// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [127:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [127:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
wire   [0:0] icmp_ln249_fu_530_p2;
wire   [0:0] icmp_ln253_fu_542_p2;
reg    ap_predicate_op27_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_CS_iter3_fsm_state4;
reg   [0:0] icmp_ln249_reg_3625;
reg   [0:0] icmp_ln249_reg_3625_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
wire    ap_CS_iter4_fsm_state5;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [5:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [6:0] p_ZL7threshs_1_q0;
wire   [5:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [6:0] p_ZL7threshs_2_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_3_reg_3620;
reg   [0:0] icmp_ln249_reg_3625_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_3625_pp0_iter2_reg;
wire   [1:0] local_temp_fu_553_p1;
reg  signed [1:0] local_temp_reg_3632;
reg  signed [1:0] local_temp_1_reg_3637;
reg  signed [1:0] local_temp_2_reg_3642;
reg  signed [1:0] local_temp_3_reg_3647;
reg  signed [1:0] local_temp_4_reg_3652;
reg  signed [1:0] local_temp_5_reg_3657;
reg  signed [1:0] local_temp_6_reg_3662;
reg  signed [1:0] local_temp_7_reg_3667;
reg  signed [1:0] local_temp_8_reg_3672;
reg  signed [1:0] local_temp_9_reg_3677;
reg  signed [1:0] local_temp_10_reg_3682;
reg  signed [1:0] local_temp_11_reg_3687;
reg  signed [1:0] local_temp_12_reg_3692;
reg  signed [1:0] local_temp_13_reg_3697;
reg  signed [1:0] local_temp_14_reg_3702;
reg  signed [1:0] local_temp_15_reg_3707;
reg  signed [1:0] local_temp_16_reg_3712;
reg  signed [1:0] local_temp_17_reg_3717;
reg  signed [1:0] local_temp_18_reg_3722;
reg  signed [1:0] local_temp_19_reg_3727;
reg  signed [1:0] local_temp_20_reg_3732;
reg  signed [1:0] local_temp_21_reg_3737;
reg  signed [1:0] local_temp_22_reg_3742;
reg  signed [1:0] local_temp_23_reg_3747;
reg  signed [1:0] local_temp_24_reg_3752;
reg  signed [1:0] local_temp_25_reg_3757;
reg  signed [1:0] local_temp_26_reg_3762;
reg  signed [1:0] local_temp_27_reg_3767;
reg  signed [1:0] local_temp_28_reg_3772;
reg  signed [1:0] local_temp_29_reg_3777;
reg  signed [1:0] local_temp_30_reg_3782;
reg  signed [1:0] local_temp_31_reg_3787;
reg  signed [1:0] local_temp_32_reg_3792;
reg  signed [1:0] local_temp_33_reg_3797;
reg  signed [1:0] local_temp_34_reg_3802;
reg  signed [1:0] local_temp_35_reg_3807;
reg  signed [1:0] local_temp_36_reg_3812;
reg  signed [1:0] local_temp_37_reg_3817;
reg  signed [1:0] local_temp_38_reg_3822;
reg  signed [1:0] local_temp_39_reg_3827;
reg  signed [1:0] local_temp_40_reg_3832;
reg  signed [1:0] local_temp_41_reg_3837;
reg  signed [1:0] local_temp_42_reg_3842;
reg  signed [1:0] local_temp_43_reg_3847;
reg  signed [1:0] local_temp_44_reg_3852;
reg  signed [1:0] local_temp_45_reg_3857;
reg  signed [1:0] local_temp_46_reg_3862;
reg  signed [1:0] local_temp_47_reg_3867;
reg  signed [1:0] local_temp_48_reg_3872;
reg  signed [1:0] local_temp_49_reg_3877;
reg  signed [1:0] local_temp_50_reg_3882;
reg  signed [1:0] local_temp_51_reg_3887;
reg  signed [1:0] local_temp_52_reg_3892;
reg  signed [1:0] local_temp_53_reg_3897;
reg  signed [1:0] local_temp_54_reg_3902;
reg  signed [1:0] local_temp_55_reg_3907;
reg  signed [1:0] local_temp_56_reg_3912;
reg  signed [1:0] local_temp_57_reg_3917;
reg  signed [1:0] local_temp_58_reg_3922;
reg  signed [1:0] local_temp_59_reg_3927;
reg  signed [1:0] local_temp_60_reg_3932;
reg  signed [1:0] local_temp_61_reg_3937;
reg  signed [1:0] local_temp_62_reg_3942;
reg  signed [1:0] local_temp_63_reg_3947;
wire   [5:0] add_ln169_2_fu_2962_p2;
reg   [5:0] add_ln169_2_reg_3952;
wire   [5:0] add_ln169_5_fu_2988_p2;
reg   [5:0] add_ln169_5_reg_3957;
wire   [5:0] add_ln169_9_fu_3014_p2;
reg   [5:0] add_ln169_9_reg_3962;
wire   [5:0] add_ln169_12_fu_3040_p2;
reg   [5:0] add_ln169_12_reg_3967;
wire   [5:0] add_ln169_17_fu_3066_p2;
reg   [5:0] add_ln169_17_reg_3972;
wire   [5:0] add_ln169_20_fu_3092_p2;
reg   [5:0] add_ln169_20_reg_3977;
wire   [5:0] add_ln169_24_fu_3118_p2;
reg   [5:0] add_ln169_24_reg_3982;
wire   [5:0] add_ln169_27_fu_3144_p2;
reg   [5:0] add_ln169_27_reg_3987;
wire   [5:0] add_ln169_33_fu_3170_p2;
reg   [5:0] add_ln169_33_reg_3992;
wire   [5:0] add_ln169_36_fu_3196_p2;
reg   [5:0] add_ln169_36_reg_3997;
wire   [5:0] add_ln169_40_fu_3222_p2;
reg   [5:0] add_ln169_40_reg_4002;
wire   [5:0] add_ln169_43_fu_3248_p2;
reg   [5:0] add_ln169_43_reg_4007;
wire   [5:0] add_ln169_48_fu_3274_p2;
reg   [5:0] add_ln169_48_reg_4012;
wire   [5:0] add_ln169_51_fu_3300_p2;
reg   [5:0] add_ln169_51_reg_4017;
wire   [5:0] add_ln169_55_fu_3326_p2;
reg   [5:0] add_ln169_55_reg_4022;
wire   [5:0] add_ln169_58_fu_3352_p2;
reg   [5:0] add_ln169_58_reg_4027;
wire   [7:0] add_ln169_14_fu_3396_p2;
reg   [7:0] add_ln169_14_reg_4047;
wire   [7:0] add_ln169_29_fu_3434_p2;
reg   [7:0] add_ln169_29_reg_4052;
wire   [6:0] add_ln169_37_fu_3446_p2;
reg   [6:0] add_ln169_37_reg_4057;
wire   [6:0] add_ln169_44_fu_3458_p2;
reg   [6:0] add_ln169_44_reg_4062;
wire   [7:0] add_ln169_60_fu_3496_p2;
reg   [7:0] add_ln169_60_reg_4067;
reg   [5:0] p_ZL7threshs_0_load_reg_4072;
reg   [5:0] p_ZL7threshs_0_load_reg_4072_pp0_iter3_reg;
reg   [6:0] p_ZL7threshs_1_load_reg_4077;
reg   [6:0] p_ZL7threshs_1_load_reg_4077_pp0_iter3_reg;
reg   [6:0] p_ZL7threshs_2_load_reg_4082;
reg   [6:0] p_ZL7threshs_2_load_reg_4082_pp0_iter3_reg;
wire   [7:0] add_ln169_62_fu_3523_p2;
reg   [7:0] add_ln169_62_reg_4087;
wire   [63:0] idxprom2_i_fu_3358_p1;
reg   [31:0] nf_1_fu_444;
wire   [31:0] nf_4_fu_1199_p3;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_nf_3;
reg   [6:0] i_fu_448;
wire   [6:0] i_2_fu_536_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [127:0] arrayidx3_0_0_0_load20_fu_452;
wire   [31:0] nf_fu_1187_p2;
wire   [0:0] icmp_ln302_fu_1193_p2;
wire   [1:0] r_fu_1220_p1;
wire   [1:0] mul_ln115_fu_1231_p0;
wire  signed [3:0] mul_ln115_fu_1231_p2;
wire   [1:0] r_1_fu_1241_p4;
wire   [1:0] mul_ln115_1_fu_1258_p0;
wire  signed [3:0] mul_ln115_1_fu_1258_p2;
wire   [1:0] r_2_fu_1268_p4;
wire   [1:0] mul_ln115_2_fu_1285_p0;
wire  signed [3:0] mul_ln115_2_fu_1285_p2;
wire   [1:0] r_3_fu_1295_p4;
wire   [1:0] mul_ln115_3_fu_1312_p0;
wire  signed [3:0] mul_ln115_3_fu_1312_p2;
wire   [1:0] r_4_fu_1322_p4;
wire   [1:0] mul_ln115_4_fu_1339_p0;
wire  signed [3:0] mul_ln115_4_fu_1339_p2;
wire   [1:0] r_5_fu_1349_p4;
wire   [1:0] mul_ln115_5_fu_1366_p0;
wire  signed [3:0] mul_ln115_5_fu_1366_p2;
wire   [1:0] r_6_fu_1376_p4;
wire   [1:0] mul_ln115_6_fu_1393_p0;
wire  signed [3:0] mul_ln115_6_fu_1393_p2;
wire   [1:0] r_7_fu_1403_p4;
wire   [1:0] mul_ln115_7_fu_1420_p0;
wire  signed [3:0] mul_ln115_7_fu_1420_p2;
wire   [1:0] r_8_fu_1430_p4;
wire   [1:0] mul_ln115_8_fu_1447_p0;
wire  signed [3:0] mul_ln115_8_fu_1447_p2;
wire   [1:0] r_9_fu_1457_p4;
wire   [1:0] mul_ln115_9_fu_1474_p0;
wire  signed [3:0] mul_ln115_9_fu_1474_p2;
wire   [1:0] r_10_fu_1484_p4;
wire   [1:0] mul_ln115_10_fu_1501_p0;
wire  signed [3:0] mul_ln115_10_fu_1501_p2;
wire   [1:0] r_11_fu_1511_p4;
wire   [1:0] mul_ln115_11_fu_1528_p0;
wire  signed [3:0] mul_ln115_11_fu_1528_p2;
wire   [1:0] r_12_fu_1538_p4;
wire   [1:0] mul_ln115_12_fu_1555_p0;
wire  signed [3:0] mul_ln115_12_fu_1555_p2;
wire   [1:0] r_13_fu_1565_p4;
wire   [1:0] mul_ln115_13_fu_1582_p0;
wire  signed [3:0] mul_ln115_13_fu_1582_p2;
wire   [1:0] r_14_fu_1592_p4;
wire   [1:0] mul_ln115_14_fu_1609_p0;
wire  signed [3:0] mul_ln115_14_fu_1609_p2;
wire   [1:0] r_15_fu_1619_p4;
wire   [1:0] mul_ln115_15_fu_1636_p0;
wire  signed [3:0] mul_ln115_15_fu_1636_p2;
wire   [1:0] r_16_fu_1646_p4;
wire   [1:0] mul_ln115_16_fu_1663_p0;
wire  signed [3:0] mul_ln115_16_fu_1663_p2;
wire   [1:0] r_17_fu_1673_p4;
wire   [1:0] mul_ln115_17_fu_1690_p0;
wire  signed [3:0] mul_ln115_17_fu_1690_p2;
wire   [1:0] r_18_fu_1700_p4;
wire   [1:0] mul_ln115_18_fu_1717_p0;
wire  signed [3:0] mul_ln115_18_fu_1717_p2;
wire   [1:0] r_19_fu_1727_p4;
wire   [1:0] mul_ln115_19_fu_1744_p0;
wire  signed [3:0] mul_ln115_19_fu_1744_p2;
wire   [1:0] r_20_fu_1754_p4;
wire   [1:0] mul_ln115_20_fu_1771_p0;
wire  signed [3:0] mul_ln115_20_fu_1771_p2;
wire   [1:0] r_21_fu_1781_p4;
wire   [1:0] mul_ln115_21_fu_1798_p0;
wire  signed [3:0] mul_ln115_21_fu_1798_p2;
wire   [1:0] r_22_fu_1808_p4;
wire   [1:0] mul_ln115_22_fu_1825_p0;
wire  signed [3:0] mul_ln115_22_fu_1825_p2;
wire   [1:0] r_23_fu_1835_p4;
wire   [1:0] mul_ln115_23_fu_1852_p0;
wire  signed [3:0] mul_ln115_23_fu_1852_p2;
wire   [1:0] r_24_fu_1862_p4;
wire   [1:0] mul_ln115_24_fu_1879_p0;
wire  signed [3:0] mul_ln115_24_fu_1879_p2;
wire   [1:0] r_25_fu_1889_p4;
wire   [1:0] mul_ln115_25_fu_1906_p0;
wire  signed [3:0] mul_ln115_25_fu_1906_p2;
wire   [1:0] r_26_fu_1916_p4;
wire   [1:0] mul_ln115_26_fu_1933_p0;
wire  signed [3:0] mul_ln115_26_fu_1933_p2;
wire   [1:0] r_27_fu_1943_p4;
wire   [1:0] mul_ln115_27_fu_1960_p0;
wire  signed [3:0] mul_ln115_27_fu_1960_p2;
wire   [1:0] r_28_fu_1970_p4;
wire   [1:0] mul_ln115_28_fu_1987_p0;
wire  signed [3:0] mul_ln115_28_fu_1987_p2;
wire   [1:0] r_29_fu_1997_p4;
wire   [1:0] mul_ln115_29_fu_2014_p0;
wire  signed [3:0] mul_ln115_29_fu_2014_p2;
wire   [1:0] r_30_fu_2024_p4;
wire   [1:0] mul_ln115_30_fu_2041_p0;
wire  signed [3:0] mul_ln115_30_fu_2041_p2;
wire   [1:0] r_31_fu_2051_p4;
wire   [1:0] mul_ln115_31_fu_2068_p0;
wire  signed [3:0] mul_ln115_31_fu_2068_p2;
wire   [1:0] r_32_fu_2078_p4;
wire   [1:0] mul_ln115_32_fu_2095_p0;
wire  signed [3:0] mul_ln115_32_fu_2095_p2;
wire   [1:0] r_33_fu_2105_p4;
wire   [1:0] mul_ln115_33_fu_2122_p0;
wire  signed [3:0] mul_ln115_33_fu_2122_p2;
wire   [1:0] r_34_fu_2132_p4;
wire   [1:0] mul_ln115_34_fu_2149_p0;
wire  signed [3:0] mul_ln115_34_fu_2149_p2;
wire   [1:0] r_35_fu_2159_p4;
wire   [1:0] mul_ln115_35_fu_2176_p0;
wire  signed [3:0] mul_ln115_35_fu_2176_p2;
wire   [1:0] r_36_fu_2186_p4;
wire   [1:0] mul_ln115_36_fu_2203_p0;
wire  signed [3:0] mul_ln115_36_fu_2203_p2;
wire   [1:0] r_37_fu_2213_p4;
wire   [1:0] mul_ln115_37_fu_2230_p0;
wire  signed [3:0] mul_ln115_37_fu_2230_p2;
wire   [1:0] r_38_fu_2240_p4;
wire   [1:0] mul_ln115_38_fu_2257_p0;
wire  signed [3:0] mul_ln115_38_fu_2257_p2;
wire   [1:0] r_39_fu_2267_p4;
wire   [1:0] mul_ln115_39_fu_2284_p0;
wire  signed [3:0] mul_ln115_39_fu_2284_p2;
wire   [1:0] r_40_fu_2294_p4;
wire   [1:0] mul_ln115_40_fu_2311_p0;
wire  signed [3:0] mul_ln115_40_fu_2311_p2;
wire   [1:0] r_41_fu_2321_p4;
wire   [1:0] mul_ln115_41_fu_2338_p0;
wire  signed [3:0] mul_ln115_41_fu_2338_p2;
wire   [1:0] r_42_fu_2348_p4;
wire   [1:0] mul_ln115_42_fu_2365_p0;
wire  signed [3:0] mul_ln115_42_fu_2365_p2;
wire   [1:0] r_43_fu_2375_p4;
wire   [1:0] mul_ln115_43_fu_2392_p0;
wire  signed [3:0] mul_ln115_43_fu_2392_p2;
wire   [1:0] r_44_fu_2402_p4;
wire   [1:0] mul_ln115_44_fu_2419_p0;
wire  signed [3:0] mul_ln115_44_fu_2419_p2;
wire   [1:0] r_45_fu_2429_p4;
wire   [1:0] mul_ln115_45_fu_2446_p0;
wire  signed [3:0] mul_ln115_45_fu_2446_p2;
wire   [1:0] r_46_fu_2456_p4;
wire   [1:0] mul_ln115_46_fu_2473_p0;
wire  signed [3:0] mul_ln115_46_fu_2473_p2;
wire   [1:0] r_47_fu_2483_p4;
wire   [1:0] mul_ln115_47_fu_2500_p0;
wire  signed [3:0] mul_ln115_47_fu_2500_p2;
wire   [1:0] r_48_fu_2510_p4;
wire   [1:0] mul_ln115_48_fu_2527_p0;
wire  signed [3:0] mul_ln115_48_fu_2527_p2;
wire   [1:0] r_49_fu_2537_p4;
wire   [1:0] mul_ln115_49_fu_2554_p0;
wire  signed [3:0] mul_ln115_49_fu_2554_p2;
wire   [1:0] r_50_fu_2564_p4;
wire   [1:0] mul_ln115_50_fu_2581_p0;
wire  signed [3:0] mul_ln115_50_fu_2581_p2;
wire   [1:0] r_51_fu_2591_p4;
wire   [1:0] mul_ln115_51_fu_2608_p0;
wire  signed [3:0] mul_ln115_51_fu_2608_p2;
wire   [1:0] r_52_fu_2618_p4;
wire   [1:0] mul_ln115_52_fu_2635_p0;
wire  signed [3:0] mul_ln115_52_fu_2635_p2;
wire   [1:0] r_53_fu_2645_p4;
wire   [1:0] mul_ln115_53_fu_2662_p0;
wire  signed [3:0] mul_ln115_53_fu_2662_p2;
wire   [1:0] r_54_fu_2672_p4;
wire   [1:0] mul_ln115_54_fu_2689_p0;
wire  signed [3:0] mul_ln115_54_fu_2689_p2;
wire   [1:0] r_55_fu_2699_p4;
wire   [1:0] mul_ln115_55_fu_2716_p0;
wire  signed [3:0] mul_ln115_55_fu_2716_p2;
wire   [1:0] r_56_fu_2726_p4;
wire   [1:0] mul_ln115_56_fu_2743_p0;
wire  signed [3:0] mul_ln115_56_fu_2743_p2;
wire   [1:0] r_57_fu_2753_p4;
wire   [1:0] mul_ln115_57_fu_2770_p0;
wire  signed [3:0] mul_ln115_57_fu_2770_p2;
wire   [1:0] r_58_fu_2780_p4;
wire   [1:0] mul_ln115_58_fu_2797_p0;
wire  signed [3:0] mul_ln115_58_fu_2797_p2;
wire   [1:0] r_59_fu_2807_p4;
wire   [1:0] mul_ln115_59_fu_2824_p0;
wire  signed [3:0] mul_ln115_59_fu_2824_p2;
wire   [1:0] r_60_fu_2834_p4;
wire   [1:0] mul_ln115_60_fu_2851_p0;
wire  signed [3:0] mul_ln115_60_fu_2851_p2;
wire   [1:0] r_61_fu_2861_p4;
wire   [1:0] mul_ln115_61_fu_2878_p0;
wire  signed [3:0] mul_ln115_61_fu_2878_p2;
wire   [1:0] r_62_fu_2888_p4;
wire   [1:0] mul_ln115_62_fu_2905_p0;
wire  signed [3:0] mul_ln115_62_fu_2905_p2;
wire   [1:0] r_63_fu_2915_p4;
wire   [1:0] mul_ln115_63_fu_2932_p0;
wire  signed [3:0] mul_ln115_63_fu_2932_p2;
wire  signed [4:0] sext_ln216_61_fu_2884_p1;
wire  signed [4:0] sext_ln216_62_fu_2911_p1;
wire   [4:0] add_ln169_fu_2942_p2;
wire  signed [4:0] sext_ln216_60_fu_2857_p1;
wire  signed [4:0] sext_ln216_59_fu_2830_p1;
wire   [4:0] add_ln169_1_fu_2952_p2;
wire  signed [5:0] sext_ln169_2_fu_2958_p1;
wire  signed [5:0] sext_ln169_1_fu_2948_p1;
wire  signed [4:0] sext_ln216_56_fu_2749_p1;
wire  signed [4:0] sext_ln216_55_fu_2722_p1;
wire   [4:0] add_ln169_3_fu_2968_p2;
wire  signed [4:0] sext_ln216_58_fu_2803_p1;
wire  signed [4:0] sext_ln216_57_fu_2776_p1;
wire   [4:0] add_ln169_4_fu_2978_p2;
wire  signed [5:0] sext_ln169_5_fu_2984_p1;
wire  signed [5:0] sext_ln169_4_fu_2974_p1;
wire  signed [4:0] sext_ln216_48_fu_2533_p1;
wire  signed [4:0] sext_ln216_47_fu_2506_p1;
wire   [4:0] add_ln169_7_fu_2994_p2;
wire  signed [4:0] sext_ln216_50_fu_2587_p1;
wire  signed [4:0] sext_ln216_49_fu_2560_p1;
wire   [4:0] add_ln169_8_fu_3004_p2;
wire  signed [5:0] sext_ln169_9_fu_3010_p1;
wire  signed [5:0] sext_ln169_8_fu_3000_p1;
wire  signed [4:0] sext_ln216_52_fu_2641_p1;
wire  signed [4:0] sext_ln216_51_fu_2614_p1;
wire   [4:0] add_ln169_10_fu_3020_p2;
wire  signed [4:0] sext_ln216_54_fu_2695_p1;
wire  signed [4:0] sext_ln216_53_fu_2668_p1;
wire   [4:0] add_ln169_11_fu_3030_p2;
wire  signed [5:0] sext_ln169_12_fu_3036_p1;
wire  signed [5:0] sext_ln169_11_fu_3026_p1;
wire  signed [4:0] sext_ln216_32_fu_2101_p1;
wire  signed [4:0] sext_ln216_31_fu_2074_p1;
wire   [4:0] add_ln169_15_fu_3046_p2;
wire  signed [4:0] sext_ln216_34_fu_2155_p1;
wire  signed [4:0] sext_ln216_33_fu_2128_p1;
wire   [4:0] add_ln169_16_fu_3056_p2;
wire  signed [5:0] sext_ln169_16_fu_3062_p1;
wire  signed [5:0] sext_ln169_15_fu_3052_p1;
wire  signed [4:0] sext_ln216_36_fu_2209_p1;
wire  signed [4:0] sext_ln216_35_fu_2182_p1;
wire   [4:0] add_ln169_18_fu_3072_p2;
wire  signed [4:0] sext_ln216_38_fu_2263_p1;
wire  signed [4:0] sext_ln216_37_fu_2236_p1;
wire   [4:0] add_ln169_19_fu_3082_p2;
wire  signed [5:0] sext_ln169_19_fu_3088_p1;
wire  signed [5:0] sext_ln169_18_fu_3078_p1;
wire  signed [4:0] sext_ln216_40_fu_2317_p1;
wire  signed [4:0] sext_ln216_39_fu_2290_p1;
wire   [4:0] add_ln169_22_fu_3098_p2;
wire  signed [4:0] sext_ln216_42_fu_2371_p1;
wire  signed [4:0] sext_ln216_41_fu_2344_p1;
wire   [4:0] add_ln169_23_fu_3108_p2;
wire  signed [5:0] sext_ln169_23_fu_3114_p1;
wire  signed [5:0] sext_ln169_22_fu_3104_p1;
wire  signed [4:0] sext_ln216_44_fu_2425_p1;
wire  signed [4:0] sext_ln216_43_fu_2398_p1;
wire   [4:0] add_ln169_25_fu_3124_p2;
wire  signed [4:0] sext_ln216_46_fu_2479_p1;
wire  signed [4:0] sext_ln216_45_fu_2452_p1;
wire   [4:0] add_ln169_26_fu_3134_p2;
wire  signed [5:0] sext_ln169_26_fu_3140_p1;
wire  signed [5:0] sext_ln169_25_fu_3130_p1;
wire  signed [4:0] sext_ln216_1_fu_1264_p1;
wire  signed [4:0] sext_ln216_2_fu_1291_p1;
wire   [4:0] add_ln169_31_fu_3150_p2;
wire  signed [4:0] sext_ln216_fu_1237_p1;
wire  signed [4:0] sext_ln216_4_fu_1345_p1;
wire   [4:0] add_ln169_32_fu_3160_p2;
wire  signed [5:0] sext_ln169_30_fu_3166_p1;
wire  signed [5:0] sext_ln169_29_fu_3156_p1;
wire  signed [4:0] sext_ln216_3_fu_1318_p1;
wire  signed [4:0] sext_ln216_6_fu_1399_p1;
wire   [4:0] add_ln169_34_fu_3176_p2;
wire  signed [4:0] sext_ln216_5_fu_1372_p1;
wire  signed [4:0] sext_ln216_8_fu_1453_p1;
wire   [4:0] add_ln169_35_fu_3186_p2;
wire  signed [5:0] sext_ln169_33_fu_3192_p1;
wire  signed [5:0] sext_ln169_32_fu_3182_p1;
wire  signed [4:0] sext_ln216_7_fu_1426_p1;
wire  signed [4:0] sext_ln216_10_fu_1507_p1;
wire   [4:0] add_ln169_38_fu_3202_p2;
wire  signed [4:0] sext_ln216_9_fu_1480_p1;
wire  signed [4:0] sext_ln216_12_fu_1561_p1;
wire   [4:0] add_ln169_39_fu_3212_p2;
wire  signed [5:0] sext_ln169_37_fu_3218_p1;
wire  signed [5:0] sext_ln169_36_fu_3208_p1;
wire  signed [4:0] sext_ln216_11_fu_1534_p1;
wire  signed [4:0] sext_ln216_14_fu_1615_p1;
wire   [4:0] add_ln169_41_fu_3228_p2;
wire  signed [4:0] sext_ln216_13_fu_1588_p1;
wire  signed [4:0] sext_ln216_16_fu_1669_p1;
wire   [4:0] add_ln169_42_fu_3238_p2;
wire  signed [5:0] sext_ln169_40_fu_3244_p1;
wire  signed [5:0] sext_ln169_39_fu_3234_p1;
wire  signed [4:0] sext_ln216_15_fu_1642_p1;
wire  signed [4:0] sext_ln216_18_fu_1723_p1;
wire   [4:0] add_ln169_46_fu_3254_p2;
wire  signed [4:0] sext_ln216_17_fu_1696_p1;
wire  signed [4:0] sext_ln216_20_fu_1777_p1;
wire   [4:0] add_ln169_47_fu_3264_p2;
wire  signed [5:0] sext_ln169_44_fu_3270_p1;
wire  signed [5:0] sext_ln169_43_fu_3260_p1;
wire  signed [4:0] sext_ln216_19_fu_1750_p1;
wire  signed [4:0] sext_ln216_22_fu_1831_p1;
wire   [4:0] add_ln169_49_fu_3280_p2;
wire  signed [4:0] sext_ln216_21_fu_1804_p1;
wire  signed [4:0] sext_ln216_24_fu_1885_p1;
wire   [4:0] add_ln169_50_fu_3290_p2;
wire  signed [5:0] sext_ln169_47_fu_3296_p1;
wire  signed [5:0] sext_ln169_46_fu_3286_p1;
wire  signed [4:0] sext_ln216_23_fu_1858_p1;
wire  signed [4:0] sext_ln216_26_fu_1939_p1;
wire   [4:0] add_ln169_53_fu_3306_p2;
wire  signed [4:0] sext_ln216_25_fu_1912_p1;
wire  signed [4:0] sext_ln216_28_fu_1993_p1;
wire   [4:0] add_ln169_54_fu_3316_p2;
wire  signed [5:0] sext_ln169_51_fu_3322_p1;
wire  signed [5:0] sext_ln169_50_fu_3312_p1;
wire  signed [4:0] sext_ln216_27_fu_1966_p1;
wire  signed [4:0] sext_ln216_30_fu_2047_p1;
wire   [4:0] add_ln169_56_fu_3332_p2;
wire  signed [4:0] sext_ln216_29_fu_2020_p1;
wire  signed [4:0] sext_ln169_fu_2938_p1;
wire   [4:0] add_ln169_57_fu_3342_p2;
wire  signed [5:0] sext_ln169_54_fu_3348_p1;
wire  signed [5:0] sext_ln169_53_fu_3338_p1;
wire  signed [6:0] sext_ln169_6_fu_3367_p1;
wire  signed [6:0] sext_ln169_3_fu_3364_p1;
wire   [6:0] add_ln169_6_fu_3370_p2;
wire  signed [6:0] sext_ln169_13_fu_3383_p1;
wire  signed [6:0] sext_ln169_10_fu_3380_p1;
wire   [6:0] add_ln169_13_fu_3386_p2;
wire  signed [7:0] sext_ln169_14_fu_3392_p1;
wire  signed [7:0] sext_ln169_7_fu_3376_p1;
wire  signed [6:0] sext_ln169_20_fu_3405_p1;
wire  signed [6:0] sext_ln169_17_fu_3402_p1;
wire   [6:0] add_ln169_21_fu_3408_p2;
wire  signed [6:0] sext_ln169_27_fu_3421_p1;
wire  signed [6:0] sext_ln169_24_fu_3418_p1;
wire   [6:0] add_ln169_28_fu_3424_p2;
wire  signed [7:0] sext_ln169_28_fu_3430_p1;
wire  signed [7:0] sext_ln169_21_fu_3414_p1;
wire  signed [6:0] sext_ln169_34_fu_3443_p1;
wire  signed [6:0] sext_ln169_31_fu_3440_p1;
wire  signed [6:0] sext_ln169_41_fu_3455_p1;
wire  signed [6:0] sext_ln169_38_fu_3452_p1;
wire  signed [6:0] sext_ln169_48_fu_3467_p1;
wire  signed [6:0] sext_ln169_45_fu_3464_p1;
wire   [6:0] add_ln169_52_fu_3470_p2;
wire  signed [6:0] sext_ln169_55_fu_3483_p1;
wire  signed [6:0] sext_ln169_52_fu_3480_p1;
wire   [6:0] add_ln169_59_fu_3486_p2;
wire  signed [7:0] sext_ln169_56_fu_3492_p1;
wire  signed [7:0] sext_ln169_49_fu_3476_p1;
wire  signed [7:0] sext_ln169_42_fu_3509_p1;
wire  signed [7:0] sext_ln169_35_fu_3506_p1;
wire   [7:0] add_ln169_45_fu_3512_p2;
wire   [7:0] add_ln169_61_fu_3518_p2;
wire   [7:0] add_ln169_30_fu_3502_p2;
wire   [7:0] zext_ln108_fu_3529_p1;
wire   [0:0] icmp_ln108_fu_3532_p2;
wire   [0:0] result_fu_3537_p2;
wire   [7:0] zext_ln108_1_fu_3547_p1;
wire   [0:0] icmp_ln108_1_fu_3550_p2;
wire   [0:0] xor_ln108_fu_3555_p2;
wire   [7:0] zext_ln108_2_fu_3565_p1;
wire   [0:0] icmp_ln108_2_fu_3568_p2;
wire   [0:0] xor_ln108_1_fu_3573_p2;
wire   [1:0] zext_ln218_2_fu_3543_p1;
wire   [1:0] zext_ln218_1_fu_3579_p1;
wire   [1:0] add_ln218_fu_3583_p2;
wire   [1:0] zext_ln218_fu_3561_p1;
wire   [1:0] result_2_fu_3589_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
wire    ap_start_int;
wire   [3:0] mul_ln115_10_fu_1501_p00;
wire   [3:0] mul_ln115_11_fu_1528_p00;
wire   [3:0] mul_ln115_12_fu_1555_p00;
wire   [3:0] mul_ln115_13_fu_1582_p00;
wire   [3:0] mul_ln115_14_fu_1609_p00;
wire   [3:0] mul_ln115_15_fu_1636_p00;
wire   [3:0] mul_ln115_16_fu_1663_p00;
wire   [3:0] mul_ln115_17_fu_1690_p00;
wire   [3:0] mul_ln115_18_fu_1717_p00;
wire   [3:0] mul_ln115_19_fu_1744_p00;
wire   [3:0] mul_ln115_1_fu_1258_p00;
wire   [3:0] mul_ln115_20_fu_1771_p00;
wire   [3:0] mul_ln115_21_fu_1798_p00;
wire   [3:0] mul_ln115_22_fu_1825_p00;
wire   [3:0] mul_ln115_23_fu_1852_p00;
wire   [3:0] mul_ln115_24_fu_1879_p00;
wire   [3:0] mul_ln115_25_fu_1906_p00;
wire   [3:0] mul_ln115_26_fu_1933_p00;
wire   [3:0] mul_ln115_27_fu_1960_p00;
wire   [3:0] mul_ln115_28_fu_1987_p00;
wire   [3:0] mul_ln115_29_fu_2014_p00;
wire   [3:0] mul_ln115_2_fu_1285_p00;
wire   [3:0] mul_ln115_30_fu_2041_p00;
wire   [3:0] mul_ln115_31_fu_2068_p00;
wire   [3:0] mul_ln115_32_fu_2095_p00;
wire   [3:0] mul_ln115_33_fu_2122_p00;
wire   [3:0] mul_ln115_34_fu_2149_p00;
wire   [3:0] mul_ln115_35_fu_2176_p00;
wire   [3:0] mul_ln115_36_fu_2203_p00;
wire   [3:0] mul_ln115_37_fu_2230_p00;
wire   [3:0] mul_ln115_38_fu_2257_p00;
wire   [3:0] mul_ln115_39_fu_2284_p00;
wire   [3:0] mul_ln115_3_fu_1312_p00;
wire   [3:0] mul_ln115_40_fu_2311_p00;
wire   [3:0] mul_ln115_41_fu_2338_p00;
wire   [3:0] mul_ln115_42_fu_2365_p00;
wire   [3:0] mul_ln115_43_fu_2392_p00;
wire   [3:0] mul_ln115_44_fu_2419_p00;
wire   [3:0] mul_ln115_45_fu_2446_p00;
wire   [3:0] mul_ln115_46_fu_2473_p00;
wire   [3:0] mul_ln115_47_fu_2500_p00;
wire   [3:0] mul_ln115_48_fu_2527_p00;
wire   [3:0] mul_ln115_49_fu_2554_p00;
wire   [3:0] mul_ln115_4_fu_1339_p00;
wire   [3:0] mul_ln115_50_fu_2581_p00;
wire   [3:0] mul_ln115_51_fu_2608_p00;
wire   [3:0] mul_ln115_52_fu_2635_p00;
wire   [3:0] mul_ln115_53_fu_2662_p00;
wire   [3:0] mul_ln115_54_fu_2689_p00;
wire   [3:0] mul_ln115_55_fu_2716_p00;
wire   [3:0] mul_ln115_56_fu_2743_p00;
wire   [3:0] mul_ln115_57_fu_2770_p00;
wire   [3:0] mul_ln115_58_fu_2797_p00;
wire   [3:0] mul_ln115_59_fu_2824_p00;
wire   [3:0] mul_ln115_5_fu_1366_p00;
wire   [3:0] mul_ln115_60_fu_2851_p00;
wire   [3:0] mul_ln115_61_fu_2878_p00;
wire   [3:0] mul_ln115_62_fu_2905_p00;
wire   [3:0] mul_ln115_63_fu_2932_p00;
wire   [3:0] mul_ln115_6_fu_1393_p00;
wire   [3:0] mul_ln115_7_fu_1420_p00;
wire   [3:0] mul_ln115_8_fu_1447_p00;
wire   [3:0] mul_ln115_9_fu_1474_p00;
wire   [3:0] mul_ln115_fu_1231_p00;
reg    ap_condition_111;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 nf_1_fu_444 = 32'd0;
#0 i_fu_448 = 7'd0;
#0 arrayidx3_0_0_0_load20_fu_452 = 128'd0;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U1(
    .din0(mul_ln115_fu_1231_p0),
    .din1(local_temp_reg_3632),
    .dout(mul_ln115_fu_1231_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln115_1_fu_1258_p0),
    .din1(local_temp_1_reg_3637),
    .dout(mul_ln115_1_fu_1258_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(mul_ln115_2_fu_1285_p0),
    .din1(local_temp_2_reg_3642),
    .dout(mul_ln115_2_fu_1285_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(mul_ln115_3_fu_1312_p0),
    .din1(local_temp_3_reg_3647),
    .dout(mul_ln115_3_fu_1312_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U5(
    .din0(mul_ln115_4_fu_1339_p0),
    .din1(local_temp_4_reg_3652),
    .dout(mul_ln115_4_fu_1339_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U6(
    .din0(mul_ln115_5_fu_1366_p0),
    .din1(local_temp_5_reg_3657),
    .dout(mul_ln115_5_fu_1366_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U7(
    .din0(mul_ln115_6_fu_1393_p0),
    .din1(local_temp_6_reg_3662),
    .dout(mul_ln115_6_fu_1393_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U8(
    .din0(mul_ln115_7_fu_1420_p0),
    .din1(local_temp_7_reg_3667),
    .dout(mul_ln115_7_fu_1420_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U9(
    .din0(mul_ln115_8_fu_1447_p0),
    .din1(local_temp_8_reg_3672),
    .dout(mul_ln115_8_fu_1447_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U10(
    .din0(mul_ln115_9_fu_1474_p0),
    .din1(local_temp_9_reg_3677),
    .dout(mul_ln115_9_fu_1474_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U11(
    .din0(mul_ln115_10_fu_1501_p0),
    .din1(local_temp_10_reg_3682),
    .dout(mul_ln115_10_fu_1501_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U12(
    .din0(mul_ln115_11_fu_1528_p0),
    .din1(local_temp_11_reg_3687),
    .dout(mul_ln115_11_fu_1528_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U13(
    .din0(mul_ln115_12_fu_1555_p0),
    .din1(local_temp_12_reg_3692),
    .dout(mul_ln115_12_fu_1555_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U14(
    .din0(mul_ln115_13_fu_1582_p0),
    .din1(local_temp_13_reg_3697),
    .dout(mul_ln115_13_fu_1582_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U15(
    .din0(mul_ln115_14_fu_1609_p0),
    .din1(local_temp_14_reg_3702),
    .dout(mul_ln115_14_fu_1609_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U16(
    .din0(mul_ln115_15_fu_1636_p0),
    .din1(local_temp_15_reg_3707),
    .dout(mul_ln115_15_fu_1636_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U17(
    .din0(mul_ln115_16_fu_1663_p0),
    .din1(local_temp_16_reg_3712),
    .dout(mul_ln115_16_fu_1663_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U18(
    .din0(mul_ln115_17_fu_1690_p0),
    .din1(local_temp_17_reg_3717),
    .dout(mul_ln115_17_fu_1690_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U19(
    .din0(mul_ln115_18_fu_1717_p0),
    .din1(local_temp_18_reg_3722),
    .dout(mul_ln115_18_fu_1717_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U20(
    .din0(mul_ln115_19_fu_1744_p0),
    .din1(local_temp_19_reg_3727),
    .dout(mul_ln115_19_fu_1744_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U21(
    .din0(mul_ln115_20_fu_1771_p0),
    .din1(local_temp_20_reg_3732),
    .dout(mul_ln115_20_fu_1771_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U22(
    .din0(mul_ln115_21_fu_1798_p0),
    .din1(local_temp_21_reg_3737),
    .dout(mul_ln115_21_fu_1798_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U23(
    .din0(mul_ln115_22_fu_1825_p0),
    .din1(local_temp_22_reg_3742),
    .dout(mul_ln115_22_fu_1825_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U24(
    .din0(mul_ln115_23_fu_1852_p0),
    .din1(local_temp_23_reg_3747),
    .dout(mul_ln115_23_fu_1852_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U25(
    .din0(mul_ln115_24_fu_1879_p0),
    .din1(local_temp_24_reg_3752),
    .dout(mul_ln115_24_fu_1879_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U26(
    .din0(mul_ln115_25_fu_1906_p0),
    .din1(local_temp_25_reg_3757),
    .dout(mul_ln115_25_fu_1906_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U27(
    .din0(mul_ln115_26_fu_1933_p0),
    .din1(local_temp_26_reg_3762),
    .dout(mul_ln115_26_fu_1933_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U28(
    .din0(mul_ln115_27_fu_1960_p0),
    .din1(local_temp_27_reg_3767),
    .dout(mul_ln115_27_fu_1960_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U29(
    .din0(mul_ln115_28_fu_1987_p0),
    .din1(local_temp_28_reg_3772),
    .dout(mul_ln115_28_fu_1987_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U30(
    .din0(mul_ln115_29_fu_2014_p0),
    .din1(local_temp_29_reg_3777),
    .dout(mul_ln115_29_fu_2014_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U31(
    .din0(mul_ln115_30_fu_2041_p0),
    .din1(local_temp_30_reg_3782),
    .dout(mul_ln115_30_fu_2041_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U32(
    .din0(mul_ln115_31_fu_2068_p0),
    .din1(local_temp_31_reg_3787),
    .dout(mul_ln115_31_fu_2068_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U33(
    .din0(mul_ln115_32_fu_2095_p0),
    .din1(local_temp_32_reg_3792),
    .dout(mul_ln115_32_fu_2095_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U34(
    .din0(mul_ln115_33_fu_2122_p0),
    .din1(local_temp_33_reg_3797),
    .dout(mul_ln115_33_fu_2122_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U35(
    .din0(mul_ln115_34_fu_2149_p0),
    .din1(local_temp_34_reg_3802),
    .dout(mul_ln115_34_fu_2149_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U36(
    .din0(mul_ln115_35_fu_2176_p0),
    .din1(local_temp_35_reg_3807),
    .dout(mul_ln115_35_fu_2176_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U37(
    .din0(mul_ln115_36_fu_2203_p0),
    .din1(local_temp_36_reg_3812),
    .dout(mul_ln115_36_fu_2203_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U38(
    .din0(mul_ln115_37_fu_2230_p0),
    .din1(local_temp_37_reg_3817),
    .dout(mul_ln115_37_fu_2230_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U39(
    .din0(mul_ln115_38_fu_2257_p0),
    .din1(local_temp_38_reg_3822),
    .dout(mul_ln115_38_fu_2257_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U40(
    .din0(mul_ln115_39_fu_2284_p0),
    .din1(local_temp_39_reg_3827),
    .dout(mul_ln115_39_fu_2284_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U41(
    .din0(mul_ln115_40_fu_2311_p0),
    .din1(local_temp_40_reg_3832),
    .dout(mul_ln115_40_fu_2311_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U42(
    .din0(mul_ln115_41_fu_2338_p0),
    .din1(local_temp_41_reg_3837),
    .dout(mul_ln115_41_fu_2338_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U43(
    .din0(mul_ln115_42_fu_2365_p0),
    .din1(local_temp_42_reg_3842),
    .dout(mul_ln115_42_fu_2365_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U44(
    .din0(mul_ln115_43_fu_2392_p0),
    .din1(local_temp_43_reg_3847),
    .dout(mul_ln115_43_fu_2392_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U45(
    .din0(mul_ln115_44_fu_2419_p0),
    .din1(local_temp_44_reg_3852),
    .dout(mul_ln115_44_fu_2419_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U46(
    .din0(mul_ln115_45_fu_2446_p0),
    .din1(local_temp_45_reg_3857),
    .dout(mul_ln115_45_fu_2446_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U47(
    .din0(mul_ln115_46_fu_2473_p0),
    .din1(local_temp_46_reg_3862),
    .dout(mul_ln115_46_fu_2473_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U48(
    .din0(mul_ln115_47_fu_2500_p0),
    .din1(local_temp_47_reg_3867),
    .dout(mul_ln115_47_fu_2500_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U49(
    .din0(mul_ln115_48_fu_2527_p0),
    .din1(local_temp_48_reg_3872),
    .dout(mul_ln115_48_fu_2527_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U50(
    .din0(mul_ln115_49_fu_2554_p0),
    .din1(local_temp_49_reg_3877),
    .dout(mul_ln115_49_fu_2554_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U51(
    .din0(mul_ln115_50_fu_2581_p0),
    .din1(local_temp_50_reg_3882),
    .dout(mul_ln115_50_fu_2581_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U52(
    .din0(mul_ln115_51_fu_2608_p0),
    .din1(local_temp_51_reg_3887),
    .dout(mul_ln115_51_fu_2608_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U53(
    .din0(mul_ln115_52_fu_2635_p0),
    .din1(local_temp_52_reg_3892),
    .dout(mul_ln115_52_fu_2635_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U54(
    .din0(mul_ln115_53_fu_2662_p0),
    .din1(local_temp_53_reg_3897),
    .dout(mul_ln115_53_fu_2662_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U55(
    .din0(mul_ln115_54_fu_2689_p0),
    .din1(local_temp_54_reg_3902),
    .dout(mul_ln115_54_fu_2689_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U56(
    .din0(mul_ln115_55_fu_2716_p0),
    .din1(local_temp_55_reg_3907),
    .dout(mul_ln115_55_fu_2716_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U57(
    .din0(mul_ln115_56_fu_2743_p0),
    .din1(local_temp_56_reg_3912),
    .dout(mul_ln115_56_fu_2743_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U58(
    .din0(mul_ln115_57_fu_2770_p0),
    .din1(local_temp_57_reg_3917),
    .dout(mul_ln115_57_fu_2770_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U59(
    .din0(mul_ln115_58_fu_2797_p0),
    .din1(local_temp_58_reg_3922),
    .dout(mul_ln115_58_fu_2797_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U60(
    .din0(mul_ln115_59_fu_2824_p0),
    .din1(local_temp_59_reg_3927),
    .dout(mul_ln115_59_fu_2824_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U61(
    .din0(mul_ln115_60_fu_2851_p0),
    .din1(local_temp_60_reg_3932),
    .dout(mul_ln115_60_fu_2851_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U62(
    .din0(mul_ln115_61_fu_2878_p0),
    .din1(local_temp_61_reg_3937),
    .dout(mul_ln115_61_fu_2878_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U63(
    .din0(mul_ln115_62_fu_2905_p0),
    .din1(local_temp_62_reg_3942),
    .dout(mul_ln115_62_fu_2905_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U64(
    .din0(mul_ln115_63_fu_2932_p0),
    .din1(local_temp_63_reg_3947),
    .dout(mul_ln115_63_fu_2932_p2)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_111)) begin
        if ((icmp_ln249_fu_530_p2 == 1'd0)) begin
            i_fu_448 <= i_2_fu_536_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_448 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_111)) begin
        if ((icmp_ln249_fu_530_p2 == 1'd0)) begin
            nf_1_fu_444 <= nf_4_fu_1199_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_444 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_ln169_12_reg_3967 <= add_ln169_12_fu_3040_p2;
        add_ln169_17_reg_3972 <= add_ln169_17_fu_3066_p2;
        add_ln169_20_reg_3977 <= add_ln169_20_fu_3092_p2;
        add_ln169_24_reg_3982 <= add_ln169_24_fu_3118_p2;
        add_ln169_27_reg_3987 <= add_ln169_27_fu_3144_p2;
        add_ln169_2_reg_3952 <= add_ln169_2_fu_2962_p2;
        add_ln169_33_reg_3992 <= add_ln169_33_fu_3170_p2;
        add_ln169_36_reg_3997 <= add_ln169_36_fu_3196_p2;
        add_ln169_40_reg_4002 <= add_ln169_40_fu_3222_p2;
        add_ln169_43_reg_4007 <= add_ln169_43_fu_3248_p2;
        add_ln169_48_reg_4012 <= add_ln169_48_fu_3274_p2;
        add_ln169_51_reg_4017 <= add_ln169_51_fu_3300_p2;
        add_ln169_55_reg_4022 <= add_ln169_55_fu_3326_p2;
        add_ln169_58_reg_4027 <= add_ln169_58_fu_3352_p2;
        add_ln169_5_reg_3957 <= add_ln169_5_fu_2988_p2;
        add_ln169_9_reg_3962 <= add_ln169_9_fu_3014_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_3625_pp0_iter1_reg <= icmp_ln249_reg_3625;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        add_ln169_14_reg_4047 <= add_ln169_14_fu_3396_p2;
        add_ln169_29_reg_4052 <= add_ln169_29_fu_3434_p2;
        add_ln169_37_reg_4057 <= add_ln169_37_fu_3446_p2;
        add_ln169_44_reg_4062 <= add_ln169_44_fu_3458_p2;
        add_ln169_60_reg_4067 <= add_ln169_60_fu_3496_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_3625_pp0_iter2_reg <= icmp_ln249_reg_3625_pp0_iter1_reg;
        p_ZL7threshs_0_load_reg_4072 <= p_ZL7threshs_0_q0;
        p_ZL7threshs_1_load_reg_4077 <= p_ZL7threshs_1_q0;
        p_ZL7threshs_2_load_reg_4082 <= p_ZL7threshs_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        add_ln169_62_reg_4087 <= add_ln169_62_fu_3523_p2;
        icmp_ln249_reg_3625_pp0_iter3_reg <= icmp_ln249_reg_3625_pp0_iter2_reg;
        p_ZL7threshs_0_load_reg_4072_pp0_iter3_reg <= p_ZL7threshs_0_load_reg_4072;
        p_ZL7threshs_1_load_reg_4077_pp0_iter3_reg <= p_ZL7threshs_1_load_reg_4077;
        p_ZL7threshs_2_load_reg_4082_pp0_iter3_reg <= p_ZL7threshs_2_load_reg_4082;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_3625 <= icmp_ln249_fu_530_p2;
        local_temp_10_reg_3682 <= {{weights_V_TDATA[21:20]}};
        local_temp_11_reg_3687 <= {{weights_V_TDATA[23:22]}};
        local_temp_12_reg_3692 <= {{weights_V_TDATA[25:24]}};
        local_temp_13_reg_3697 <= {{weights_V_TDATA[27:26]}};
        local_temp_14_reg_3702 <= {{weights_V_TDATA[29:28]}};
        local_temp_15_reg_3707 <= {{weights_V_TDATA[31:30]}};
        local_temp_16_reg_3712 <= {{weights_V_TDATA[33:32]}};
        local_temp_17_reg_3717 <= {{weights_V_TDATA[35:34]}};
        local_temp_18_reg_3722 <= {{weights_V_TDATA[37:36]}};
        local_temp_19_reg_3727 <= {{weights_V_TDATA[39:38]}};
        local_temp_1_reg_3637 <= {{weights_V_TDATA[3:2]}};
        local_temp_20_reg_3732 <= {{weights_V_TDATA[41:40]}};
        local_temp_21_reg_3737 <= {{weights_V_TDATA[43:42]}};
        local_temp_22_reg_3742 <= {{weights_V_TDATA[45:44]}};
        local_temp_23_reg_3747 <= {{weights_V_TDATA[47:46]}};
        local_temp_24_reg_3752 <= {{weights_V_TDATA[49:48]}};
        local_temp_25_reg_3757 <= {{weights_V_TDATA[51:50]}};
        local_temp_26_reg_3762 <= {{weights_V_TDATA[53:52]}};
        local_temp_27_reg_3767 <= {{weights_V_TDATA[55:54]}};
        local_temp_28_reg_3772 <= {{weights_V_TDATA[57:56]}};
        local_temp_29_reg_3777 <= {{weights_V_TDATA[59:58]}};
        local_temp_2_reg_3642 <= {{weights_V_TDATA[5:4]}};
        local_temp_30_reg_3782 <= {{weights_V_TDATA[61:60]}};
        local_temp_31_reg_3787 <= {{weights_V_TDATA[63:62]}};
        local_temp_32_reg_3792 <= {{weights_V_TDATA[65:64]}};
        local_temp_33_reg_3797 <= {{weights_V_TDATA[67:66]}};
        local_temp_34_reg_3802 <= {{weights_V_TDATA[69:68]}};
        local_temp_35_reg_3807 <= {{weights_V_TDATA[71:70]}};
        local_temp_36_reg_3812 <= {{weights_V_TDATA[73:72]}};
        local_temp_37_reg_3817 <= {{weights_V_TDATA[75:74]}};
        local_temp_38_reg_3822 <= {{weights_V_TDATA[77:76]}};
        local_temp_39_reg_3827 <= {{weights_V_TDATA[79:78]}};
        local_temp_3_reg_3647 <= {{weights_V_TDATA[7:6]}};
        local_temp_40_reg_3832 <= {{weights_V_TDATA[81:80]}};
        local_temp_41_reg_3837 <= {{weights_V_TDATA[83:82]}};
        local_temp_42_reg_3842 <= {{weights_V_TDATA[85:84]}};
        local_temp_43_reg_3847 <= {{weights_V_TDATA[87:86]}};
        local_temp_44_reg_3852 <= {{weights_V_TDATA[89:88]}};
        local_temp_45_reg_3857 <= {{weights_V_TDATA[91:90]}};
        local_temp_46_reg_3862 <= {{weights_V_TDATA[93:92]}};
        local_temp_47_reg_3867 <= {{weights_V_TDATA[95:94]}};
        local_temp_48_reg_3872 <= {{weights_V_TDATA[97:96]}};
        local_temp_49_reg_3877 <= {{weights_V_TDATA[99:98]}};
        local_temp_4_reg_3652 <= {{weights_V_TDATA[9:8]}};
        local_temp_50_reg_3882 <= {{weights_V_TDATA[101:100]}};
        local_temp_51_reg_3887 <= {{weights_V_TDATA[103:102]}};
        local_temp_52_reg_3892 <= {{weights_V_TDATA[105:104]}};
        local_temp_53_reg_3897 <= {{weights_V_TDATA[107:106]}};
        local_temp_54_reg_3902 <= {{weights_V_TDATA[109:108]}};
        local_temp_55_reg_3907 <= {{weights_V_TDATA[111:110]}};
        local_temp_56_reg_3912 <= {{weights_V_TDATA[113:112]}};
        local_temp_57_reg_3917 <= {{weights_V_TDATA[115:114]}};
        local_temp_58_reg_3922 <= {{weights_V_TDATA[117:116]}};
        local_temp_59_reg_3927 <= {{weights_V_TDATA[119:118]}};
        local_temp_5_reg_3657 <= {{weights_V_TDATA[11:10]}};
        local_temp_60_reg_3932 <= {{weights_V_TDATA[121:120]}};
        local_temp_61_reg_3937 <= {{weights_V_TDATA[123:122]}};
        local_temp_62_reg_3942 <= {{weights_V_TDATA[125:124]}};
        local_temp_63_reg_3947 <= {{weights_V_TDATA[127:126]}};
        local_temp_6_reg_3662 <= {{weights_V_TDATA[13:12]}};
        local_temp_7_reg_3667 <= {{weights_V_TDATA[15:14]}};
        local_temp_8_reg_3672 <= {{weights_V_TDATA[17:16]}};
        local_temp_9_reg_3677 <= {{weights_V_TDATA[19:18]}};
        local_temp_reg_3632 <= local_temp_fu_553_p1;
        nf_3_reg_3620 <= ap_sig_allocacmp_nf_3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0))) begin
        arrayidx3_0_0_0_load20_fu_452 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_448;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_3 = nf_1_fu_444;
    end
end

always @ (*) begin
    if (((ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_reg_3625_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (icmp_ln249_reg_3625_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_530_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else if (((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (icmp_ln249_reg_3625_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

assign add_ln169_10_fu_3020_p2 = ($signed(sext_ln216_52_fu_2641_p1) + $signed(sext_ln216_51_fu_2614_p1));

assign add_ln169_11_fu_3030_p2 = ($signed(sext_ln216_54_fu_2695_p1) + $signed(sext_ln216_53_fu_2668_p1));

assign add_ln169_12_fu_3040_p2 = ($signed(sext_ln169_12_fu_3036_p1) + $signed(sext_ln169_11_fu_3026_p1));

assign add_ln169_13_fu_3386_p2 = ($signed(sext_ln169_13_fu_3383_p1) + $signed(sext_ln169_10_fu_3380_p1));

assign add_ln169_14_fu_3396_p2 = ($signed(sext_ln169_14_fu_3392_p1) + $signed(sext_ln169_7_fu_3376_p1));

assign add_ln169_15_fu_3046_p2 = ($signed(sext_ln216_32_fu_2101_p1) + $signed(sext_ln216_31_fu_2074_p1));

assign add_ln169_16_fu_3056_p2 = ($signed(sext_ln216_34_fu_2155_p1) + $signed(sext_ln216_33_fu_2128_p1));

assign add_ln169_17_fu_3066_p2 = ($signed(sext_ln169_16_fu_3062_p1) + $signed(sext_ln169_15_fu_3052_p1));

assign add_ln169_18_fu_3072_p2 = ($signed(sext_ln216_36_fu_2209_p1) + $signed(sext_ln216_35_fu_2182_p1));

assign add_ln169_19_fu_3082_p2 = ($signed(sext_ln216_38_fu_2263_p1) + $signed(sext_ln216_37_fu_2236_p1));

assign add_ln169_1_fu_2952_p2 = ($signed(sext_ln216_60_fu_2857_p1) + $signed(sext_ln216_59_fu_2830_p1));

assign add_ln169_20_fu_3092_p2 = ($signed(sext_ln169_19_fu_3088_p1) + $signed(sext_ln169_18_fu_3078_p1));

assign add_ln169_21_fu_3408_p2 = ($signed(sext_ln169_20_fu_3405_p1) + $signed(sext_ln169_17_fu_3402_p1));

assign add_ln169_22_fu_3098_p2 = ($signed(sext_ln216_40_fu_2317_p1) + $signed(sext_ln216_39_fu_2290_p1));

assign add_ln169_23_fu_3108_p2 = ($signed(sext_ln216_42_fu_2371_p1) + $signed(sext_ln216_41_fu_2344_p1));

assign add_ln169_24_fu_3118_p2 = ($signed(sext_ln169_23_fu_3114_p1) + $signed(sext_ln169_22_fu_3104_p1));

assign add_ln169_25_fu_3124_p2 = ($signed(sext_ln216_44_fu_2425_p1) + $signed(sext_ln216_43_fu_2398_p1));

assign add_ln169_26_fu_3134_p2 = ($signed(sext_ln216_46_fu_2479_p1) + $signed(sext_ln216_45_fu_2452_p1));

assign add_ln169_27_fu_3144_p2 = ($signed(sext_ln169_26_fu_3140_p1) + $signed(sext_ln169_25_fu_3130_p1));

assign add_ln169_28_fu_3424_p2 = ($signed(sext_ln169_27_fu_3421_p1) + $signed(sext_ln169_24_fu_3418_p1));

assign add_ln169_29_fu_3434_p2 = ($signed(sext_ln169_28_fu_3430_p1) + $signed(sext_ln169_21_fu_3414_p1));

assign add_ln169_2_fu_2962_p2 = ($signed(sext_ln169_2_fu_2958_p1) + $signed(sext_ln169_1_fu_2948_p1));

assign add_ln169_30_fu_3502_p2 = (add_ln169_29_reg_4052 + add_ln169_14_reg_4047);

assign add_ln169_31_fu_3150_p2 = ($signed(sext_ln216_1_fu_1264_p1) + $signed(sext_ln216_2_fu_1291_p1));

assign add_ln169_32_fu_3160_p2 = ($signed(sext_ln216_fu_1237_p1) + $signed(sext_ln216_4_fu_1345_p1));

assign add_ln169_33_fu_3170_p2 = ($signed(sext_ln169_30_fu_3166_p1) + $signed(sext_ln169_29_fu_3156_p1));

assign add_ln169_34_fu_3176_p2 = ($signed(sext_ln216_3_fu_1318_p1) + $signed(sext_ln216_6_fu_1399_p1));

assign add_ln169_35_fu_3186_p2 = ($signed(sext_ln216_5_fu_1372_p1) + $signed(sext_ln216_8_fu_1453_p1));

assign add_ln169_36_fu_3196_p2 = ($signed(sext_ln169_33_fu_3192_p1) + $signed(sext_ln169_32_fu_3182_p1));

assign add_ln169_37_fu_3446_p2 = ($signed(sext_ln169_34_fu_3443_p1) + $signed(sext_ln169_31_fu_3440_p1));

assign add_ln169_38_fu_3202_p2 = ($signed(sext_ln216_7_fu_1426_p1) + $signed(sext_ln216_10_fu_1507_p1));

assign add_ln169_39_fu_3212_p2 = ($signed(sext_ln216_9_fu_1480_p1) + $signed(sext_ln216_12_fu_1561_p1));

assign add_ln169_3_fu_2968_p2 = ($signed(sext_ln216_56_fu_2749_p1) + $signed(sext_ln216_55_fu_2722_p1));

assign add_ln169_40_fu_3222_p2 = ($signed(sext_ln169_37_fu_3218_p1) + $signed(sext_ln169_36_fu_3208_p1));

assign add_ln169_41_fu_3228_p2 = ($signed(sext_ln216_11_fu_1534_p1) + $signed(sext_ln216_14_fu_1615_p1));

assign add_ln169_42_fu_3238_p2 = ($signed(sext_ln216_13_fu_1588_p1) + $signed(sext_ln216_16_fu_1669_p1));

assign add_ln169_43_fu_3248_p2 = ($signed(sext_ln169_40_fu_3244_p1) + $signed(sext_ln169_39_fu_3234_p1));

assign add_ln169_44_fu_3458_p2 = ($signed(sext_ln169_41_fu_3455_p1) + $signed(sext_ln169_38_fu_3452_p1));

assign add_ln169_45_fu_3512_p2 = ($signed(sext_ln169_42_fu_3509_p1) + $signed(sext_ln169_35_fu_3506_p1));

assign add_ln169_46_fu_3254_p2 = ($signed(sext_ln216_15_fu_1642_p1) + $signed(sext_ln216_18_fu_1723_p1));

assign add_ln169_47_fu_3264_p2 = ($signed(sext_ln216_17_fu_1696_p1) + $signed(sext_ln216_20_fu_1777_p1));

assign add_ln169_48_fu_3274_p2 = ($signed(sext_ln169_44_fu_3270_p1) + $signed(sext_ln169_43_fu_3260_p1));

assign add_ln169_49_fu_3280_p2 = ($signed(sext_ln216_19_fu_1750_p1) + $signed(sext_ln216_22_fu_1831_p1));

assign add_ln169_4_fu_2978_p2 = ($signed(sext_ln216_58_fu_2803_p1) + $signed(sext_ln216_57_fu_2776_p1));

assign add_ln169_50_fu_3290_p2 = ($signed(sext_ln216_21_fu_1804_p1) + $signed(sext_ln216_24_fu_1885_p1));

assign add_ln169_51_fu_3300_p2 = ($signed(sext_ln169_47_fu_3296_p1) + $signed(sext_ln169_46_fu_3286_p1));

assign add_ln169_52_fu_3470_p2 = ($signed(sext_ln169_48_fu_3467_p1) + $signed(sext_ln169_45_fu_3464_p1));

assign add_ln169_53_fu_3306_p2 = ($signed(sext_ln216_23_fu_1858_p1) + $signed(sext_ln216_26_fu_1939_p1));

assign add_ln169_54_fu_3316_p2 = ($signed(sext_ln216_25_fu_1912_p1) + $signed(sext_ln216_28_fu_1993_p1));

assign add_ln169_55_fu_3326_p2 = ($signed(sext_ln169_51_fu_3322_p1) + $signed(sext_ln169_50_fu_3312_p1));

assign add_ln169_56_fu_3332_p2 = ($signed(sext_ln216_27_fu_1966_p1) + $signed(sext_ln216_30_fu_2047_p1));

assign add_ln169_57_fu_3342_p2 = ($signed(sext_ln216_29_fu_2020_p1) + $signed(sext_ln169_fu_2938_p1));

assign add_ln169_58_fu_3352_p2 = ($signed(sext_ln169_54_fu_3348_p1) + $signed(sext_ln169_53_fu_3338_p1));

assign add_ln169_59_fu_3486_p2 = ($signed(sext_ln169_55_fu_3483_p1) + $signed(sext_ln169_52_fu_3480_p1));

assign add_ln169_5_fu_2988_p2 = ($signed(sext_ln169_5_fu_2984_p1) + $signed(sext_ln169_4_fu_2974_p1));

assign add_ln169_60_fu_3496_p2 = ($signed(sext_ln169_56_fu_3492_p1) + $signed(sext_ln169_49_fu_3476_p1));

assign add_ln169_61_fu_3518_p2 = (add_ln169_60_reg_4067 + add_ln169_45_fu_3512_p2);

assign add_ln169_62_fu_3523_p2 = (add_ln169_61_fu_3518_p2 + add_ln169_30_fu_3502_p2);

assign add_ln169_6_fu_3370_p2 = ($signed(sext_ln169_6_fu_3367_p1) + $signed(sext_ln169_3_fu_3364_p1));

assign add_ln169_7_fu_2994_p2 = ($signed(sext_ln216_48_fu_2533_p1) + $signed(sext_ln216_47_fu_2506_p1));

assign add_ln169_8_fu_3004_p2 = ($signed(sext_ln216_50_fu_2587_p1) + $signed(sext_ln216_49_fu_2560_p1));

assign add_ln169_9_fu_3014_p2 = ($signed(sext_ln169_9_fu_3010_p1) + $signed(sext_ln169_8_fu_3000_p1));

assign add_ln169_fu_2942_p2 = ($signed(sext_ln216_61_fu_2884_p1) + $signed(sext_ln216_62_fu_2911_p1));

assign add_ln218_fu_3583_p2 = (zext_ln218_2_fu_3543_p1 + zext_ln218_1_fu_3579_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_530_p2 == 1'd0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state5_io = ((icmp_ln249_reg_3625_pp0_iter3_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((icmp_ln249_reg_3625_pp0_iter3_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_111 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op27_read_state1 = ((icmp_ln253_fu_542_p2 == 1'd1) & (icmp_ln249_fu_530_p2 == 1'd0));
end

assign i_2_fu_536_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln108_1_fu_3550_p2 = (($signed(add_ln169_62_reg_4087) < $signed(zext_ln108_1_fu_3547_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_2_fu_3568_p2 = (($signed(add_ln169_62_reg_4087) < $signed(zext_ln108_2_fu_3565_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_3532_p2 = (($signed(add_ln169_62_reg_4087) < $signed(zext_ln108_fu_3529_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_530_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_542_p2 = ((ap_sig_allocacmp_nf_3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_1193_p2 = ((nf_fu_1187_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_3358_p1 = nf_3_reg_3620;

assign local_temp_fu_553_p1 = weights_V_TDATA[1:0];

assign mul_ln115_10_fu_1501_p0 = mul_ln115_10_fu_1501_p00;

assign mul_ln115_10_fu_1501_p00 = r_10_fu_1484_p4;

assign mul_ln115_11_fu_1528_p0 = mul_ln115_11_fu_1528_p00;

assign mul_ln115_11_fu_1528_p00 = r_11_fu_1511_p4;

assign mul_ln115_12_fu_1555_p0 = mul_ln115_12_fu_1555_p00;

assign mul_ln115_12_fu_1555_p00 = r_12_fu_1538_p4;

assign mul_ln115_13_fu_1582_p0 = mul_ln115_13_fu_1582_p00;

assign mul_ln115_13_fu_1582_p00 = r_13_fu_1565_p4;

assign mul_ln115_14_fu_1609_p0 = mul_ln115_14_fu_1609_p00;

assign mul_ln115_14_fu_1609_p00 = r_14_fu_1592_p4;

assign mul_ln115_15_fu_1636_p0 = mul_ln115_15_fu_1636_p00;

assign mul_ln115_15_fu_1636_p00 = r_15_fu_1619_p4;

assign mul_ln115_16_fu_1663_p0 = mul_ln115_16_fu_1663_p00;

assign mul_ln115_16_fu_1663_p00 = r_16_fu_1646_p4;

assign mul_ln115_17_fu_1690_p0 = mul_ln115_17_fu_1690_p00;

assign mul_ln115_17_fu_1690_p00 = r_17_fu_1673_p4;

assign mul_ln115_18_fu_1717_p0 = mul_ln115_18_fu_1717_p00;

assign mul_ln115_18_fu_1717_p00 = r_18_fu_1700_p4;

assign mul_ln115_19_fu_1744_p0 = mul_ln115_19_fu_1744_p00;

assign mul_ln115_19_fu_1744_p00 = r_19_fu_1727_p4;

assign mul_ln115_1_fu_1258_p0 = mul_ln115_1_fu_1258_p00;

assign mul_ln115_1_fu_1258_p00 = r_1_fu_1241_p4;

assign mul_ln115_20_fu_1771_p0 = mul_ln115_20_fu_1771_p00;

assign mul_ln115_20_fu_1771_p00 = r_20_fu_1754_p4;

assign mul_ln115_21_fu_1798_p0 = mul_ln115_21_fu_1798_p00;

assign mul_ln115_21_fu_1798_p00 = r_21_fu_1781_p4;

assign mul_ln115_22_fu_1825_p0 = mul_ln115_22_fu_1825_p00;

assign mul_ln115_22_fu_1825_p00 = r_22_fu_1808_p4;

assign mul_ln115_23_fu_1852_p0 = mul_ln115_23_fu_1852_p00;

assign mul_ln115_23_fu_1852_p00 = r_23_fu_1835_p4;

assign mul_ln115_24_fu_1879_p0 = mul_ln115_24_fu_1879_p00;

assign mul_ln115_24_fu_1879_p00 = r_24_fu_1862_p4;

assign mul_ln115_25_fu_1906_p0 = mul_ln115_25_fu_1906_p00;

assign mul_ln115_25_fu_1906_p00 = r_25_fu_1889_p4;

assign mul_ln115_26_fu_1933_p0 = mul_ln115_26_fu_1933_p00;

assign mul_ln115_26_fu_1933_p00 = r_26_fu_1916_p4;

assign mul_ln115_27_fu_1960_p0 = mul_ln115_27_fu_1960_p00;

assign mul_ln115_27_fu_1960_p00 = r_27_fu_1943_p4;

assign mul_ln115_28_fu_1987_p0 = mul_ln115_28_fu_1987_p00;

assign mul_ln115_28_fu_1987_p00 = r_28_fu_1970_p4;

assign mul_ln115_29_fu_2014_p0 = mul_ln115_29_fu_2014_p00;

assign mul_ln115_29_fu_2014_p00 = r_29_fu_1997_p4;

assign mul_ln115_2_fu_1285_p0 = mul_ln115_2_fu_1285_p00;

assign mul_ln115_2_fu_1285_p00 = r_2_fu_1268_p4;

assign mul_ln115_30_fu_2041_p0 = mul_ln115_30_fu_2041_p00;

assign mul_ln115_30_fu_2041_p00 = r_30_fu_2024_p4;

assign mul_ln115_31_fu_2068_p0 = mul_ln115_31_fu_2068_p00;

assign mul_ln115_31_fu_2068_p00 = r_31_fu_2051_p4;

assign mul_ln115_32_fu_2095_p0 = mul_ln115_32_fu_2095_p00;

assign mul_ln115_32_fu_2095_p00 = r_32_fu_2078_p4;

assign mul_ln115_33_fu_2122_p0 = mul_ln115_33_fu_2122_p00;

assign mul_ln115_33_fu_2122_p00 = r_33_fu_2105_p4;

assign mul_ln115_34_fu_2149_p0 = mul_ln115_34_fu_2149_p00;

assign mul_ln115_34_fu_2149_p00 = r_34_fu_2132_p4;

assign mul_ln115_35_fu_2176_p0 = mul_ln115_35_fu_2176_p00;

assign mul_ln115_35_fu_2176_p00 = r_35_fu_2159_p4;

assign mul_ln115_36_fu_2203_p0 = mul_ln115_36_fu_2203_p00;

assign mul_ln115_36_fu_2203_p00 = r_36_fu_2186_p4;

assign mul_ln115_37_fu_2230_p0 = mul_ln115_37_fu_2230_p00;

assign mul_ln115_37_fu_2230_p00 = r_37_fu_2213_p4;

assign mul_ln115_38_fu_2257_p0 = mul_ln115_38_fu_2257_p00;

assign mul_ln115_38_fu_2257_p00 = r_38_fu_2240_p4;

assign mul_ln115_39_fu_2284_p0 = mul_ln115_39_fu_2284_p00;

assign mul_ln115_39_fu_2284_p00 = r_39_fu_2267_p4;

assign mul_ln115_3_fu_1312_p0 = mul_ln115_3_fu_1312_p00;

assign mul_ln115_3_fu_1312_p00 = r_3_fu_1295_p4;

assign mul_ln115_40_fu_2311_p0 = mul_ln115_40_fu_2311_p00;

assign mul_ln115_40_fu_2311_p00 = r_40_fu_2294_p4;

assign mul_ln115_41_fu_2338_p0 = mul_ln115_41_fu_2338_p00;

assign mul_ln115_41_fu_2338_p00 = r_41_fu_2321_p4;

assign mul_ln115_42_fu_2365_p0 = mul_ln115_42_fu_2365_p00;

assign mul_ln115_42_fu_2365_p00 = r_42_fu_2348_p4;

assign mul_ln115_43_fu_2392_p0 = mul_ln115_43_fu_2392_p00;

assign mul_ln115_43_fu_2392_p00 = r_43_fu_2375_p4;

assign mul_ln115_44_fu_2419_p0 = mul_ln115_44_fu_2419_p00;

assign mul_ln115_44_fu_2419_p00 = r_44_fu_2402_p4;

assign mul_ln115_45_fu_2446_p0 = mul_ln115_45_fu_2446_p00;

assign mul_ln115_45_fu_2446_p00 = r_45_fu_2429_p4;

assign mul_ln115_46_fu_2473_p0 = mul_ln115_46_fu_2473_p00;

assign mul_ln115_46_fu_2473_p00 = r_46_fu_2456_p4;

assign mul_ln115_47_fu_2500_p0 = mul_ln115_47_fu_2500_p00;

assign mul_ln115_47_fu_2500_p00 = r_47_fu_2483_p4;

assign mul_ln115_48_fu_2527_p0 = mul_ln115_48_fu_2527_p00;

assign mul_ln115_48_fu_2527_p00 = r_48_fu_2510_p4;

assign mul_ln115_49_fu_2554_p0 = mul_ln115_49_fu_2554_p00;

assign mul_ln115_49_fu_2554_p00 = r_49_fu_2537_p4;

assign mul_ln115_4_fu_1339_p0 = mul_ln115_4_fu_1339_p00;

assign mul_ln115_4_fu_1339_p00 = r_4_fu_1322_p4;

assign mul_ln115_50_fu_2581_p0 = mul_ln115_50_fu_2581_p00;

assign mul_ln115_50_fu_2581_p00 = r_50_fu_2564_p4;

assign mul_ln115_51_fu_2608_p0 = mul_ln115_51_fu_2608_p00;

assign mul_ln115_51_fu_2608_p00 = r_51_fu_2591_p4;

assign mul_ln115_52_fu_2635_p0 = mul_ln115_52_fu_2635_p00;

assign mul_ln115_52_fu_2635_p00 = r_52_fu_2618_p4;

assign mul_ln115_53_fu_2662_p0 = mul_ln115_53_fu_2662_p00;

assign mul_ln115_53_fu_2662_p00 = r_53_fu_2645_p4;

assign mul_ln115_54_fu_2689_p0 = mul_ln115_54_fu_2689_p00;

assign mul_ln115_54_fu_2689_p00 = r_54_fu_2672_p4;

assign mul_ln115_55_fu_2716_p0 = mul_ln115_55_fu_2716_p00;

assign mul_ln115_55_fu_2716_p00 = r_55_fu_2699_p4;

assign mul_ln115_56_fu_2743_p0 = mul_ln115_56_fu_2743_p00;

assign mul_ln115_56_fu_2743_p00 = r_56_fu_2726_p4;

assign mul_ln115_57_fu_2770_p0 = mul_ln115_57_fu_2770_p00;

assign mul_ln115_57_fu_2770_p00 = r_57_fu_2753_p4;

assign mul_ln115_58_fu_2797_p0 = mul_ln115_58_fu_2797_p00;

assign mul_ln115_58_fu_2797_p00 = r_58_fu_2780_p4;

assign mul_ln115_59_fu_2824_p0 = mul_ln115_59_fu_2824_p00;

assign mul_ln115_59_fu_2824_p00 = r_59_fu_2807_p4;

assign mul_ln115_5_fu_1366_p0 = mul_ln115_5_fu_1366_p00;

assign mul_ln115_5_fu_1366_p00 = r_5_fu_1349_p4;

assign mul_ln115_60_fu_2851_p0 = mul_ln115_60_fu_2851_p00;

assign mul_ln115_60_fu_2851_p00 = r_60_fu_2834_p4;

assign mul_ln115_61_fu_2878_p0 = mul_ln115_61_fu_2878_p00;

assign mul_ln115_61_fu_2878_p00 = r_61_fu_2861_p4;

assign mul_ln115_62_fu_2905_p0 = mul_ln115_62_fu_2905_p00;

assign mul_ln115_62_fu_2905_p00 = r_62_fu_2888_p4;

assign mul_ln115_63_fu_2932_p0 = mul_ln115_63_fu_2932_p00;

assign mul_ln115_63_fu_2932_p00 = r_63_fu_2915_p4;

assign mul_ln115_6_fu_1393_p0 = mul_ln115_6_fu_1393_p00;

assign mul_ln115_6_fu_1393_p00 = r_6_fu_1376_p4;

assign mul_ln115_7_fu_1420_p0 = mul_ln115_7_fu_1420_p00;

assign mul_ln115_7_fu_1420_p00 = r_7_fu_1403_p4;

assign mul_ln115_8_fu_1447_p0 = mul_ln115_8_fu_1447_p00;

assign mul_ln115_8_fu_1447_p00 = r_8_fu_1430_p4;

assign mul_ln115_9_fu_1474_p0 = mul_ln115_9_fu_1474_p00;

assign mul_ln115_9_fu_1474_p00 = r_9_fu_1457_p4;

assign mul_ln115_fu_1231_p0 = mul_ln115_fu_1231_p00;

assign mul_ln115_fu_1231_p00 = r_fu_1220_p1;

assign nf_4_fu_1199_p3 = ((icmp_ln302_fu_1193_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_1187_p2);

assign nf_fu_1187_p2 = (ap_sig_allocacmp_nf_3 + 32'd1);

assign out_V_TDATA = result_2_fu_3589_p2;

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_3358_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_3358_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_3358_p1;

assign r_10_fu_1484_p4 = {{arrayidx3_0_0_0_load20_fu_452[21:20]}};

assign r_11_fu_1511_p4 = {{arrayidx3_0_0_0_load20_fu_452[23:22]}};

assign r_12_fu_1538_p4 = {{arrayidx3_0_0_0_load20_fu_452[25:24]}};

assign r_13_fu_1565_p4 = {{arrayidx3_0_0_0_load20_fu_452[27:26]}};

assign r_14_fu_1592_p4 = {{arrayidx3_0_0_0_load20_fu_452[29:28]}};

assign r_15_fu_1619_p4 = {{arrayidx3_0_0_0_load20_fu_452[31:30]}};

assign r_16_fu_1646_p4 = {{arrayidx3_0_0_0_load20_fu_452[33:32]}};

assign r_17_fu_1673_p4 = {{arrayidx3_0_0_0_load20_fu_452[35:34]}};

assign r_18_fu_1700_p4 = {{arrayidx3_0_0_0_load20_fu_452[37:36]}};

assign r_19_fu_1727_p4 = {{arrayidx3_0_0_0_load20_fu_452[39:38]}};

assign r_1_fu_1241_p4 = {{arrayidx3_0_0_0_load20_fu_452[3:2]}};

assign r_20_fu_1754_p4 = {{arrayidx3_0_0_0_load20_fu_452[41:40]}};

assign r_21_fu_1781_p4 = {{arrayidx3_0_0_0_load20_fu_452[43:42]}};

assign r_22_fu_1808_p4 = {{arrayidx3_0_0_0_load20_fu_452[45:44]}};

assign r_23_fu_1835_p4 = {{arrayidx3_0_0_0_load20_fu_452[47:46]}};

assign r_24_fu_1862_p4 = {{arrayidx3_0_0_0_load20_fu_452[49:48]}};

assign r_25_fu_1889_p4 = {{arrayidx3_0_0_0_load20_fu_452[51:50]}};

assign r_26_fu_1916_p4 = {{arrayidx3_0_0_0_load20_fu_452[53:52]}};

assign r_27_fu_1943_p4 = {{arrayidx3_0_0_0_load20_fu_452[55:54]}};

assign r_28_fu_1970_p4 = {{arrayidx3_0_0_0_load20_fu_452[57:56]}};

assign r_29_fu_1997_p4 = {{arrayidx3_0_0_0_load20_fu_452[59:58]}};

assign r_2_fu_1268_p4 = {{arrayidx3_0_0_0_load20_fu_452[5:4]}};

assign r_30_fu_2024_p4 = {{arrayidx3_0_0_0_load20_fu_452[61:60]}};

assign r_31_fu_2051_p4 = {{arrayidx3_0_0_0_load20_fu_452[63:62]}};

assign r_32_fu_2078_p4 = {{arrayidx3_0_0_0_load20_fu_452[65:64]}};

assign r_33_fu_2105_p4 = {{arrayidx3_0_0_0_load20_fu_452[67:66]}};

assign r_34_fu_2132_p4 = {{arrayidx3_0_0_0_load20_fu_452[69:68]}};

assign r_35_fu_2159_p4 = {{arrayidx3_0_0_0_load20_fu_452[71:70]}};

assign r_36_fu_2186_p4 = {{arrayidx3_0_0_0_load20_fu_452[73:72]}};

assign r_37_fu_2213_p4 = {{arrayidx3_0_0_0_load20_fu_452[75:74]}};

assign r_38_fu_2240_p4 = {{arrayidx3_0_0_0_load20_fu_452[77:76]}};

assign r_39_fu_2267_p4 = {{arrayidx3_0_0_0_load20_fu_452[79:78]}};

assign r_3_fu_1295_p4 = {{arrayidx3_0_0_0_load20_fu_452[7:6]}};

assign r_40_fu_2294_p4 = {{arrayidx3_0_0_0_load20_fu_452[81:80]}};

assign r_41_fu_2321_p4 = {{arrayidx3_0_0_0_load20_fu_452[83:82]}};

assign r_42_fu_2348_p4 = {{arrayidx3_0_0_0_load20_fu_452[85:84]}};

assign r_43_fu_2375_p4 = {{arrayidx3_0_0_0_load20_fu_452[87:86]}};

assign r_44_fu_2402_p4 = {{arrayidx3_0_0_0_load20_fu_452[89:88]}};

assign r_45_fu_2429_p4 = {{arrayidx3_0_0_0_load20_fu_452[91:90]}};

assign r_46_fu_2456_p4 = {{arrayidx3_0_0_0_load20_fu_452[93:92]}};

assign r_47_fu_2483_p4 = {{arrayidx3_0_0_0_load20_fu_452[95:94]}};

assign r_48_fu_2510_p4 = {{arrayidx3_0_0_0_load20_fu_452[97:96]}};

assign r_49_fu_2537_p4 = {{arrayidx3_0_0_0_load20_fu_452[99:98]}};

assign r_4_fu_1322_p4 = {{arrayidx3_0_0_0_load20_fu_452[9:8]}};

assign r_50_fu_2564_p4 = {{arrayidx3_0_0_0_load20_fu_452[101:100]}};

assign r_51_fu_2591_p4 = {{arrayidx3_0_0_0_load20_fu_452[103:102]}};

assign r_52_fu_2618_p4 = {{arrayidx3_0_0_0_load20_fu_452[105:104]}};

assign r_53_fu_2645_p4 = {{arrayidx3_0_0_0_load20_fu_452[107:106]}};

assign r_54_fu_2672_p4 = {{arrayidx3_0_0_0_load20_fu_452[109:108]}};

assign r_55_fu_2699_p4 = {{arrayidx3_0_0_0_load20_fu_452[111:110]}};

assign r_56_fu_2726_p4 = {{arrayidx3_0_0_0_load20_fu_452[113:112]}};

assign r_57_fu_2753_p4 = {{arrayidx3_0_0_0_load20_fu_452[115:114]}};

assign r_58_fu_2780_p4 = {{arrayidx3_0_0_0_load20_fu_452[117:116]}};

assign r_59_fu_2807_p4 = {{arrayidx3_0_0_0_load20_fu_452[119:118]}};

assign r_5_fu_1349_p4 = {{arrayidx3_0_0_0_load20_fu_452[11:10]}};

assign r_60_fu_2834_p4 = {{arrayidx3_0_0_0_load20_fu_452[121:120]}};

assign r_61_fu_2861_p4 = {{arrayidx3_0_0_0_load20_fu_452[123:122]}};

assign r_62_fu_2888_p4 = {{arrayidx3_0_0_0_load20_fu_452[125:124]}};

assign r_63_fu_2915_p4 = {{arrayidx3_0_0_0_load20_fu_452[127:126]}};

assign r_6_fu_1376_p4 = {{arrayidx3_0_0_0_load20_fu_452[13:12]}};

assign r_7_fu_1403_p4 = {{arrayidx3_0_0_0_load20_fu_452[15:14]}};

assign r_8_fu_1430_p4 = {{arrayidx3_0_0_0_load20_fu_452[17:16]}};

assign r_9_fu_1457_p4 = {{arrayidx3_0_0_0_load20_fu_452[19:18]}};

assign r_fu_1220_p1 = arrayidx3_0_0_0_load20_fu_452[1:0];

assign result_2_fu_3589_p2 = (add_ln218_fu_3583_p2 + zext_ln218_fu_3561_p1);

assign result_fu_3537_p2 = (icmp_ln108_fu_3532_p2 ^ 1'd1);

assign sext_ln169_10_fu_3380_p1 = $signed(add_ln169_9_reg_3962);

assign sext_ln169_11_fu_3026_p1 = $signed(add_ln169_10_fu_3020_p2);

assign sext_ln169_12_fu_3036_p1 = $signed(add_ln169_11_fu_3030_p2);

assign sext_ln169_13_fu_3383_p1 = $signed(add_ln169_12_reg_3967);

assign sext_ln169_14_fu_3392_p1 = $signed(add_ln169_13_fu_3386_p2);

assign sext_ln169_15_fu_3052_p1 = $signed(add_ln169_15_fu_3046_p2);

assign sext_ln169_16_fu_3062_p1 = $signed(add_ln169_16_fu_3056_p2);

assign sext_ln169_17_fu_3402_p1 = $signed(add_ln169_17_reg_3972);

assign sext_ln169_18_fu_3078_p1 = $signed(add_ln169_18_fu_3072_p2);

assign sext_ln169_19_fu_3088_p1 = $signed(add_ln169_19_fu_3082_p2);

assign sext_ln169_1_fu_2948_p1 = $signed(add_ln169_fu_2942_p2);

assign sext_ln169_20_fu_3405_p1 = $signed(add_ln169_20_reg_3977);

assign sext_ln169_21_fu_3414_p1 = $signed(add_ln169_21_fu_3408_p2);

assign sext_ln169_22_fu_3104_p1 = $signed(add_ln169_22_fu_3098_p2);

assign sext_ln169_23_fu_3114_p1 = $signed(add_ln169_23_fu_3108_p2);

assign sext_ln169_24_fu_3418_p1 = $signed(add_ln169_24_reg_3982);

assign sext_ln169_25_fu_3130_p1 = $signed(add_ln169_25_fu_3124_p2);

assign sext_ln169_26_fu_3140_p1 = $signed(add_ln169_26_fu_3134_p2);

assign sext_ln169_27_fu_3421_p1 = $signed(add_ln169_27_reg_3987);

assign sext_ln169_28_fu_3430_p1 = $signed(add_ln169_28_fu_3424_p2);

assign sext_ln169_29_fu_3156_p1 = $signed(add_ln169_31_fu_3150_p2);

assign sext_ln169_2_fu_2958_p1 = $signed(add_ln169_1_fu_2952_p2);

assign sext_ln169_30_fu_3166_p1 = $signed(add_ln169_32_fu_3160_p2);

assign sext_ln169_31_fu_3440_p1 = $signed(add_ln169_33_reg_3992);

assign sext_ln169_32_fu_3182_p1 = $signed(add_ln169_34_fu_3176_p2);

assign sext_ln169_33_fu_3192_p1 = $signed(add_ln169_35_fu_3186_p2);

assign sext_ln169_34_fu_3443_p1 = $signed(add_ln169_36_reg_3997);

assign sext_ln169_35_fu_3506_p1 = $signed(add_ln169_37_reg_4057);

assign sext_ln169_36_fu_3208_p1 = $signed(add_ln169_38_fu_3202_p2);

assign sext_ln169_37_fu_3218_p1 = $signed(add_ln169_39_fu_3212_p2);

assign sext_ln169_38_fu_3452_p1 = $signed(add_ln169_40_reg_4002);

assign sext_ln169_39_fu_3234_p1 = $signed(add_ln169_41_fu_3228_p2);

assign sext_ln169_3_fu_3364_p1 = $signed(add_ln169_2_reg_3952);

assign sext_ln169_40_fu_3244_p1 = $signed(add_ln169_42_fu_3238_p2);

assign sext_ln169_41_fu_3455_p1 = $signed(add_ln169_43_reg_4007);

assign sext_ln169_42_fu_3509_p1 = $signed(add_ln169_44_reg_4062);

assign sext_ln169_43_fu_3260_p1 = $signed(add_ln169_46_fu_3254_p2);

assign sext_ln169_44_fu_3270_p1 = $signed(add_ln169_47_fu_3264_p2);

assign sext_ln169_45_fu_3464_p1 = $signed(add_ln169_48_reg_4012);

assign sext_ln169_46_fu_3286_p1 = $signed(add_ln169_49_fu_3280_p2);

assign sext_ln169_47_fu_3296_p1 = $signed(add_ln169_50_fu_3290_p2);

assign sext_ln169_48_fu_3467_p1 = $signed(add_ln169_51_reg_4017);

assign sext_ln169_49_fu_3476_p1 = $signed(add_ln169_52_fu_3470_p2);

assign sext_ln169_4_fu_2974_p1 = $signed(add_ln169_3_fu_2968_p2);

assign sext_ln169_50_fu_3312_p1 = $signed(add_ln169_53_fu_3306_p2);

assign sext_ln169_51_fu_3322_p1 = $signed(add_ln169_54_fu_3316_p2);

assign sext_ln169_52_fu_3480_p1 = $signed(add_ln169_55_reg_4022);

assign sext_ln169_53_fu_3338_p1 = $signed(add_ln169_56_fu_3332_p2);

assign sext_ln169_54_fu_3348_p1 = $signed(add_ln169_57_fu_3342_p2);

assign sext_ln169_55_fu_3483_p1 = $signed(add_ln169_58_reg_4027);

assign sext_ln169_56_fu_3492_p1 = $signed(add_ln169_59_fu_3486_p2);

assign sext_ln169_5_fu_2984_p1 = $signed(add_ln169_4_fu_2978_p2);

assign sext_ln169_6_fu_3367_p1 = $signed(add_ln169_5_reg_3957);

assign sext_ln169_7_fu_3376_p1 = $signed(add_ln169_6_fu_3370_p2);

assign sext_ln169_8_fu_3000_p1 = $signed(add_ln169_7_fu_2994_p2);

assign sext_ln169_9_fu_3010_p1 = $signed(add_ln169_8_fu_3004_p2);

assign sext_ln169_fu_2938_p1 = mul_ln115_63_fu_2932_p2;

assign sext_ln216_10_fu_1507_p1 = mul_ln115_10_fu_1501_p2;

assign sext_ln216_11_fu_1534_p1 = mul_ln115_11_fu_1528_p2;

assign sext_ln216_12_fu_1561_p1 = mul_ln115_12_fu_1555_p2;

assign sext_ln216_13_fu_1588_p1 = mul_ln115_13_fu_1582_p2;

assign sext_ln216_14_fu_1615_p1 = mul_ln115_14_fu_1609_p2;

assign sext_ln216_15_fu_1642_p1 = mul_ln115_15_fu_1636_p2;

assign sext_ln216_16_fu_1669_p1 = mul_ln115_16_fu_1663_p2;

assign sext_ln216_17_fu_1696_p1 = mul_ln115_17_fu_1690_p2;

assign sext_ln216_18_fu_1723_p1 = mul_ln115_18_fu_1717_p2;

assign sext_ln216_19_fu_1750_p1 = mul_ln115_19_fu_1744_p2;

assign sext_ln216_1_fu_1264_p1 = mul_ln115_1_fu_1258_p2;

assign sext_ln216_20_fu_1777_p1 = mul_ln115_20_fu_1771_p2;

assign sext_ln216_21_fu_1804_p1 = mul_ln115_21_fu_1798_p2;

assign sext_ln216_22_fu_1831_p1 = mul_ln115_22_fu_1825_p2;

assign sext_ln216_23_fu_1858_p1 = mul_ln115_23_fu_1852_p2;

assign sext_ln216_24_fu_1885_p1 = mul_ln115_24_fu_1879_p2;

assign sext_ln216_25_fu_1912_p1 = mul_ln115_25_fu_1906_p2;

assign sext_ln216_26_fu_1939_p1 = mul_ln115_26_fu_1933_p2;

assign sext_ln216_27_fu_1966_p1 = mul_ln115_27_fu_1960_p2;

assign sext_ln216_28_fu_1993_p1 = mul_ln115_28_fu_1987_p2;

assign sext_ln216_29_fu_2020_p1 = mul_ln115_29_fu_2014_p2;

assign sext_ln216_2_fu_1291_p1 = mul_ln115_2_fu_1285_p2;

assign sext_ln216_30_fu_2047_p1 = mul_ln115_30_fu_2041_p2;

assign sext_ln216_31_fu_2074_p1 = mul_ln115_31_fu_2068_p2;

assign sext_ln216_32_fu_2101_p1 = mul_ln115_32_fu_2095_p2;

assign sext_ln216_33_fu_2128_p1 = mul_ln115_33_fu_2122_p2;

assign sext_ln216_34_fu_2155_p1 = mul_ln115_34_fu_2149_p2;

assign sext_ln216_35_fu_2182_p1 = mul_ln115_35_fu_2176_p2;

assign sext_ln216_36_fu_2209_p1 = mul_ln115_36_fu_2203_p2;

assign sext_ln216_37_fu_2236_p1 = mul_ln115_37_fu_2230_p2;

assign sext_ln216_38_fu_2263_p1 = mul_ln115_38_fu_2257_p2;

assign sext_ln216_39_fu_2290_p1 = mul_ln115_39_fu_2284_p2;

assign sext_ln216_3_fu_1318_p1 = mul_ln115_3_fu_1312_p2;

assign sext_ln216_40_fu_2317_p1 = mul_ln115_40_fu_2311_p2;

assign sext_ln216_41_fu_2344_p1 = mul_ln115_41_fu_2338_p2;

assign sext_ln216_42_fu_2371_p1 = mul_ln115_42_fu_2365_p2;

assign sext_ln216_43_fu_2398_p1 = mul_ln115_43_fu_2392_p2;

assign sext_ln216_44_fu_2425_p1 = mul_ln115_44_fu_2419_p2;

assign sext_ln216_45_fu_2452_p1 = mul_ln115_45_fu_2446_p2;

assign sext_ln216_46_fu_2479_p1 = mul_ln115_46_fu_2473_p2;

assign sext_ln216_47_fu_2506_p1 = mul_ln115_47_fu_2500_p2;

assign sext_ln216_48_fu_2533_p1 = mul_ln115_48_fu_2527_p2;

assign sext_ln216_49_fu_2560_p1 = mul_ln115_49_fu_2554_p2;

assign sext_ln216_4_fu_1345_p1 = mul_ln115_4_fu_1339_p2;

assign sext_ln216_50_fu_2587_p1 = mul_ln115_50_fu_2581_p2;

assign sext_ln216_51_fu_2614_p1 = mul_ln115_51_fu_2608_p2;

assign sext_ln216_52_fu_2641_p1 = mul_ln115_52_fu_2635_p2;

assign sext_ln216_53_fu_2668_p1 = mul_ln115_53_fu_2662_p2;

assign sext_ln216_54_fu_2695_p1 = mul_ln115_54_fu_2689_p2;

assign sext_ln216_55_fu_2722_p1 = mul_ln115_55_fu_2716_p2;

assign sext_ln216_56_fu_2749_p1 = mul_ln115_56_fu_2743_p2;

assign sext_ln216_57_fu_2776_p1 = mul_ln115_57_fu_2770_p2;

assign sext_ln216_58_fu_2803_p1 = mul_ln115_58_fu_2797_p2;

assign sext_ln216_59_fu_2830_p1 = mul_ln115_59_fu_2824_p2;

assign sext_ln216_5_fu_1372_p1 = mul_ln115_5_fu_1366_p2;

assign sext_ln216_60_fu_2857_p1 = mul_ln115_60_fu_2851_p2;

assign sext_ln216_61_fu_2884_p1 = mul_ln115_61_fu_2878_p2;

assign sext_ln216_62_fu_2911_p1 = mul_ln115_62_fu_2905_p2;

assign sext_ln216_6_fu_1399_p1 = mul_ln115_6_fu_1393_p2;

assign sext_ln216_7_fu_1426_p1 = mul_ln115_7_fu_1420_p2;

assign sext_ln216_8_fu_1453_p1 = mul_ln115_8_fu_1447_p2;

assign sext_ln216_9_fu_1480_p1 = mul_ln115_9_fu_1474_p2;

assign sext_ln216_fu_1237_p1 = mul_ln115_fu_1231_p2;

assign xor_ln108_1_fu_3573_p2 = (icmp_ln108_2_fu_3568_p2 ^ 1'd1);

assign xor_ln108_fu_3555_p2 = (icmp_ln108_1_fu_3550_p2 ^ 1'd1);

assign zext_ln108_1_fu_3547_p1 = p_ZL7threshs_1_load_reg_4077_pp0_iter3_reg;

assign zext_ln108_2_fu_3565_p1 = p_ZL7threshs_2_load_reg_4082_pp0_iter3_reg;

assign zext_ln108_fu_3529_p1 = p_ZL7threshs_0_load_reg_4072_pp0_iter3_reg;

assign zext_ln218_1_fu_3579_p1 = xor_ln108_1_fu_3573_p2;

assign zext_ln218_2_fu_3543_p1 = result_fu_3537_p2;

assign zext_ln218_fu_3561_p1 = xor_ln108_fu_3555_p2;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch
