// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [7:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] icmp_ln249_fu_691_p2;
wire   [0:0] icmp_ln253_fu_707_p2;
reg    ap_predicate_op94_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln249_reg_2089;
reg   [0:0] icmp_ln249_reg_2089_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_2180;
reg   [0:0] icmp_ln290_reg_2180_pp0_iter2_reg;
reg    ap_predicate_op343_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [5:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [6:0] p_ZL7threshs_1_q0;
wire   [5:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [6:0] p_ZL7threshs_2_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_2084;
wire   [0:0] icmp_ln249_reg_2089_pp0_iter0_reg;
reg   [0:0] icmp_ln249_reg_2089_pp0_iter1_reg;
wire   [5:0] trunc_ln242_fu_703_p1;
reg   [5:0] trunc_ln242_reg_2093;
reg   [0:0] icmp_ln253_reg_2098;
wire   [0:0] icmp_ln253_reg_2098_pp0_iter0_reg;
wire   [1:0] inputBuf_64_fu_713_p1;
wire   [1:0] W_packed_fu_1037_p1;
reg   [1:0] W_packed_reg_2170;
reg  signed [1:0] W_packed_reg_2170_pp0_iter1_reg;
wire   [0:0] icmp_ln272_fu_1041_p2;
reg   [0:0] icmp_ln272_reg_2175;
reg   [0:0] icmp_ln272_reg_2175_pp0_iter1_reg;
wire   [0:0] icmp_ln290_fu_1053_p2;
reg   [0:0] icmp_ln290_reg_2180_pp0_iter1_reg;
wire   [1:0] tmp_fu_1291_p131;
wire   [0:0] icmp_ln108_fu_1597_p2;
reg   [0:0] icmp_ln108_reg_2204;
wire   [0:0] icmp_ln108_1_fu_1607_p2;
reg   [0:0] icmp_ln108_1_reg_2209;
wire   [0:0] icmp_ln108_2_fu_1617_p2;
reg   [0:0] icmp_ln108_2_reg_2214;
wire   [1:0] ap_phi_reg_pp0_iter0_inElem_reg_532;
reg   [1:0] ap_phi_reg_pp0_iter1_inElem_reg_532;
reg   [1:0] ap_phi_reg_pp0_iter2_inElem_reg_532;
wire   [63:0] idxprom2_i_fu_1554_p1;
reg   [31:0] sf_fu_202;
wire   [31:0] sf_2_fu_1047_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [12:0] i_fu_206;
wire   [12:0] i_2_fu_697_p2;
reg   [12:0] ap_sig_allocacmp_i_1;
reg   [7:0] p_0_0_07625_fu_210;
wire   [7:0] add_ln169_fu_1587_p2;
reg   [1:0] inputBuf_fu_214;
reg   [1:0] inputBuf_1_fu_218;
reg   [1:0] inputBuf_2_fu_222;
reg   [1:0] inputBuf_3_fu_226;
reg   [1:0] inputBuf_4_fu_230;
reg   [1:0] inputBuf_5_fu_234;
reg   [1:0] inputBuf_6_fu_238;
reg   [1:0] inputBuf_7_fu_242;
reg   [1:0] inputBuf_8_fu_246;
reg   [1:0] inputBuf_9_fu_250;
reg   [1:0] inputBuf_10_fu_254;
reg   [1:0] inputBuf_11_fu_258;
reg   [1:0] inputBuf_12_fu_262;
reg   [1:0] inputBuf_13_fu_266;
reg   [1:0] inputBuf_14_fu_270;
reg   [1:0] inputBuf_15_fu_274;
reg   [1:0] inputBuf_16_fu_278;
reg   [1:0] inputBuf_17_fu_282;
reg   [1:0] inputBuf_18_fu_286;
reg   [1:0] inputBuf_19_fu_290;
reg   [1:0] inputBuf_20_fu_294;
reg   [1:0] inputBuf_21_fu_298;
reg   [1:0] inputBuf_22_fu_302;
reg   [1:0] inputBuf_23_fu_306;
reg   [1:0] inputBuf_24_fu_310;
reg   [1:0] inputBuf_25_fu_314;
reg   [1:0] inputBuf_26_fu_318;
reg   [1:0] inputBuf_27_fu_322;
reg   [1:0] inputBuf_28_fu_326;
reg   [1:0] inputBuf_29_fu_330;
reg   [1:0] inputBuf_30_fu_334;
reg   [1:0] inputBuf_31_fu_338;
reg   [1:0] inputBuf_32_fu_342;
reg   [1:0] inputBuf_33_fu_346;
reg   [1:0] inputBuf_34_fu_350;
reg   [1:0] inputBuf_35_fu_354;
reg   [1:0] inputBuf_36_fu_358;
reg   [1:0] inputBuf_37_fu_362;
reg   [1:0] inputBuf_38_fu_366;
reg   [1:0] inputBuf_39_fu_370;
reg   [1:0] inputBuf_40_fu_374;
reg   [1:0] inputBuf_41_fu_378;
reg   [1:0] inputBuf_42_fu_382;
reg   [1:0] inputBuf_43_fu_386;
reg   [1:0] inputBuf_44_fu_390;
reg   [1:0] inputBuf_45_fu_394;
reg   [1:0] inputBuf_46_fu_398;
reg   [1:0] inputBuf_47_fu_402;
reg   [1:0] inputBuf_48_fu_406;
reg   [1:0] inputBuf_49_fu_410;
reg   [1:0] inputBuf_50_fu_414;
reg   [1:0] inputBuf_51_fu_418;
reg   [1:0] inputBuf_52_fu_422;
reg   [1:0] inputBuf_53_fu_426;
reg   [1:0] inputBuf_54_fu_430;
reg   [1:0] inputBuf_55_fu_434;
reg   [1:0] inputBuf_56_fu_438;
reg   [1:0] inputBuf_57_fu_442;
reg   [1:0] inputBuf_58_fu_446;
reg   [1:0] inputBuf_59_fu_450;
reg   [1:0] inputBuf_60_fu_454;
reg   [1:0] inputBuf_61_fu_458;
reg   [1:0] inputBuf_62_fu_462;
reg   [1:0] inputBuf_63_fu_466;
reg   [31:0] nf_1_fu_470;
wire   [31:0] nf_3_fu_1076_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [31:0] nf_fu_1064_p2;
wire   [0:0] icmp_ln302_fu_1070_p2;
wire   [1:0] tmp_fu_1291_p129;
wire   [1:0] mul_ln115_fu_1577_p0;
wire  signed [3:0] mul_ln115_fu_1577_p2;
wire   [7:0] select_ln272_fu_1563_p3;
wire  signed [7:0] sext_ln169_fu_1583_p1;
wire   [7:0] zext_ln108_fu_1593_p1;
wire   [7:0] zext_ln108_1_fu_1603_p1;
wire   [7:0] zext_ln108_2_fu_1613_p1;
wire   [0:0] result_fu_1628_p2;
wire   [0:0] xor_ln108_fu_1637_p2;
wire   [0:0] xor_ln108_1_fu_1646_p2;
wire   [1:0] zext_ln218_2_fu_1633_p1;
wire   [1:0] zext_ln218_1_fu_1651_p1;
wire   [1:0] add_ln218_fu_1655_p2;
wire   [1:0] zext_ln218_fu_1642_p1;
wire   [1:0] result_2_fu_1661_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_start_int;
wire   [3:0] mul_ln115_fu_1577_p00;
reg    ap_condition_153;
reg    ap_condition_105;
wire   [5:0] tmp_fu_1291_p1;
wire   [5:0] tmp_fu_1291_p3;
wire   [5:0] tmp_fu_1291_p5;
wire   [5:0] tmp_fu_1291_p7;
wire   [5:0] tmp_fu_1291_p9;
wire   [5:0] tmp_fu_1291_p11;
wire   [5:0] tmp_fu_1291_p13;
wire   [5:0] tmp_fu_1291_p15;
wire   [5:0] tmp_fu_1291_p17;
wire   [5:0] tmp_fu_1291_p19;
wire   [5:0] tmp_fu_1291_p21;
wire   [5:0] tmp_fu_1291_p23;
wire   [5:0] tmp_fu_1291_p25;
wire   [5:0] tmp_fu_1291_p27;
wire   [5:0] tmp_fu_1291_p29;
wire   [5:0] tmp_fu_1291_p31;
wire   [5:0] tmp_fu_1291_p33;
wire   [5:0] tmp_fu_1291_p35;
wire   [5:0] tmp_fu_1291_p37;
wire   [5:0] tmp_fu_1291_p39;
wire   [5:0] tmp_fu_1291_p41;
wire   [5:0] tmp_fu_1291_p43;
wire   [5:0] tmp_fu_1291_p45;
wire   [5:0] tmp_fu_1291_p47;
wire   [5:0] tmp_fu_1291_p49;
wire   [5:0] tmp_fu_1291_p51;
wire   [5:0] tmp_fu_1291_p53;
wire   [5:0] tmp_fu_1291_p55;
wire   [5:0] tmp_fu_1291_p57;
wire   [5:0] tmp_fu_1291_p59;
wire   [5:0] tmp_fu_1291_p61;
wire   [5:0] tmp_fu_1291_p63;
wire  signed [5:0] tmp_fu_1291_p65;
wire  signed [5:0] tmp_fu_1291_p67;
wire  signed [5:0] tmp_fu_1291_p69;
wire  signed [5:0] tmp_fu_1291_p71;
wire  signed [5:0] tmp_fu_1291_p73;
wire  signed [5:0] tmp_fu_1291_p75;
wire  signed [5:0] tmp_fu_1291_p77;
wire  signed [5:0] tmp_fu_1291_p79;
wire  signed [5:0] tmp_fu_1291_p81;
wire  signed [5:0] tmp_fu_1291_p83;
wire  signed [5:0] tmp_fu_1291_p85;
wire  signed [5:0] tmp_fu_1291_p87;
wire  signed [5:0] tmp_fu_1291_p89;
wire  signed [5:0] tmp_fu_1291_p91;
wire  signed [5:0] tmp_fu_1291_p93;
wire  signed [5:0] tmp_fu_1291_p95;
wire  signed [5:0] tmp_fu_1291_p97;
wire  signed [5:0] tmp_fu_1291_p99;
wire  signed [5:0] tmp_fu_1291_p101;
wire  signed [5:0] tmp_fu_1291_p103;
wire  signed [5:0] tmp_fu_1291_p105;
wire  signed [5:0] tmp_fu_1291_p107;
wire  signed [5:0] tmp_fu_1291_p109;
wire  signed [5:0] tmp_fu_1291_p111;
wire  signed [5:0] tmp_fu_1291_p113;
wire  signed [5:0] tmp_fu_1291_p115;
wire  signed [5:0] tmp_fu_1291_p117;
wire  signed [5:0] tmp_fu_1291_p119;
wire  signed [5:0] tmp_fu_1291_p121;
wire  signed [5:0] tmp_fu_1291_p123;
wire  signed [5:0] tmp_fu_1291_p125;
wire  signed [5:0] tmp_fu_1291_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 sf_fu_202 = 32'd0;
#0 i_fu_206 = 13'd0;
#0 p_0_0_07625_fu_210 = 8'd0;
#0 inputBuf_fu_214 = 2'd0;
#0 inputBuf_1_fu_218 = 2'd0;
#0 inputBuf_2_fu_222 = 2'd0;
#0 inputBuf_3_fu_226 = 2'd0;
#0 inputBuf_4_fu_230 = 2'd0;
#0 inputBuf_5_fu_234 = 2'd0;
#0 inputBuf_6_fu_238 = 2'd0;
#0 inputBuf_7_fu_242 = 2'd0;
#0 inputBuf_8_fu_246 = 2'd0;
#0 inputBuf_9_fu_250 = 2'd0;
#0 inputBuf_10_fu_254 = 2'd0;
#0 inputBuf_11_fu_258 = 2'd0;
#0 inputBuf_12_fu_262 = 2'd0;
#0 inputBuf_13_fu_266 = 2'd0;
#0 inputBuf_14_fu_270 = 2'd0;
#0 inputBuf_15_fu_274 = 2'd0;
#0 inputBuf_16_fu_278 = 2'd0;
#0 inputBuf_17_fu_282 = 2'd0;
#0 inputBuf_18_fu_286 = 2'd0;
#0 inputBuf_19_fu_290 = 2'd0;
#0 inputBuf_20_fu_294 = 2'd0;
#0 inputBuf_21_fu_298 = 2'd0;
#0 inputBuf_22_fu_302 = 2'd0;
#0 inputBuf_23_fu_306 = 2'd0;
#0 inputBuf_24_fu_310 = 2'd0;
#0 inputBuf_25_fu_314 = 2'd0;
#0 inputBuf_26_fu_318 = 2'd0;
#0 inputBuf_27_fu_322 = 2'd0;
#0 inputBuf_28_fu_326 = 2'd0;
#0 inputBuf_29_fu_330 = 2'd0;
#0 inputBuf_30_fu_334 = 2'd0;
#0 inputBuf_31_fu_338 = 2'd0;
#0 inputBuf_32_fu_342 = 2'd0;
#0 inputBuf_33_fu_346 = 2'd0;
#0 inputBuf_34_fu_350 = 2'd0;
#0 inputBuf_35_fu_354 = 2'd0;
#0 inputBuf_36_fu_358 = 2'd0;
#0 inputBuf_37_fu_362 = 2'd0;
#0 inputBuf_38_fu_366 = 2'd0;
#0 inputBuf_39_fu_370 = 2'd0;
#0 inputBuf_40_fu_374 = 2'd0;
#0 inputBuf_41_fu_378 = 2'd0;
#0 inputBuf_42_fu_382 = 2'd0;
#0 inputBuf_43_fu_386 = 2'd0;
#0 inputBuf_44_fu_390 = 2'd0;
#0 inputBuf_45_fu_394 = 2'd0;
#0 inputBuf_46_fu_398 = 2'd0;
#0 inputBuf_47_fu_402 = 2'd0;
#0 inputBuf_48_fu_406 = 2'd0;
#0 inputBuf_49_fu_410 = 2'd0;
#0 inputBuf_50_fu_414 = 2'd0;
#0 inputBuf_51_fu_418 = 2'd0;
#0 inputBuf_52_fu_422 = 2'd0;
#0 inputBuf_53_fu_426 = 2'd0;
#0 inputBuf_54_fu_430 = 2'd0;
#0 inputBuf_55_fu_434 = 2'd0;
#0 inputBuf_56_fu_438 = 2'd0;
#0 inputBuf_57_fu_442 = 2'd0;
#0 inputBuf_58_fu_446 = 2'd0;
#0 inputBuf_59_fu_450 = 2'd0;
#0 inputBuf_60_fu_454 = 2'd0;
#0 inputBuf_61_fu_458 = 2'd0;
#0 inputBuf_62_fu_462 = 2'd0;
#0 inputBuf_63_fu_466 = 2'd0;
#0 nf_1_fu_470 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MatrixVectorActivation_1_sparsemux_129_6_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 2 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 2 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 2 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 2 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 2 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 2 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 2 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 2 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 2 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 2 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 2 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 2 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 2 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 2 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 2 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 2 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 2 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 2 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 2 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 2 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 2 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 2 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 2 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 2 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 2 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 2 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 2 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 2 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 2 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 2 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 2 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 2 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 2 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 2 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 2 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 2 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 2 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 2 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 2 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 2 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 2 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 2 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 2 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 2 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 2 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 2 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 2 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 2 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 2 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 2 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 2 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 2 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 2 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 2 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 2 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 2 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 2 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 2 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 2 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 2 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 2 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 2 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 2 ))
sparsemux_129_6_2_1_1_U1(
    .din0(inputBuf_fu_214),
    .din1(inputBuf_1_fu_218),
    .din2(inputBuf_2_fu_222),
    .din3(inputBuf_3_fu_226),
    .din4(inputBuf_4_fu_230),
    .din5(inputBuf_5_fu_234),
    .din6(inputBuf_6_fu_238),
    .din7(inputBuf_7_fu_242),
    .din8(inputBuf_8_fu_246),
    .din9(inputBuf_9_fu_250),
    .din10(inputBuf_10_fu_254),
    .din11(inputBuf_11_fu_258),
    .din12(inputBuf_12_fu_262),
    .din13(inputBuf_13_fu_266),
    .din14(inputBuf_14_fu_270),
    .din15(inputBuf_15_fu_274),
    .din16(inputBuf_16_fu_278),
    .din17(inputBuf_17_fu_282),
    .din18(inputBuf_18_fu_286),
    .din19(inputBuf_19_fu_290),
    .din20(inputBuf_20_fu_294),
    .din21(inputBuf_21_fu_298),
    .din22(inputBuf_22_fu_302),
    .din23(inputBuf_23_fu_306),
    .din24(inputBuf_24_fu_310),
    .din25(inputBuf_25_fu_314),
    .din26(inputBuf_26_fu_318),
    .din27(inputBuf_27_fu_322),
    .din28(inputBuf_28_fu_326),
    .din29(inputBuf_29_fu_330),
    .din30(inputBuf_30_fu_334),
    .din31(inputBuf_31_fu_338),
    .din32(inputBuf_32_fu_342),
    .din33(inputBuf_33_fu_346),
    .din34(inputBuf_34_fu_350),
    .din35(inputBuf_35_fu_354),
    .din36(inputBuf_36_fu_358),
    .din37(inputBuf_37_fu_362),
    .din38(inputBuf_38_fu_366),
    .din39(inputBuf_39_fu_370),
    .din40(inputBuf_40_fu_374),
    .din41(inputBuf_41_fu_378),
    .din42(inputBuf_42_fu_382),
    .din43(inputBuf_43_fu_386),
    .din44(inputBuf_44_fu_390),
    .din45(inputBuf_45_fu_394),
    .din46(inputBuf_46_fu_398),
    .din47(inputBuf_47_fu_402),
    .din48(inputBuf_48_fu_406),
    .din49(inputBuf_49_fu_410),
    .din50(inputBuf_50_fu_414),
    .din51(inputBuf_51_fu_418),
    .din52(inputBuf_52_fu_422),
    .din53(inputBuf_53_fu_426),
    .din54(inputBuf_54_fu_430),
    .din55(inputBuf_55_fu_434),
    .din56(inputBuf_56_fu_438),
    .din57(inputBuf_57_fu_442),
    .din58(inputBuf_58_fu_446),
    .din59(inputBuf_59_fu_450),
    .din60(inputBuf_60_fu_454),
    .din61(inputBuf_61_fu_458),
    .din62(inputBuf_62_fu_462),
    .din63(inputBuf_63_fu_466),
    .def(tmp_fu_1291_p129),
    .sel(trunc_ln242_reg_2093),
    .dout(tmp_fu_1291_p131)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln115_fu_1577_p0),
    .din1(W_packed_reg_2170_pp0_iter1_reg),
    .dout(mul_ln115_fu_1577_p2)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd62)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == 
    ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd3)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd4)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) 
    & (trunc_ln242_fu_703_p1 == 6'd5)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd6)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd7)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd8)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 
    == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd9)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd10)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd11)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 
    == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd12)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd13)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd14)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd15)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) 
    | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd16)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd17)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd18)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 
    == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd19)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd20)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd21)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd22)) | (~((1'b1 
    == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd23)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd24)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd25)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) 
    & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd26)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd27)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd28)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 
    == 6'd29)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd30)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd31)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd32)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) 
    | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd33)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd34)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd35)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 
    == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd36)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd37)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd38)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd39)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == 
    ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd40)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd41)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd42)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 
    == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd43)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd44)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd45)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd46)) | (~((1'b1 
    == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd47)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd48)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd49)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) 
    & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd50)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd51)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd52)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 
    == 6'd53)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd54)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd55)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd56)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) 
    | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd57)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd58)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd59)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 
    == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd60)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd61)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd63)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_532 <= inputBuf_64_fu_713_p1;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_532 <= ap_phi_reg_pp0_iter0_inElem_reg_532;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_153)) begin
        if (((icmp_ln253_reg_2098_pp0_iter0_reg == 1'd0) & (icmp_ln249_reg_2089_pp0_iter0_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter2_inElem_reg_532 <= tmp_fu_1291_p131;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_inElem_reg_532 <= ap_phi_reg_pp0_iter1_inElem_reg_532;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if ((icmp_ln249_fu_691_p2 == 1'd0)) begin
            i_fu_206 <= i_2_fu_697_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_206 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_691_p2 == 1'd0) & (icmp_ln290_fu_1053_p2 == 1'd1))) begin
            nf_1_fu_470 <= nf_3_fu_1076_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_470 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_105)) begin
        if (((icmp_ln249_fu_691_p2 == 1'd0) & (icmp_ln290_fu_1053_p2 == 1'd1))) begin
            sf_fu_202 <= 32'd0;
        end else if (((icmp_ln249_fu_691_p2 == 1'd0) & (icmp_ln290_fu_1053_p2 == 1'd0))) begin
            sf_fu_202 <= sf_2_fu_1047_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_202 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        W_packed_reg_2170 <= W_packed_fu_1037_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_2089 <= icmp_ln249_fu_691_p2;
        icmp_ln253_reg_2098 <= icmp_ln253_fu_707_p2;
        icmp_ln272_reg_2175 <= icmp_ln272_fu_1041_p2;
        icmp_ln290_reg_2180 <= icmp_ln290_fu_1053_p2;
        nf_2_reg_2084 <= ap_sig_allocacmp_nf_2;
        trunc_ln242_reg_2093 <= trunc_ln242_fu_703_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        W_packed_reg_2170_pp0_iter1_reg <= W_packed_reg_2170;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_2089_pp0_iter1_reg <= icmp_ln249_reg_2089;
        icmp_ln272_reg_2175_pp0_iter1_reg <= icmp_ln272_reg_2175;
        icmp_ln290_reg_2180_pp0_iter1_reg <= icmp_ln290_reg_2180;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln108_1_reg_2209 <= icmp_ln108_1_fu_1607_p2;
        icmp_ln108_2_reg_2214 <= icmp_ln108_2_fu_1617_p2;
        icmp_ln108_reg_2204 <= icmp_ln108_fu_1597_p2;
        icmp_ln249_reg_2089_pp0_iter2_reg <= icmp_ln249_reg_2089_pp0_iter1_reg;
        icmp_ln290_reg_2180_pp0_iter2_reg <= icmp_ln290_reg_2180_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd10))) begin
        inputBuf_10_fu_254 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd11))) begin
        inputBuf_11_fu_258 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd12))) begin
        inputBuf_12_fu_262 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd13))) begin
        inputBuf_13_fu_266 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd14))) begin
        inputBuf_14_fu_270 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd15))) begin
        inputBuf_15_fu_274 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd16))) begin
        inputBuf_16_fu_278 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd17))) begin
        inputBuf_17_fu_282 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd18))) begin
        inputBuf_18_fu_286 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd19))) begin
        inputBuf_19_fu_290 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd1))) begin
        inputBuf_1_fu_218 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd20))) begin
        inputBuf_20_fu_294 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd21))) begin
        inputBuf_21_fu_298 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd22))) begin
        inputBuf_22_fu_302 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd23))) begin
        inputBuf_23_fu_306 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd24))) begin
        inputBuf_24_fu_310 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd25))) begin
        inputBuf_25_fu_314 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd26))) begin
        inputBuf_26_fu_318 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd27))) begin
        inputBuf_27_fu_322 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd28))) begin
        inputBuf_28_fu_326 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd29))) begin
        inputBuf_29_fu_330 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd2))) begin
        inputBuf_2_fu_222 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd30))) begin
        inputBuf_30_fu_334 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd31))) begin
        inputBuf_31_fu_338 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd32))) begin
        inputBuf_32_fu_342 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd33))) begin
        inputBuf_33_fu_346 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd34))) begin
        inputBuf_34_fu_350 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd35))) begin
        inputBuf_35_fu_354 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd36))) begin
        inputBuf_36_fu_358 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd37))) begin
        inputBuf_37_fu_362 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd38))) begin
        inputBuf_38_fu_366 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd39))) begin
        inputBuf_39_fu_370 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd3))) begin
        inputBuf_3_fu_226 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd40))) begin
        inputBuf_40_fu_374 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd41))) begin
        inputBuf_41_fu_378 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd42))) begin
        inputBuf_42_fu_382 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd43))) begin
        inputBuf_43_fu_386 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd44))) begin
        inputBuf_44_fu_390 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd45))) begin
        inputBuf_45_fu_394 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd46))) begin
        inputBuf_46_fu_398 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd47))) begin
        inputBuf_47_fu_402 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd48))) begin
        inputBuf_48_fu_406 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd49))) begin
        inputBuf_49_fu_410 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd4))) begin
        inputBuf_4_fu_230 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd50))) begin
        inputBuf_50_fu_414 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd51))) begin
        inputBuf_51_fu_418 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd52))) begin
        inputBuf_52_fu_422 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd53))) begin
        inputBuf_53_fu_426 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd54))) begin
        inputBuf_54_fu_430 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd55))) begin
        inputBuf_55_fu_434 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd56))) begin
        inputBuf_56_fu_438 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd57))) begin
        inputBuf_57_fu_442 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd58))) begin
        inputBuf_58_fu_446 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd59))) begin
        inputBuf_59_fu_450 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd5))) begin
        inputBuf_5_fu_234 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd60))) begin
        inputBuf_60_fu_454 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd61))) begin
        inputBuf_61_fu_458 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd62))) begin
        inputBuf_62_fu_462 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd63))) begin
        inputBuf_63_fu_466 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd6))) begin
        inputBuf_6_fu_238 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd7))) begin
        inputBuf_7_fu_242 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd8))) begin
        inputBuf_8_fu_246 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd9))) begin
        inputBuf_9_fu_250 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_703_p1 == 6'd0))) begin
        inputBuf_fu_214 <= inputBuf_64_fu_713_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln249_reg_2089_pp0_iter1_reg == 1'd0))) begin
        p_0_0_07625_fu_210 <= add_ln169_fu_1587_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_691_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 13'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_206;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_470;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_202;
    end
end

always @ (*) begin
    if (((ap_predicate_op94_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (ap_predicate_op94_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op343_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (ap_predicate_op343_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (icmp_ln249_fu_691_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (icmp_ln249_reg_2089_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign W_packed_fu_1037_p1 = weights_V_TDATA[1:0];

assign add_ln169_fu_1587_p2 = ($signed(select_ln272_fu_1563_p3) + $signed(sext_ln169_fu_1583_p1));

assign add_ln218_fu_1655_p2 = (zext_ln218_2_fu_1633_p1 + zext_ln218_1_fu_1651_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_691_p2 == 1'd0)) | ((ap_predicate_op94_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op343_write_state4 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op343_write_state4 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_105 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_153 = (~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_532 = 'bx;

always @ (*) begin
    ap_predicate_op343_write_state4 = ((icmp_ln290_reg_2180_pp0_iter2_reg == 1'd1) & (icmp_ln249_reg_2089_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op94_read_state1 = ((icmp_ln253_fu_707_p2 == 1'd1) & (icmp_ln249_fu_691_p2 == 1'd0));
end

assign i_2_fu_697_p2 = (ap_sig_allocacmp_i_1 + 13'd1);

assign icmp_ln108_1_fu_1607_p2 = (($signed(add_ln169_fu_1587_p2) < $signed(zext_ln108_1_fu_1603_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_2_fu_1617_p2 = (($signed(add_ln169_fu_1587_p2) < $signed(zext_ln108_2_fu_1613_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_1597_p2 = (($signed(add_ln169_fu_1587_p2) < $signed(zext_ln108_fu_1593_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_691_p2 = ((ap_sig_allocacmp_i_1 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_2089_pp0_iter0_reg = icmp_ln249_reg_2089;

assign icmp_ln253_fu_707_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln253_reg_2098_pp0_iter0_reg = icmp_ln253_reg_2098;

assign icmp_ln272_fu_1041_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_1053_p2 = ((sf_2_fu_1047_p2 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_1070_p2 = ((nf_fu_1064_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_1554_p1 = nf_2_reg_2084;

assign inputBuf_64_fu_713_p1 = in0_V_TDATA[1:0];

assign mul_ln115_fu_1577_p0 = mul_ln115_fu_1577_p00;

assign mul_ln115_fu_1577_p00 = ap_phi_reg_pp0_iter2_inElem_reg_532;

assign nf_3_fu_1076_p3 = ((icmp_ln302_fu_1070_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_1064_p2);

assign nf_fu_1064_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = result_2_fu_1661_p2;

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_1554_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_1554_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_1554_p1;

assign result_2_fu_1661_p2 = (add_ln218_fu_1655_p2 + zext_ln218_fu_1642_p1);

assign result_fu_1628_p2 = (icmp_ln108_reg_2204 ^ 1'd1);

assign select_ln272_fu_1563_p3 = ((icmp_ln272_reg_2175_pp0_iter1_reg[0:0] == 1'b1) ? 8'd0 : p_0_0_07625_fu_210);

assign sext_ln169_fu_1583_p1 = mul_ln115_fu_1577_p2;

assign sf_2_fu_1047_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_1291_p129 = 'bx;

assign trunc_ln242_fu_703_p1 = ap_sig_allocacmp_sf_1[5:0];

assign xor_ln108_1_fu_1646_p2 = (icmp_ln108_2_reg_2214 ^ 1'd1);

assign xor_ln108_fu_1637_p2 = (icmp_ln108_1_reg_2209 ^ 1'd1);

assign zext_ln108_1_fu_1603_p1 = p_ZL7threshs_1_q0;

assign zext_ln108_2_fu_1613_p1 = p_ZL7threshs_2_q0;

assign zext_ln108_fu_1593_p1 = p_ZL7threshs_0_q0;

assign zext_ln218_1_fu_1651_p1 = xor_ln108_1_fu_1646_p2;

assign zext_ln218_2_fu_1633_p1 = result_fu_1628_p2;

assign zext_ln218_fu_1642_p1 = xor_ln108_fu_1637_p2;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch
