// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MatrixVectorActivation_3_MatrixVectorActivation_3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.241500,HLS_SYN_LAT=69,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=107,HLS_SYN_LUT=347,HLS_VERSION=2023_2}" *)

module MatrixVectorActivation_3 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln123_fu_134_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] ap_CS_iter3_fsm;
reg   [0:0] icmp_ln123_reg_301;
reg   [0:0] icmp_ln123_reg_301_pp0_iter2_reg;
reg   [0:0] icmp_ln161_reg_320;
reg   [0:0] icmp_ln161_reg_320_pp0_iter2_reg;
reg    ap_predicate_op62_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg   [1:0] ap_CS_iter4_fsm;
reg   [0:0] icmp_ln123_reg_301_pp0_iter3_reg;
reg   [0:0] icmp_ln161_reg_320_pp0_iter3_reg;
reg    ap_predicate_op65_write_state5;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
wire    ap_CS_iter4_fsm_state5;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [5:0] weights_40_address0;
reg    weights_40_ce0;
wire   [1:0] weights_40_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [0:0] icmp_ln123_reg_301_pp0_iter0_reg;
reg   [0:0] icmp_ln123_reg_301_pp0_iter1_reg;
wire   [1:0] act_fu_146_p1;
reg   [1:0] act_reg_305;
reg   [1:0] act_reg_305_pp0_iter1_reg;
reg   [1:0] act_reg_305_pp0_iter2_reg;
wire   [0:0] icmp_ln138_fu_161_p2;
reg   [0:0] icmp_ln138_reg_310;
reg   [0:0] icmp_ln138_reg_310_pp0_iter2_reg;
wire   [0:0] icmp_ln161_fu_184_p2;
reg  signed [1:0] local_temp_reg_324;
wire   [63:0] idxprom2_i26_i_fu_167_p1;
reg   [31:0] tile_fu_74;
wire   [31:0] tile_1_fu_172_p2;
wire    ap_loop_init;
reg   [31:0] sf_fu_78;
wire   [31:0] sf_1_fu_178_p2;
reg   [6:0] i_fu_82;
wire   [6:0] i_2_fu_140_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [7:0] p_0_0_062_i3_fu_86;
wire   [7:0] add_ln169_fu_240_p2;
wire   [1:0] mul_ln115_fu_226_p0;
wire   [3:0] mul_ln115_fu_226_p2;
wire   [2:0] trunc_ln115_fu_232_p1;
wire   [7:0] select_ln138_fu_213_p3;
wire  signed [7:0] sext_ln169_fu_236_p1;
wire   [6:0] tmp_fu_246_p4;
wire   [0:0] result_fu_256_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire   [7:0] out_V_TDATA_int_regslice;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
wire   [3:0] mul_ln115_fu_226_p00;
reg    ap_condition_120;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 tile_fu_74 = 32'd0;
#0 sf_fu_78 = 32'd0;
#0 i_fu_82 = 7'd0;
#0 p_0_0_062_i3_fu_86 = 8'd0;
end

MatrixVectorActivation_3_weights_40_ROM_AUTO_1R #(
    .DataWidth( 2 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
weights_40_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(weights_40_address0),
    .ce0(weights_40_ce0),
    .q0(weights_40_q0)
);

MatrixVectorActivation_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U1(
    .din0(mul_ln115_fu_226_p0),
    .din1(local_temp_reg_324),
    .dout(mul_ln115_fu_226_p2)
);

MatrixVectorActivation_3_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

MatrixVectorActivation_3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

MatrixVectorActivation_3_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_V_TDATA_int_regslice),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_120)) begin
        if ((icmp_ln123_fu_134_p2 == 1'd0)) begin
            i_fu_82 <= i_2_fu_140_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln161_fu_184_p2 == 1'd1) & (icmp_ln123_reg_301_pp0_iter0_reg == 1'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1)))) begin
        sf_fu_78 <= 32'd0;
    end else if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln161_fu_184_p2 == 1'd0) & (icmp_ln123_reg_301_pp0_iter0_reg == 1'd0))) begin
        sf_fu_78 <= sf_1_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln161_fu_184_p2 == 1'd1) & (icmp_ln123_reg_301_pp0_iter0_reg == 1'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1)))) begin
        tile_fu_74 <= 32'd0;
    end else if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln161_fu_184_p2 == 1'd0) & (icmp_ln123_reg_301_pp0_iter0_reg == 1'd0))) begin
        tile_fu_74 <= tile_1_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        act_reg_305 <= act_fu_146_p1;
        icmp_ln123_reg_301 <= icmp_ln123_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        act_reg_305_pp0_iter1_reg <= act_reg_305;
        icmp_ln123_reg_301_pp0_iter1_reg <= icmp_ln123_reg_301;
        icmp_ln138_reg_310 <= icmp_ln138_fu_161_p2;
        icmp_ln161_reg_320 <= icmp_ln161_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        act_reg_305_pp0_iter2_reg <= act_reg_305_pp0_iter1_reg;
        icmp_ln123_reg_301_pp0_iter2_reg <= icmp_ln123_reg_301_pp0_iter1_reg;
        icmp_ln138_reg_310_pp0_iter2_reg <= icmp_ln138_reg_310;
        icmp_ln161_reg_320_pp0_iter2_reg <= icmp_ln161_reg_320;
        local_temp_reg_324 <= weights_40_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln123_reg_301_pp0_iter3_reg <= icmp_ln123_reg_301_pp0_iter2_reg;
        icmp_ln161_reg_320_pp0_iter3_reg <= icmp_ln161_reg_320_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln123_reg_301_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        p_0_0_062_i3_fu_86 <= add_ln169_fu_240_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln123_fu_134_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_82;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln123_fu_134_p2 == 1'd0))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln123_fu_134_p2 == 1'd0))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op62_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (ap_predicate_op65_write_state5 == 1'b1)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (ap_predicate_op62_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        weights_40_ce0 = 1'b1;
    end else begin
        weights_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & ~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & ((1'b0 == ap_CS_iter3_fsm_state4) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (icmp_ln123_reg_301_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter4_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

assign act_fu_146_p1 = in0_V_TDATA_int_regslice[1:0];

assign add_ln169_fu_240_p2 = ($signed(select_ln138_fu_213_p3) + $signed(sext_ln169_fu_236_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln123_fu_134_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state4_io = ((ap_predicate_op62_write_state4 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op62_write_state4 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op65_write_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op65_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_condition_120 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_predicate_op62_write_state4 = ((icmp_ln161_reg_320_pp0_iter2_reg == 1'd1) & (icmp_ln123_reg_301_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op65_write_state5 = ((icmp_ln161_reg_320_pp0_iter3_reg == 1'd1) & (icmp_ln123_reg_301_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_2_fu_140_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln123_fu_134_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln123_reg_301_pp0_iter0_reg = icmp_ln123_reg_301;

assign icmp_ln138_fu_161_p2 = ((sf_fu_78 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_184_p2 = ((sf_1_fu_178_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i26_i_fu_167_p1 = tile_fu_74;

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign mul_ln115_fu_226_p0 = mul_ln115_fu_226_p00;

assign mul_ln115_fu_226_p00 = act_reg_305_pp0_iter2_reg;

assign out_V_TDATA_int_regslice = result_fu_256_p2;

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign result_fu_256_p2 = (($signed(tmp_fu_246_p4) > $signed(7'd0)) ? 1'b1 : 1'b0);

assign select_ln138_fu_213_p3 = ((icmp_ln138_reg_310_pp0_iter2_reg[0:0] == 1'b1) ? 8'd0 : p_0_0_062_i3_fu_86);

assign sext_ln169_fu_236_p1 = $signed(trunc_ln115_fu_232_p1);

assign sf_1_fu_178_p2 = (sf_fu_78 + 32'd1);

assign tile_1_fu_172_p2 = (tile_fu_74 + 32'd1);

assign tmp_fu_246_p4 = {{add_ln169_fu_240_p2[7:1]}};

assign trunc_ln115_fu_232_p1 = mul_ln115_fu_226_p2[2:0];

assign weights_40_address0 = idxprom2_i26_i_fu_167_p1;

endmodule //MatrixVectorActivation_3
