#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< Updated upstream
# Generated by Vivado on Thu Jan 25 17:26:09 -03 2024
=======
# Generated by Vivado on Sun Feb 11 02:35:18 -03 2024
>>>>>>> Stashed changes
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
<<<<<<< Updated upstream
echo "xsim testbench_behav -key {Behavioral:sim_1:Functional:testbench} -tclbatch testbench.tcl -protoinst "protoinst_files/finn_design.protoinst" -view /home/afely/Desktop/finn-notebook/notebooks/end2end_example/cybersecurity/output_ipstitch_ooc_rtlsim/stitched_ip/testbench_behav.wcfg -log simulate.log"
xsim testbench_behav -key {Behavioral:sim_1:Functional:testbench} -tclbatch testbench.tcl -protoinst "protoinst_files/finn_design.protoinst" -view /home/afely/Desktop/finn-notebook/notebooks/end2end_example/cybersecurity/output_ipstitch_ooc_rtlsim/stitched_ip/testbench_behav.wcfg -log simulate.log
=======
echo "xsim tb_finn_behav -key {Behavioral:sim_1:Functional:tb_finn} -tclbatch tb_finn.tcl -protoinst "protoinst_files/finn_design.protoinst" -view /home/finn/Desktop/finn/notebooks/end2end_example/cybersecurity/output_ipstitch_ooc_rtlsim/stitched_ip/tb_finn_behav.wcfg -log simulate.log"
xsim tb_finn_behav -key {Behavioral:sim_1:Functional:tb_finn} -tclbatch tb_finn.tcl -protoinst "protoinst_files/finn_design.protoinst" -view /home/finn/Desktop/finn/notebooks/end2end_example/cybersecurity/output_ipstitch_ooc_rtlsim/stitched_ip/tb_finn_behav.wcfg -log simulate.log
>>>>>>> Stashed changes

