// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [127:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
wire   [0:0] icmp_ln123_fu_546_p2;
wire   [0:0] icmp_ln126_fu_558_p2;
reg    ap_predicate_op29_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_CS_iter4_fsm_state5;
reg   [0:0] icmp_ln123_reg_3658;
reg   [0:0] icmp_ln123_reg_3658_pp0_iter4_reg;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
wire    ap_CS_iter5_fsm_state6;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] weights_39_address0;
reg    weights_39_ce0;
wire   [127:0] weights_39_q0;
wire   [5:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [5:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [6:0] p_ZL7threshs_1_q0;
wire   [5:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [6:0] p_ZL7threshs_2_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg   [31:0] nf_3_reg_3653;
wire   [0:0] icmp_ln123_reg_3658_pp0_iter0_reg;
reg   [0:0] icmp_ln123_reg_3658_pp0_iter1_reg;
reg   [0:0] icmp_ln123_reg_3658_pp0_iter2_reg;
reg   [0:0] icmp_ln123_reg_3658_pp0_iter3_reg;
wire   [0:0] icmp_ln174_fu_575_p2;
reg   [0:0] icmp_ln174_reg_3665;
wire   [1:0] r_fu_610_p1;
reg   [1:0] r_reg_3675;
reg   [1:0] r_1_reg_3680;
reg   [1:0] r_2_reg_3685;
reg   [1:0] r_3_reg_3690;
reg   [1:0] r_4_reg_3695;
reg   [1:0] r_5_reg_3700;
reg   [1:0] r_6_reg_3705;
reg   [1:0] r_7_reg_3710;
reg   [1:0] r_8_reg_3715;
reg   [1:0] r_9_reg_3720;
reg   [1:0] r_10_reg_3725;
reg   [1:0] r_11_reg_3730;
reg   [1:0] r_12_reg_3735;
reg   [1:0] r_13_reg_3740;
reg   [1:0] r_14_reg_3745;
reg   [1:0] r_15_reg_3750;
reg   [1:0] r_16_reg_3755;
reg   [1:0] r_17_reg_3760;
reg   [1:0] r_18_reg_3765;
reg   [1:0] r_19_reg_3770;
reg   [1:0] r_20_reg_3775;
reg   [1:0] r_21_reg_3780;
reg   [1:0] r_22_reg_3785;
reg   [1:0] r_23_reg_3790;
reg   [1:0] r_24_reg_3795;
reg   [1:0] r_25_reg_3800;
reg   [1:0] r_26_reg_3805;
reg   [1:0] r_27_reg_3810;
reg   [1:0] r_28_reg_3815;
reg   [1:0] r_29_reg_3820;
reg   [1:0] r_30_reg_3825;
reg   [1:0] r_31_reg_3830;
reg   [1:0] r_32_reg_3835;
reg   [1:0] r_33_reg_3840;
reg   [1:0] r_34_reg_3845;
reg   [1:0] r_35_reg_3850;
reg   [1:0] r_36_reg_3855;
reg   [1:0] r_37_reg_3860;
reg   [1:0] r_38_reg_3865;
reg   [1:0] r_39_reg_3870;
reg   [1:0] r_40_reg_3875;
reg   [1:0] r_41_reg_3880;
reg   [1:0] r_42_reg_3885;
reg   [1:0] r_43_reg_3890;
reg   [1:0] r_44_reg_3895;
reg   [1:0] r_45_reg_3900;
reg   [1:0] r_46_reg_3905;
reg   [1:0] r_47_reg_3910;
reg   [1:0] r_48_reg_3915;
reg   [1:0] r_49_reg_3920;
reg   [1:0] r_50_reg_3925;
reg   [1:0] r_51_reg_3930;
reg   [1:0] r_52_reg_3935;
reg   [1:0] r_53_reg_3940;
reg   [1:0] r_54_reg_3945;
reg   [1:0] r_55_reg_3950;
reg   [1:0] r_56_reg_3955;
reg   [1:0] r_57_reg_3960;
reg   [1:0] r_58_reg_3965;
reg   [1:0] r_59_reg_3970;
reg   [1:0] r_60_reg_3975;
reg   [1:0] r_61_reg_3980;
reg   [1:0] r_62_reg_3985;
reg   [1:0] r_63_reg_3990;
wire   [4:0] add_ln169_fu_2990_p2;
reg   [4:0] add_ln169_reg_4010;
wire   [4:0] add_ln169_1_fu_2996_p2;
reg   [4:0] add_ln169_1_reg_4015;
wire   [4:0] add_ln169_3_fu_3002_p2;
reg   [4:0] add_ln169_3_reg_4020;
wire   [4:0] add_ln169_4_fu_3008_p2;
reg   [4:0] add_ln169_4_reg_4025;
wire   [4:0] add_ln169_7_fu_3014_p2;
reg   [4:0] add_ln169_7_reg_4030;
wire   [4:0] add_ln169_8_fu_3020_p2;
reg   [4:0] add_ln169_8_reg_4035;
wire   [4:0] add_ln169_10_fu_3026_p2;
reg   [4:0] add_ln169_10_reg_4040;
wire   [4:0] add_ln169_11_fu_3032_p2;
reg   [4:0] add_ln169_11_reg_4045;
wire   [4:0] add_ln169_15_fu_3038_p2;
reg   [4:0] add_ln169_15_reg_4050;
wire   [4:0] add_ln169_16_fu_3044_p2;
reg   [4:0] add_ln169_16_reg_4055;
wire   [4:0] add_ln169_18_fu_3050_p2;
reg   [4:0] add_ln169_18_reg_4060;
wire   [4:0] add_ln169_19_fu_3056_p2;
reg   [4:0] add_ln169_19_reg_4065;
wire   [4:0] add_ln169_22_fu_3062_p2;
reg   [4:0] add_ln169_22_reg_4070;
wire   [4:0] add_ln169_23_fu_3068_p2;
reg   [4:0] add_ln169_23_reg_4075;
wire   [4:0] add_ln169_25_fu_3074_p2;
reg   [4:0] add_ln169_25_reg_4080;
wire   [4:0] add_ln169_26_fu_3080_p2;
reg   [4:0] add_ln169_26_reg_4085;
wire   [4:0] add_ln169_31_fu_3086_p2;
reg   [4:0] add_ln169_31_reg_4090;
wire   [4:0] add_ln169_32_fu_3092_p2;
reg   [4:0] add_ln169_32_reg_4095;
wire   [4:0] add_ln169_34_fu_3098_p2;
reg   [4:0] add_ln169_34_reg_4100;
wire   [4:0] add_ln169_35_fu_3104_p2;
reg   [4:0] add_ln169_35_reg_4105;
wire   [4:0] add_ln169_38_fu_3110_p2;
reg   [4:0] add_ln169_38_reg_4110;
wire   [4:0] add_ln169_39_fu_3116_p2;
reg   [4:0] add_ln169_39_reg_4115;
wire   [4:0] add_ln169_41_fu_3122_p2;
reg   [4:0] add_ln169_41_reg_4120;
wire   [4:0] add_ln169_42_fu_3128_p2;
reg   [4:0] add_ln169_42_reg_4125;
wire   [4:0] add_ln169_46_fu_3134_p2;
reg   [4:0] add_ln169_46_reg_4130;
wire   [4:0] add_ln169_47_fu_3140_p2;
reg   [4:0] add_ln169_47_reg_4135;
wire   [4:0] add_ln169_49_fu_3146_p2;
reg   [4:0] add_ln169_49_reg_4140;
wire   [4:0] add_ln169_50_fu_3152_p2;
reg   [4:0] add_ln169_50_reg_4145;
wire   [4:0] add_ln169_53_fu_3158_p2;
reg   [4:0] add_ln169_53_reg_4150;
wire   [4:0] add_ln169_54_fu_3164_p2;
reg   [4:0] add_ln169_54_reg_4155;
wire   [4:0] add_ln169_56_fu_3170_p2;
reg   [4:0] add_ln169_56_reg_4160;
wire   [4:0] add_ln169_57_fu_3176_p2;
reg   [4:0] add_ln169_57_reg_4165;
reg   [5:0] p_ZL7threshs_0_load_reg_4170;
reg   [5:0] p_ZL7threshs_0_load_reg_4170_pp0_iter3_reg;
reg   [5:0] p_ZL7threshs_0_load_reg_4170_pp0_iter4_reg;
reg   [6:0] p_ZL7threshs_1_load_reg_4175;
reg   [6:0] p_ZL7threshs_1_load_reg_4175_pp0_iter3_reg;
reg   [6:0] p_ZL7threshs_1_load_reg_4175_pp0_iter4_reg;
reg   [6:0] p_ZL7threshs_2_load_reg_4180;
reg   [6:0] p_ZL7threshs_2_load_reg_4180_pp0_iter3_reg;
reg   [6:0] p_ZL7threshs_2_load_reg_4180_pp0_iter4_reg;
wire   [7:0] add_ln169_14_fu_3266_p2;
reg   [7:0] add_ln169_14_reg_4185;
wire   [7:0] add_ln169_29_fu_3356_p2;
reg   [7:0] add_ln169_29_reg_4190;
wire   [6:0] add_ln169_37_fu_3394_p2;
reg   [6:0] add_ln169_37_reg_4195;
wire   [6:0] add_ln169_44_fu_3432_p2;
reg   [6:0] add_ln169_44_reg_4200;
wire   [7:0] add_ln169_60_fu_3522_p2;
reg   [7:0] add_ln169_60_reg_4205;
wire   [7:0] add_ln169_62_fu_3549_p2;
reg   [7:0] add_ln169_62_reg_4210;
wire   [63:0] idxprom2_i26_fu_605_p1;
wire   [63:0] idxprom2_i_fu_1250_p1;
reg   [31:0] tile_fu_444;
wire   [31:0] tile_2_fu_1256_p3;
wire    ap_loop_init;
reg   [31:0] nf_1_fu_448;
wire   [31:0] nf_4_fu_581_p3;
reg   [31:0] ap_sig_allocacmp_nf_3;
reg   [6:0] i_fu_452;
wire   [6:0] i_2_fu_552_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [127:0] arrayidx3_0_0_0_load22_fu_456;
wire   [31:0] nf_fu_569_p2;
wire   [31:0] tile_1_fu_1244_p2;
wire  signed [1:0] local_temp_fu_1268_p1;
wire   [1:0] mul_ln115_fu_1909_p0;
wire  signed [3:0] mul_ln115_fu_1909_p2;
wire  signed [1:0] local_temp_1_fu_1272_p4;
wire   [1:0] mul_ln115_1_fu_1926_p0;
wire  signed [3:0] mul_ln115_1_fu_1926_p2;
wire  signed [1:0] local_temp_2_fu_1282_p4;
wire   [1:0] mul_ln115_2_fu_1943_p0;
wire  signed [3:0] mul_ln115_2_fu_1943_p2;
wire  signed [1:0] local_temp_3_fu_1292_p4;
wire   [1:0] mul_ln115_3_fu_1960_p0;
wire  signed [3:0] mul_ln115_3_fu_1960_p2;
wire  signed [1:0] local_temp_4_fu_1302_p4;
wire   [1:0] mul_ln115_4_fu_1977_p0;
wire  signed [3:0] mul_ln115_4_fu_1977_p2;
wire  signed [1:0] local_temp_5_fu_1312_p4;
wire   [1:0] mul_ln115_5_fu_1994_p0;
wire  signed [3:0] mul_ln115_5_fu_1994_p2;
wire  signed [1:0] local_temp_6_fu_1322_p4;
wire   [1:0] mul_ln115_6_fu_2011_p0;
wire  signed [3:0] mul_ln115_6_fu_2011_p2;
wire  signed [1:0] local_temp_7_fu_1332_p4;
wire   [1:0] mul_ln115_7_fu_2028_p0;
wire  signed [3:0] mul_ln115_7_fu_2028_p2;
wire  signed [1:0] local_temp_8_fu_1342_p4;
wire   [1:0] mul_ln115_8_fu_2045_p0;
wire  signed [3:0] mul_ln115_8_fu_2045_p2;
wire  signed [1:0] local_temp_9_fu_1352_p4;
wire   [1:0] mul_ln115_9_fu_2062_p0;
wire  signed [3:0] mul_ln115_9_fu_2062_p2;
wire  signed [1:0] local_temp_10_fu_1362_p4;
wire   [1:0] mul_ln115_10_fu_2079_p0;
wire  signed [3:0] mul_ln115_10_fu_2079_p2;
wire  signed [1:0] local_temp_11_fu_1372_p4;
wire   [1:0] mul_ln115_11_fu_2096_p0;
wire  signed [3:0] mul_ln115_11_fu_2096_p2;
wire  signed [1:0] local_temp_12_fu_1382_p4;
wire   [1:0] mul_ln115_12_fu_2113_p0;
wire  signed [3:0] mul_ln115_12_fu_2113_p2;
wire  signed [1:0] local_temp_13_fu_1392_p4;
wire   [1:0] mul_ln115_13_fu_2130_p0;
wire  signed [3:0] mul_ln115_13_fu_2130_p2;
wire  signed [1:0] local_temp_14_fu_1402_p4;
wire   [1:0] mul_ln115_14_fu_2147_p0;
wire  signed [3:0] mul_ln115_14_fu_2147_p2;
wire  signed [1:0] local_temp_15_fu_1412_p4;
wire   [1:0] mul_ln115_15_fu_2164_p0;
wire  signed [3:0] mul_ln115_15_fu_2164_p2;
wire  signed [1:0] local_temp_16_fu_1422_p4;
wire   [1:0] mul_ln115_16_fu_2181_p0;
wire  signed [3:0] mul_ln115_16_fu_2181_p2;
wire  signed [1:0] local_temp_17_fu_1432_p4;
wire   [1:0] mul_ln115_17_fu_2198_p0;
wire  signed [3:0] mul_ln115_17_fu_2198_p2;
wire  signed [1:0] local_temp_18_fu_1442_p4;
wire   [1:0] mul_ln115_18_fu_2215_p0;
wire  signed [3:0] mul_ln115_18_fu_2215_p2;
wire  signed [1:0] local_temp_19_fu_1452_p4;
wire   [1:0] mul_ln115_19_fu_2232_p0;
wire  signed [3:0] mul_ln115_19_fu_2232_p2;
wire  signed [1:0] local_temp_20_fu_1462_p4;
wire   [1:0] mul_ln115_20_fu_2249_p0;
wire  signed [3:0] mul_ln115_20_fu_2249_p2;
wire  signed [1:0] local_temp_21_fu_1472_p4;
wire   [1:0] mul_ln115_21_fu_2266_p0;
wire  signed [3:0] mul_ln115_21_fu_2266_p2;
wire  signed [1:0] local_temp_22_fu_1482_p4;
wire   [1:0] mul_ln115_22_fu_2283_p0;
wire  signed [3:0] mul_ln115_22_fu_2283_p2;
wire  signed [1:0] local_temp_23_fu_1492_p4;
wire   [1:0] mul_ln115_23_fu_2300_p0;
wire  signed [3:0] mul_ln115_23_fu_2300_p2;
wire  signed [1:0] local_temp_24_fu_1502_p4;
wire   [1:0] mul_ln115_24_fu_2317_p0;
wire  signed [3:0] mul_ln115_24_fu_2317_p2;
wire  signed [1:0] local_temp_25_fu_1512_p4;
wire   [1:0] mul_ln115_25_fu_2334_p0;
wire  signed [3:0] mul_ln115_25_fu_2334_p2;
wire  signed [1:0] local_temp_26_fu_1522_p4;
wire   [1:0] mul_ln115_26_fu_2351_p0;
wire  signed [3:0] mul_ln115_26_fu_2351_p2;
wire  signed [1:0] local_temp_27_fu_1532_p4;
wire   [1:0] mul_ln115_27_fu_2368_p0;
wire  signed [3:0] mul_ln115_27_fu_2368_p2;
wire  signed [1:0] local_temp_28_fu_1542_p4;
wire   [1:0] mul_ln115_28_fu_2385_p0;
wire  signed [3:0] mul_ln115_28_fu_2385_p2;
wire  signed [1:0] local_temp_29_fu_1552_p4;
wire   [1:0] mul_ln115_29_fu_2402_p0;
wire  signed [3:0] mul_ln115_29_fu_2402_p2;
wire  signed [1:0] local_temp_30_fu_1562_p4;
wire   [1:0] mul_ln115_30_fu_2419_p0;
wire  signed [3:0] mul_ln115_30_fu_2419_p2;
wire  signed [1:0] local_temp_31_fu_1572_p4;
wire   [1:0] mul_ln115_31_fu_2436_p0;
wire  signed [3:0] mul_ln115_31_fu_2436_p2;
wire  signed [1:0] local_temp_32_fu_1582_p4;
wire   [1:0] mul_ln115_32_fu_2453_p0;
wire  signed [3:0] mul_ln115_32_fu_2453_p2;
wire  signed [1:0] local_temp_33_fu_1592_p4;
wire   [1:0] mul_ln115_33_fu_2470_p0;
wire  signed [3:0] mul_ln115_33_fu_2470_p2;
wire  signed [1:0] local_temp_34_fu_1602_p4;
wire   [1:0] mul_ln115_34_fu_2487_p0;
wire  signed [3:0] mul_ln115_34_fu_2487_p2;
wire  signed [1:0] local_temp_35_fu_1612_p4;
wire   [1:0] mul_ln115_35_fu_2504_p0;
wire  signed [3:0] mul_ln115_35_fu_2504_p2;
wire  signed [1:0] local_temp_36_fu_1622_p4;
wire   [1:0] mul_ln115_36_fu_2521_p0;
wire  signed [3:0] mul_ln115_36_fu_2521_p2;
wire  signed [1:0] local_temp_37_fu_1632_p4;
wire   [1:0] mul_ln115_37_fu_2538_p0;
wire  signed [3:0] mul_ln115_37_fu_2538_p2;
wire  signed [1:0] local_temp_38_fu_1642_p4;
wire   [1:0] mul_ln115_38_fu_2555_p0;
wire  signed [3:0] mul_ln115_38_fu_2555_p2;
wire  signed [1:0] local_temp_39_fu_1652_p4;
wire   [1:0] mul_ln115_39_fu_2572_p0;
wire  signed [3:0] mul_ln115_39_fu_2572_p2;
wire  signed [1:0] local_temp_40_fu_1662_p4;
wire   [1:0] mul_ln115_40_fu_2589_p0;
wire  signed [3:0] mul_ln115_40_fu_2589_p2;
wire  signed [1:0] local_temp_41_fu_1672_p4;
wire   [1:0] mul_ln115_41_fu_2606_p0;
wire  signed [3:0] mul_ln115_41_fu_2606_p2;
wire  signed [1:0] local_temp_42_fu_1682_p4;
wire   [1:0] mul_ln115_42_fu_2623_p0;
wire  signed [3:0] mul_ln115_42_fu_2623_p2;
wire  signed [1:0] local_temp_43_fu_1692_p4;
wire   [1:0] mul_ln115_43_fu_2640_p0;
wire  signed [3:0] mul_ln115_43_fu_2640_p2;
wire  signed [1:0] local_temp_44_fu_1702_p4;
wire   [1:0] mul_ln115_44_fu_2657_p0;
wire  signed [3:0] mul_ln115_44_fu_2657_p2;
wire  signed [1:0] local_temp_45_fu_1712_p4;
wire   [1:0] mul_ln115_45_fu_2674_p0;
wire  signed [3:0] mul_ln115_45_fu_2674_p2;
wire  signed [1:0] local_temp_46_fu_1722_p4;
wire   [1:0] mul_ln115_46_fu_2691_p0;
wire  signed [3:0] mul_ln115_46_fu_2691_p2;
wire  signed [1:0] local_temp_47_fu_1732_p4;
wire   [1:0] mul_ln115_47_fu_2708_p0;
wire  signed [3:0] mul_ln115_47_fu_2708_p2;
wire  signed [1:0] local_temp_48_fu_1742_p4;
wire   [1:0] mul_ln115_48_fu_2725_p0;
wire  signed [3:0] mul_ln115_48_fu_2725_p2;
wire  signed [1:0] local_temp_49_fu_1752_p4;
wire   [1:0] mul_ln115_49_fu_2742_p0;
wire  signed [3:0] mul_ln115_49_fu_2742_p2;
wire  signed [1:0] local_temp_50_fu_1762_p4;
wire   [1:0] mul_ln115_50_fu_2759_p0;
wire  signed [3:0] mul_ln115_50_fu_2759_p2;
wire  signed [1:0] local_temp_51_fu_1772_p4;
wire   [1:0] mul_ln115_51_fu_2776_p0;
wire  signed [3:0] mul_ln115_51_fu_2776_p2;
wire  signed [1:0] local_temp_52_fu_1782_p4;
wire   [1:0] mul_ln115_52_fu_2793_p0;
wire  signed [3:0] mul_ln115_52_fu_2793_p2;
wire  signed [1:0] local_temp_53_fu_1792_p4;
wire   [1:0] mul_ln115_53_fu_2810_p0;
wire  signed [3:0] mul_ln115_53_fu_2810_p2;
wire  signed [1:0] local_temp_54_fu_1802_p4;
wire   [1:0] mul_ln115_54_fu_2827_p0;
wire  signed [3:0] mul_ln115_54_fu_2827_p2;
wire  signed [1:0] local_temp_55_fu_1812_p4;
wire   [1:0] mul_ln115_55_fu_2844_p0;
wire  signed [3:0] mul_ln115_55_fu_2844_p2;
wire  signed [1:0] local_temp_56_fu_1822_p4;
wire   [1:0] mul_ln115_56_fu_2861_p0;
wire  signed [3:0] mul_ln115_56_fu_2861_p2;
wire  signed [1:0] local_temp_57_fu_1832_p4;
wire   [1:0] mul_ln115_57_fu_2878_p0;
wire  signed [3:0] mul_ln115_57_fu_2878_p2;
wire  signed [1:0] local_temp_58_fu_1842_p4;
wire   [1:0] mul_ln115_58_fu_2895_p0;
wire  signed [3:0] mul_ln115_58_fu_2895_p2;
wire  signed [1:0] local_temp_59_fu_1852_p4;
wire   [1:0] mul_ln115_59_fu_2912_p0;
wire  signed [3:0] mul_ln115_59_fu_2912_p2;
wire  signed [1:0] local_temp_60_fu_1862_p4;
wire   [1:0] mul_ln115_60_fu_2929_p0;
wire  signed [3:0] mul_ln115_60_fu_2929_p2;
wire  signed [1:0] local_temp_61_fu_1872_p4;
wire   [1:0] mul_ln115_61_fu_2946_p0;
wire  signed [3:0] mul_ln115_61_fu_2946_p2;
wire  signed [1:0] local_temp_62_fu_1882_p4;
wire   [1:0] mul_ln115_62_fu_2963_p0;
wire  signed [3:0] mul_ln115_62_fu_2963_p2;
wire  signed [1:0] local_temp_63_fu_1892_p4;
wire   [1:0] mul_ln115_63_fu_2980_p0;
wire  signed [3:0] mul_ln115_63_fu_2980_p2;
wire  signed [4:0] sext_ln216_61_fu_2952_p1;
wire  signed [4:0] sext_ln216_62_fu_2969_p1;
wire  signed [4:0] sext_ln216_60_fu_2935_p1;
wire  signed [4:0] sext_ln216_59_fu_2918_p1;
wire  signed [4:0] sext_ln216_56_fu_2867_p1;
wire  signed [4:0] sext_ln216_55_fu_2850_p1;
wire  signed [4:0] sext_ln216_58_fu_2901_p1;
wire  signed [4:0] sext_ln216_57_fu_2884_p1;
wire  signed [4:0] sext_ln216_48_fu_2731_p1;
wire  signed [4:0] sext_ln216_47_fu_2714_p1;
wire  signed [4:0] sext_ln216_50_fu_2765_p1;
wire  signed [4:0] sext_ln216_49_fu_2748_p1;
wire  signed [4:0] sext_ln216_52_fu_2799_p1;
wire  signed [4:0] sext_ln216_51_fu_2782_p1;
wire  signed [4:0] sext_ln216_54_fu_2833_p1;
wire  signed [4:0] sext_ln216_53_fu_2816_p1;
wire  signed [4:0] sext_ln216_32_fu_2459_p1;
wire  signed [4:0] sext_ln216_31_fu_2442_p1;
wire  signed [4:0] sext_ln216_34_fu_2493_p1;
wire  signed [4:0] sext_ln216_33_fu_2476_p1;
wire  signed [4:0] sext_ln216_36_fu_2527_p1;
wire  signed [4:0] sext_ln216_35_fu_2510_p1;
wire  signed [4:0] sext_ln216_38_fu_2561_p1;
wire  signed [4:0] sext_ln216_37_fu_2544_p1;
wire  signed [4:0] sext_ln216_40_fu_2595_p1;
wire  signed [4:0] sext_ln216_39_fu_2578_p1;
wire  signed [4:0] sext_ln216_42_fu_2629_p1;
wire  signed [4:0] sext_ln216_41_fu_2612_p1;
wire  signed [4:0] sext_ln216_44_fu_2663_p1;
wire  signed [4:0] sext_ln216_43_fu_2646_p1;
wire  signed [4:0] sext_ln216_46_fu_2697_p1;
wire  signed [4:0] sext_ln216_45_fu_2680_p1;
wire  signed [4:0] sext_ln216_1_fu_1932_p1;
wire  signed [4:0] sext_ln216_2_fu_1949_p1;
wire  signed [4:0] sext_ln216_fu_1915_p1;
wire  signed [4:0] sext_ln216_4_fu_1983_p1;
wire  signed [4:0] sext_ln216_3_fu_1966_p1;
wire  signed [4:0] sext_ln216_6_fu_2017_p1;
wire  signed [4:0] sext_ln216_5_fu_2000_p1;
wire  signed [4:0] sext_ln216_8_fu_2051_p1;
wire  signed [4:0] sext_ln216_7_fu_2034_p1;
wire  signed [4:0] sext_ln216_10_fu_2085_p1;
wire  signed [4:0] sext_ln216_9_fu_2068_p1;
wire  signed [4:0] sext_ln216_12_fu_2119_p1;
wire  signed [4:0] sext_ln216_11_fu_2102_p1;
wire  signed [4:0] sext_ln216_14_fu_2153_p1;
wire  signed [4:0] sext_ln216_13_fu_2136_p1;
wire  signed [4:0] sext_ln216_16_fu_2187_p1;
wire  signed [4:0] sext_ln216_15_fu_2170_p1;
wire  signed [4:0] sext_ln216_18_fu_2221_p1;
wire  signed [4:0] sext_ln216_17_fu_2204_p1;
wire  signed [4:0] sext_ln216_20_fu_2255_p1;
wire  signed [4:0] sext_ln216_19_fu_2238_p1;
wire  signed [4:0] sext_ln216_22_fu_2289_p1;
wire  signed [4:0] sext_ln216_21_fu_2272_p1;
wire  signed [4:0] sext_ln216_24_fu_2323_p1;
wire  signed [4:0] sext_ln216_23_fu_2306_p1;
wire  signed [4:0] sext_ln216_26_fu_2357_p1;
wire  signed [4:0] sext_ln216_25_fu_2340_p1;
wire  signed [4:0] sext_ln216_28_fu_2391_p1;
wire  signed [4:0] sext_ln216_27_fu_2374_p1;
wire  signed [4:0] sext_ln216_30_fu_2425_p1;
wire  signed [4:0] sext_ln216_29_fu_2408_p1;
wire  signed [4:0] sext_ln169_fu_2986_p1;
wire  signed [5:0] sext_ln169_2_fu_3185_p1;
wire  signed [5:0] sext_ln169_1_fu_3182_p1;
wire   [5:0] add_ln169_2_fu_3188_p2;
wire  signed [5:0] sext_ln169_5_fu_3201_p1;
wire  signed [5:0] sext_ln169_4_fu_3198_p1;
wire   [5:0] add_ln169_5_fu_3204_p2;
wire  signed [6:0] sext_ln169_6_fu_3210_p1;
wire  signed [6:0] sext_ln169_3_fu_3194_p1;
wire   [6:0] add_ln169_6_fu_3214_p2;
wire  signed [5:0] sext_ln169_9_fu_3227_p1;
wire  signed [5:0] sext_ln169_8_fu_3224_p1;
wire   [5:0] add_ln169_9_fu_3230_p2;
wire  signed [5:0] sext_ln169_12_fu_3243_p1;
wire  signed [5:0] sext_ln169_11_fu_3240_p1;
wire   [5:0] add_ln169_12_fu_3246_p2;
wire  signed [6:0] sext_ln169_13_fu_3252_p1;
wire  signed [6:0] sext_ln169_10_fu_3236_p1;
wire   [6:0] add_ln169_13_fu_3256_p2;
wire  signed [7:0] sext_ln169_14_fu_3262_p1;
wire  signed [7:0] sext_ln169_7_fu_3220_p1;
wire  signed [5:0] sext_ln169_16_fu_3275_p1;
wire  signed [5:0] sext_ln169_15_fu_3272_p1;
wire   [5:0] add_ln169_17_fu_3278_p2;
wire  signed [5:0] sext_ln169_19_fu_3291_p1;
wire  signed [5:0] sext_ln169_18_fu_3288_p1;
wire   [5:0] add_ln169_20_fu_3294_p2;
wire  signed [6:0] sext_ln169_20_fu_3300_p1;
wire  signed [6:0] sext_ln169_17_fu_3284_p1;
wire   [6:0] add_ln169_21_fu_3304_p2;
wire  signed [5:0] sext_ln169_23_fu_3317_p1;
wire  signed [5:0] sext_ln169_22_fu_3314_p1;
wire   [5:0] add_ln169_24_fu_3320_p2;
wire  signed [5:0] sext_ln169_26_fu_3333_p1;
wire  signed [5:0] sext_ln169_25_fu_3330_p1;
wire   [5:0] add_ln169_27_fu_3336_p2;
wire  signed [6:0] sext_ln169_27_fu_3342_p1;
wire  signed [6:0] sext_ln169_24_fu_3326_p1;
wire   [6:0] add_ln169_28_fu_3346_p2;
wire  signed [7:0] sext_ln169_28_fu_3352_p1;
wire  signed [7:0] sext_ln169_21_fu_3310_p1;
wire  signed [5:0] sext_ln169_30_fu_3365_p1;
wire  signed [5:0] sext_ln169_29_fu_3362_p1;
wire   [5:0] add_ln169_33_fu_3368_p2;
wire  signed [5:0] sext_ln169_33_fu_3381_p1;
wire  signed [5:0] sext_ln169_32_fu_3378_p1;
wire   [5:0] add_ln169_36_fu_3384_p2;
wire  signed [6:0] sext_ln169_34_fu_3390_p1;
wire  signed [6:0] sext_ln169_31_fu_3374_p1;
wire  signed [5:0] sext_ln169_37_fu_3403_p1;
wire  signed [5:0] sext_ln169_36_fu_3400_p1;
wire   [5:0] add_ln169_40_fu_3406_p2;
wire  signed [5:0] sext_ln169_40_fu_3419_p1;
wire  signed [5:0] sext_ln169_39_fu_3416_p1;
wire   [5:0] add_ln169_43_fu_3422_p2;
wire  signed [6:0] sext_ln169_41_fu_3428_p1;
wire  signed [6:0] sext_ln169_38_fu_3412_p1;
wire  signed [5:0] sext_ln169_44_fu_3441_p1;
wire  signed [5:0] sext_ln169_43_fu_3438_p1;
wire   [5:0] add_ln169_48_fu_3444_p2;
wire  signed [5:0] sext_ln169_47_fu_3457_p1;
wire  signed [5:0] sext_ln169_46_fu_3454_p1;
wire   [5:0] add_ln169_51_fu_3460_p2;
wire  signed [6:0] sext_ln169_48_fu_3466_p1;
wire  signed [6:0] sext_ln169_45_fu_3450_p1;
wire   [6:0] add_ln169_52_fu_3470_p2;
wire  signed [5:0] sext_ln169_51_fu_3483_p1;
wire  signed [5:0] sext_ln169_50_fu_3480_p1;
wire   [5:0] add_ln169_55_fu_3486_p2;
wire  signed [5:0] sext_ln169_54_fu_3499_p1;
wire  signed [5:0] sext_ln169_53_fu_3496_p1;
wire   [5:0] add_ln169_58_fu_3502_p2;
wire  signed [6:0] sext_ln169_55_fu_3508_p1;
wire  signed [6:0] sext_ln169_52_fu_3492_p1;
wire   [6:0] add_ln169_59_fu_3512_p2;
wire  signed [7:0] sext_ln169_56_fu_3518_p1;
wire  signed [7:0] sext_ln169_49_fu_3476_p1;
wire  signed [7:0] sext_ln169_42_fu_3535_p1;
wire  signed [7:0] sext_ln169_35_fu_3532_p1;
wire   [7:0] add_ln169_45_fu_3538_p2;
wire   [7:0] add_ln169_61_fu_3544_p2;
wire   [7:0] add_ln169_30_fu_3528_p2;
wire   [7:0] zext_ln108_fu_3555_p1;
wire   [0:0] icmp_ln108_fu_3558_p2;
wire   [0:0] result_fu_3563_p2;
wire   [7:0] zext_ln108_1_fu_3573_p1;
wire   [0:0] icmp_ln108_1_fu_3576_p2;
wire   [0:0] xor_ln108_fu_3581_p2;
wire   [7:0] zext_ln108_2_fu_3591_p1;
wire   [0:0] icmp_ln108_2_fu_3594_p2;
wire   [0:0] xor_ln108_1_fu_3599_p2;
wire   [1:0] zext_ln218_2_fu_3569_p1;
wire   [1:0] zext_ln218_1_fu_3605_p1;
wire   [1:0] add_ln218_fu_3609_p2;
wire   [1:0] zext_ln218_fu_3587_p1;
wire   [1:0] result_2_fu_3615_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
wire    ap_start_int;
wire   [3:0] mul_ln115_10_fu_2079_p00;
wire   [3:0] mul_ln115_11_fu_2096_p00;
wire   [3:0] mul_ln115_12_fu_2113_p00;
wire   [3:0] mul_ln115_13_fu_2130_p00;
wire   [3:0] mul_ln115_14_fu_2147_p00;
wire   [3:0] mul_ln115_15_fu_2164_p00;
wire   [3:0] mul_ln115_16_fu_2181_p00;
wire   [3:0] mul_ln115_17_fu_2198_p00;
wire   [3:0] mul_ln115_18_fu_2215_p00;
wire   [3:0] mul_ln115_19_fu_2232_p00;
wire   [3:0] mul_ln115_1_fu_1926_p00;
wire   [3:0] mul_ln115_20_fu_2249_p00;
wire   [3:0] mul_ln115_21_fu_2266_p00;
wire   [3:0] mul_ln115_22_fu_2283_p00;
wire   [3:0] mul_ln115_23_fu_2300_p00;
wire   [3:0] mul_ln115_24_fu_2317_p00;
wire   [3:0] mul_ln115_25_fu_2334_p00;
wire   [3:0] mul_ln115_26_fu_2351_p00;
wire   [3:0] mul_ln115_27_fu_2368_p00;
wire   [3:0] mul_ln115_28_fu_2385_p00;
wire   [3:0] mul_ln115_29_fu_2402_p00;
wire   [3:0] mul_ln115_2_fu_1943_p00;
wire   [3:0] mul_ln115_30_fu_2419_p00;
wire   [3:0] mul_ln115_31_fu_2436_p00;
wire   [3:0] mul_ln115_32_fu_2453_p00;
wire   [3:0] mul_ln115_33_fu_2470_p00;
wire   [3:0] mul_ln115_34_fu_2487_p00;
wire   [3:0] mul_ln115_35_fu_2504_p00;
wire   [3:0] mul_ln115_36_fu_2521_p00;
wire   [3:0] mul_ln115_37_fu_2538_p00;
wire   [3:0] mul_ln115_38_fu_2555_p00;
wire   [3:0] mul_ln115_39_fu_2572_p00;
wire   [3:0] mul_ln115_3_fu_1960_p00;
wire   [3:0] mul_ln115_40_fu_2589_p00;
wire   [3:0] mul_ln115_41_fu_2606_p00;
wire   [3:0] mul_ln115_42_fu_2623_p00;
wire   [3:0] mul_ln115_43_fu_2640_p00;
wire   [3:0] mul_ln115_44_fu_2657_p00;
wire   [3:0] mul_ln115_45_fu_2674_p00;
wire   [3:0] mul_ln115_46_fu_2691_p00;
wire   [3:0] mul_ln115_47_fu_2708_p00;
wire   [3:0] mul_ln115_48_fu_2725_p00;
wire   [3:0] mul_ln115_49_fu_2742_p00;
wire   [3:0] mul_ln115_4_fu_1977_p00;
wire   [3:0] mul_ln115_50_fu_2759_p00;
wire   [3:0] mul_ln115_51_fu_2776_p00;
wire   [3:0] mul_ln115_52_fu_2793_p00;
wire   [3:0] mul_ln115_53_fu_2810_p00;
wire   [3:0] mul_ln115_54_fu_2827_p00;
wire   [3:0] mul_ln115_55_fu_2844_p00;
wire   [3:0] mul_ln115_56_fu_2861_p00;
wire   [3:0] mul_ln115_57_fu_2878_p00;
wire   [3:0] mul_ln115_58_fu_2895_p00;
wire   [3:0] mul_ln115_59_fu_2912_p00;
wire   [3:0] mul_ln115_5_fu_1994_p00;
wire   [3:0] mul_ln115_60_fu_2929_p00;
wire   [3:0] mul_ln115_61_fu_2946_p00;
wire   [3:0] mul_ln115_62_fu_2963_p00;
wire   [3:0] mul_ln115_63_fu_2980_p00;
wire   [3:0] mul_ln115_6_fu_2011_p00;
wire   [3:0] mul_ln115_7_fu_2028_p00;
wire   [3:0] mul_ln115_8_fu_2045_p00;
wire   [3:0] mul_ln115_9_fu_2062_p00;
wire   [3:0] mul_ln115_fu_1909_p00;
reg    ap_condition_120;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 tile_fu_444 = 32'd0;
#0 nf_1_fu_448 = 32'd0;
#0 i_fu_452 = 7'd0;
#0 arrayidx3_0_0_0_load22_fu_456 = 128'd0;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_Matrix_Vector_Activate_Batch_weights_39_ROM_AUTO_1R #(
    .DataWidth( 128 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
weights_39_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights_39_address0),
    .ce0(weights_39_ce0),
    .q0(weights_39_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U1(
    .din0(mul_ln115_fu_1909_p0),
    .din1(local_temp_fu_1268_p1),
    .dout(mul_ln115_fu_1909_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln115_1_fu_1926_p0),
    .din1(local_temp_1_fu_1272_p4),
    .dout(mul_ln115_1_fu_1926_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(mul_ln115_2_fu_1943_p0),
    .din1(local_temp_2_fu_1282_p4),
    .dout(mul_ln115_2_fu_1943_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(mul_ln115_3_fu_1960_p0),
    .din1(local_temp_3_fu_1292_p4),
    .dout(mul_ln115_3_fu_1960_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U5(
    .din0(mul_ln115_4_fu_1977_p0),
    .din1(local_temp_4_fu_1302_p4),
    .dout(mul_ln115_4_fu_1977_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U6(
    .din0(mul_ln115_5_fu_1994_p0),
    .din1(local_temp_5_fu_1312_p4),
    .dout(mul_ln115_5_fu_1994_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U7(
    .din0(mul_ln115_6_fu_2011_p0),
    .din1(local_temp_6_fu_1322_p4),
    .dout(mul_ln115_6_fu_2011_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U8(
    .din0(mul_ln115_7_fu_2028_p0),
    .din1(local_temp_7_fu_1332_p4),
    .dout(mul_ln115_7_fu_2028_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U9(
    .din0(mul_ln115_8_fu_2045_p0),
    .din1(local_temp_8_fu_1342_p4),
    .dout(mul_ln115_8_fu_2045_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U10(
    .din0(mul_ln115_9_fu_2062_p0),
    .din1(local_temp_9_fu_1352_p4),
    .dout(mul_ln115_9_fu_2062_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U11(
    .din0(mul_ln115_10_fu_2079_p0),
    .din1(local_temp_10_fu_1362_p4),
    .dout(mul_ln115_10_fu_2079_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U12(
    .din0(mul_ln115_11_fu_2096_p0),
    .din1(local_temp_11_fu_1372_p4),
    .dout(mul_ln115_11_fu_2096_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U13(
    .din0(mul_ln115_12_fu_2113_p0),
    .din1(local_temp_12_fu_1382_p4),
    .dout(mul_ln115_12_fu_2113_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U14(
    .din0(mul_ln115_13_fu_2130_p0),
    .din1(local_temp_13_fu_1392_p4),
    .dout(mul_ln115_13_fu_2130_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U15(
    .din0(mul_ln115_14_fu_2147_p0),
    .din1(local_temp_14_fu_1402_p4),
    .dout(mul_ln115_14_fu_2147_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U16(
    .din0(mul_ln115_15_fu_2164_p0),
    .din1(local_temp_15_fu_1412_p4),
    .dout(mul_ln115_15_fu_2164_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U17(
    .din0(mul_ln115_16_fu_2181_p0),
    .din1(local_temp_16_fu_1422_p4),
    .dout(mul_ln115_16_fu_2181_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U18(
    .din0(mul_ln115_17_fu_2198_p0),
    .din1(local_temp_17_fu_1432_p4),
    .dout(mul_ln115_17_fu_2198_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U19(
    .din0(mul_ln115_18_fu_2215_p0),
    .din1(local_temp_18_fu_1442_p4),
    .dout(mul_ln115_18_fu_2215_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U20(
    .din0(mul_ln115_19_fu_2232_p0),
    .din1(local_temp_19_fu_1452_p4),
    .dout(mul_ln115_19_fu_2232_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U21(
    .din0(mul_ln115_20_fu_2249_p0),
    .din1(local_temp_20_fu_1462_p4),
    .dout(mul_ln115_20_fu_2249_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U22(
    .din0(mul_ln115_21_fu_2266_p0),
    .din1(local_temp_21_fu_1472_p4),
    .dout(mul_ln115_21_fu_2266_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U23(
    .din0(mul_ln115_22_fu_2283_p0),
    .din1(local_temp_22_fu_1482_p4),
    .dout(mul_ln115_22_fu_2283_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U24(
    .din0(mul_ln115_23_fu_2300_p0),
    .din1(local_temp_23_fu_1492_p4),
    .dout(mul_ln115_23_fu_2300_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U25(
    .din0(mul_ln115_24_fu_2317_p0),
    .din1(local_temp_24_fu_1502_p4),
    .dout(mul_ln115_24_fu_2317_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U26(
    .din0(mul_ln115_25_fu_2334_p0),
    .din1(local_temp_25_fu_1512_p4),
    .dout(mul_ln115_25_fu_2334_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U27(
    .din0(mul_ln115_26_fu_2351_p0),
    .din1(local_temp_26_fu_1522_p4),
    .dout(mul_ln115_26_fu_2351_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U28(
    .din0(mul_ln115_27_fu_2368_p0),
    .din1(local_temp_27_fu_1532_p4),
    .dout(mul_ln115_27_fu_2368_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U29(
    .din0(mul_ln115_28_fu_2385_p0),
    .din1(local_temp_28_fu_1542_p4),
    .dout(mul_ln115_28_fu_2385_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U30(
    .din0(mul_ln115_29_fu_2402_p0),
    .din1(local_temp_29_fu_1552_p4),
    .dout(mul_ln115_29_fu_2402_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U31(
    .din0(mul_ln115_30_fu_2419_p0),
    .din1(local_temp_30_fu_1562_p4),
    .dout(mul_ln115_30_fu_2419_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U32(
    .din0(mul_ln115_31_fu_2436_p0),
    .din1(local_temp_31_fu_1572_p4),
    .dout(mul_ln115_31_fu_2436_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U33(
    .din0(mul_ln115_32_fu_2453_p0),
    .din1(local_temp_32_fu_1582_p4),
    .dout(mul_ln115_32_fu_2453_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U34(
    .din0(mul_ln115_33_fu_2470_p0),
    .din1(local_temp_33_fu_1592_p4),
    .dout(mul_ln115_33_fu_2470_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U35(
    .din0(mul_ln115_34_fu_2487_p0),
    .din1(local_temp_34_fu_1602_p4),
    .dout(mul_ln115_34_fu_2487_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U36(
    .din0(mul_ln115_35_fu_2504_p0),
    .din1(local_temp_35_fu_1612_p4),
    .dout(mul_ln115_35_fu_2504_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U37(
    .din0(mul_ln115_36_fu_2521_p0),
    .din1(local_temp_36_fu_1622_p4),
    .dout(mul_ln115_36_fu_2521_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U38(
    .din0(mul_ln115_37_fu_2538_p0),
    .din1(local_temp_37_fu_1632_p4),
    .dout(mul_ln115_37_fu_2538_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U39(
    .din0(mul_ln115_38_fu_2555_p0),
    .din1(local_temp_38_fu_1642_p4),
    .dout(mul_ln115_38_fu_2555_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U40(
    .din0(mul_ln115_39_fu_2572_p0),
    .din1(local_temp_39_fu_1652_p4),
    .dout(mul_ln115_39_fu_2572_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U41(
    .din0(mul_ln115_40_fu_2589_p0),
    .din1(local_temp_40_fu_1662_p4),
    .dout(mul_ln115_40_fu_2589_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U42(
    .din0(mul_ln115_41_fu_2606_p0),
    .din1(local_temp_41_fu_1672_p4),
    .dout(mul_ln115_41_fu_2606_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U43(
    .din0(mul_ln115_42_fu_2623_p0),
    .din1(local_temp_42_fu_1682_p4),
    .dout(mul_ln115_42_fu_2623_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U44(
    .din0(mul_ln115_43_fu_2640_p0),
    .din1(local_temp_43_fu_1692_p4),
    .dout(mul_ln115_43_fu_2640_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U45(
    .din0(mul_ln115_44_fu_2657_p0),
    .din1(local_temp_44_fu_1702_p4),
    .dout(mul_ln115_44_fu_2657_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U46(
    .din0(mul_ln115_45_fu_2674_p0),
    .din1(local_temp_45_fu_1712_p4),
    .dout(mul_ln115_45_fu_2674_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U47(
    .din0(mul_ln115_46_fu_2691_p0),
    .din1(local_temp_46_fu_1722_p4),
    .dout(mul_ln115_46_fu_2691_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U48(
    .din0(mul_ln115_47_fu_2708_p0),
    .din1(local_temp_47_fu_1732_p4),
    .dout(mul_ln115_47_fu_2708_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U49(
    .din0(mul_ln115_48_fu_2725_p0),
    .din1(local_temp_48_fu_1742_p4),
    .dout(mul_ln115_48_fu_2725_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U50(
    .din0(mul_ln115_49_fu_2742_p0),
    .din1(local_temp_49_fu_1752_p4),
    .dout(mul_ln115_49_fu_2742_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U51(
    .din0(mul_ln115_50_fu_2759_p0),
    .din1(local_temp_50_fu_1762_p4),
    .dout(mul_ln115_50_fu_2759_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U52(
    .din0(mul_ln115_51_fu_2776_p0),
    .din1(local_temp_51_fu_1772_p4),
    .dout(mul_ln115_51_fu_2776_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U53(
    .din0(mul_ln115_52_fu_2793_p0),
    .din1(local_temp_52_fu_1782_p4),
    .dout(mul_ln115_52_fu_2793_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U54(
    .din0(mul_ln115_53_fu_2810_p0),
    .din1(local_temp_53_fu_1792_p4),
    .dout(mul_ln115_53_fu_2810_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U55(
    .din0(mul_ln115_54_fu_2827_p0),
    .din1(local_temp_54_fu_1802_p4),
    .dout(mul_ln115_54_fu_2827_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U56(
    .din0(mul_ln115_55_fu_2844_p0),
    .din1(local_temp_55_fu_1812_p4),
    .dout(mul_ln115_55_fu_2844_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U57(
    .din0(mul_ln115_56_fu_2861_p0),
    .din1(local_temp_56_fu_1822_p4),
    .dout(mul_ln115_56_fu_2861_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U58(
    .din0(mul_ln115_57_fu_2878_p0),
    .din1(local_temp_57_fu_1832_p4),
    .dout(mul_ln115_57_fu_2878_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U59(
    .din0(mul_ln115_58_fu_2895_p0),
    .din1(local_temp_58_fu_1842_p4),
    .dout(mul_ln115_58_fu_2895_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U60(
    .din0(mul_ln115_59_fu_2912_p0),
    .din1(local_temp_59_fu_1852_p4),
    .dout(mul_ln115_59_fu_2912_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U61(
    .din0(mul_ln115_60_fu_2929_p0),
    .din1(local_temp_60_fu_1862_p4),
    .dout(mul_ln115_60_fu_2929_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U62(
    .din0(mul_ln115_61_fu_2946_p0),
    .din1(local_temp_61_fu_1872_p4),
    .dout(mul_ln115_61_fu_2946_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U63(
    .din0(mul_ln115_62_fu_2963_p0),
    .din1(local_temp_62_fu_1882_p4),
    .dout(mul_ln115_62_fu_2963_p2)
);

MatrixVectorActivation_1_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U64(
    .din0(mul_ln115_63_fu_2980_p0),
    .din1(local_temp_63_fu_1892_p4),
    .dout(mul_ln115_63_fu_2980_p2)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_120)) begin
        if ((icmp_ln123_fu_546_p2 == 1'd0)) begin
            i_fu_452 <= i_2_fu_552_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_452 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_120)) begin
        if ((icmp_ln123_fu_546_p2 == 1'd0)) begin
            nf_1_fu_448 <= nf_4_fu_581_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_448 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        tile_fu_444 <= 32'd0;
    end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln123_reg_3658_pp0_iter0_reg == 1'd0))) begin
        tile_fu_444 <= tile_2_fu_1256_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        add_ln169_10_reg_4040 <= add_ln169_10_fu_3026_p2;
        add_ln169_11_reg_4045 <= add_ln169_11_fu_3032_p2;
        add_ln169_15_reg_4050 <= add_ln169_15_fu_3038_p2;
        add_ln169_16_reg_4055 <= add_ln169_16_fu_3044_p2;
        add_ln169_18_reg_4060 <= add_ln169_18_fu_3050_p2;
        add_ln169_19_reg_4065 <= add_ln169_19_fu_3056_p2;
        add_ln169_1_reg_4015 <= add_ln169_1_fu_2996_p2;
        add_ln169_22_reg_4070 <= add_ln169_22_fu_3062_p2;
        add_ln169_23_reg_4075 <= add_ln169_23_fu_3068_p2;
        add_ln169_25_reg_4080 <= add_ln169_25_fu_3074_p2;
        add_ln169_26_reg_4085 <= add_ln169_26_fu_3080_p2;
        add_ln169_31_reg_4090 <= add_ln169_31_fu_3086_p2;
        add_ln169_32_reg_4095 <= add_ln169_32_fu_3092_p2;
        add_ln169_34_reg_4100 <= add_ln169_34_fu_3098_p2;
        add_ln169_35_reg_4105 <= add_ln169_35_fu_3104_p2;
        add_ln169_38_reg_4110 <= add_ln169_38_fu_3110_p2;
        add_ln169_39_reg_4115 <= add_ln169_39_fu_3116_p2;
        add_ln169_3_reg_4020 <= add_ln169_3_fu_3002_p2;
        add_ln169_41_reg_4120 <= add_ln169_41_fu_3122_p2;
        add_ln169_42_reg_4125 <= add_ln169_42_fu_3128_p2;
        add_ln169_46_reg_4130 <= add_ln169_46_fu_3134_p2;
        add_ln169_47_reg_4135 <= add_ln169_47_fu_3140_p2;
        add_ln169_49_reg_4140 <= add_ln169_49_fu_3146_p2;
        add_ln169_4_reg_4025 <= add_ln169_4_fu_3008_p2;
        add_ln169_50_reg_4145 <= add_ln169_50_fu_3152_p2;
        add_ln169_53_reg_4150 <= add_ln169_53_fu_3158_p2;
        add_ln169_54_reg_4155 <= add_ln169_54_fu_3164_p2;
        add_ln169_56_reg_4160 <= add_ln169_56_fu_3170_p2;
        add_ln169_57_reg_4165 <= add_ln169_57_fu_3176_p2;
        add_ln169_7_reg_4030 <= add_ln169_7_fu_3014_p2;
        add_ln169_8_reg_4035 <= add_ln169_8_fu_3020_p2;
        add_ln169_reg_4010 <= add_ln169_fu_2990_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln123_reg_3658_pp0_iter2_reg <= icmp_ln123_reg_3658_pp0_iter1_reg;
        p_ZL7threshs_0_load_reg_4170 <= p_ZL7threshs_0_q0;
        p_ZL7threshs_1_load_reg_4175 <= p_ZL7threshs_1_q0;
        p_ZL7threshs_2_load_reg_4180 <= p_ZL7threshs_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        add_ln169_14_reg_4185 <= add_ln169_14_fu_3266_p2;
        add_ln169_29_reg_4190 <= add_ln169_29_fu_3356_p2;
        add_ln169_37_reg_4195 <= add_ln169_37_fu_3394_p2;
        add_ln169_44_reg_4200 <= add_ln169_44_fu_3432_p2;
        add_ln169_60_reg_4205 <= add_ln169_60_fu_3522_p2;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln123_reg_3658_pp0_iter3_reg <= icmp_ln123_reg_3658_pp0_iter2_reg;
        p_ZL7threshs_0_load_reg_4170_pp0_iter3_reg <= p_ZL7threshs_0_load_reg_4170;
        p_ZL7threshs_1_load_reg_4175_pp0_iter3_reg <= p_ZL7threshs_1_load_reg_4175;
        p_ZL7threshs_2_load_reg_4180_pp0_iter3_reg <= p_ZL7threshs_2_load_reg_4180;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        add_ln169_62_reg_4210 <= add_ln169_62_fu_3549_p2;
        icmp_ln123_reg_3658_pp0_iter4_reg <= icmp_ln123_reg_3658_pp0_iter3_reg;
        p_ZL7threshs_0_load_reg_4170_pp0_iter4_reg <= p_ZL7threshs_0_load_reg_4170_pp0_iter3_reg;
        p_ZL7threshs_1_load_reg_4175_pp0_iter4_reg <= p_ZL7threshs_1_load_reg_4175_pp0_iter3_reg;
        p_ZL7threshs_2_load_reg_4180_pp0_iter4_reg <= p_ZL7threshs_2_load_reg_4180_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln123_reg_3658 <= icmp_ln123_fu_546_p2;
        icmp_ln174_reg_3665 <= icmp_ln174_fu_575_p2;
        nf_3_reg_3653 <= ap_sig_allocacmp_nf_3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln123_reg_3658_pp0_iter1_reg <= icmp_ln123_reg_3658;
        r_10_reg_3725 <= {{arrayidx3_0_0_0_load22_fu_456[21:20]}};
        r_11_reg_3730 <= {{arrayidx3_0_0_0_load22_fu_456[23:22]}};
        r_12_reg_3735 <= {{arrayidx3_0_0_0_load22_fu_456[25:24]}};
        r_13_reg_3740 <= {{arrayidx3_0_0_0_load22_fu_456[27:26]}};
        r_14_reg_3745 <= {{arrayidx3_0_0_0_load22_fu_456[29:28]}};
        r_15_reg_3750 <= {{arrayidx3_0_0_0_load22_fu_456[31:30]}};
        r_16_reg_3755 <= {{arrayidx3_0_0_0_load22_fu_456[33:32]}};
        r_17_reg_3760 <= {{arrayidx3_0_0_0_load22_fu_456[35:34]}};
        r_18_reg_3765 <= {{arrayidx3_0_0_0_load22_fu_456[37:36]}};
        r_19_reg_3770 <= {{arrayidx3_0_0_0_load22_fu_456[39:38]}};
        r_1_reg_3680 <= {{arrayidx3_0_0_0_load22_fu_456[3:2]}};
        r_20_reg_3775 <= {{arrayidx3_0_0_0_load22_fu_456[41:40]}};
        r_21_reg_3780 <= {{arrayidx3_0_0_0_load22_fu_456[43:42]}};
        r_22_reg_3785 <= {{arrayidx3_0_0_0_load22_fu_456[45:44]}};
        r_23_reg_3790 <= {{arrayidx3_0_0_0_load22_fu_456[47:46]}};
        r_24_reg_3795 <= {{arrayidx3_0_0_0_load22_fu_456[49:48]}};
        r_25_reg_3800 <= {{arrayidx3_0_0_0_load22_fu_456[51:50]}};
        r_26_reg_3805 <= {{arrayidx3_0_0_0_load22_fu_456[53:52]}};
        r_27_reg_3810 <= {{arrayidx3_0_0_0_load22_fu_456[55:54]}};
        r_28_reg_3815 <= {{arrayidx3_0_0_0_load22_fu_456[57:56]}};
        r_29_reg_3820 <= {{arrayidx3_0_0_0_load22_fu_456[59:58]}};
        r_2_reg_3685 <= {{arrayidx3_0_0_0_load22_fu_456[5:4]}};
        r_30_reg_3825 <= {{arrayidx3_0_0_0_load22_fu_456[61:60]}};
        r_31_reg_3830 <= {{arrayidx3_0_0_0_load22_fu_456[63:62]}};
        r_32_reg_3835 <= {{arrayidx3_0_0_0_load22_fu_456[65:64]}};
        r_33_reg_3840 <= {{arrayidx3_0_0_0_load22_fu_456[67:66]}};
        r_34_reg_3845 <= {{arrayidx3_0_0_0_load22_fu_456[69:68]}};
        r_35_reg_3850 <= {{arrayidx3_0_0_0_load22_fu_456[71:70]}};
        r_36_reg_3855 <= {{arrayidx3_0_0_0_load22_fu_456[73:72]}};
        r_37_reg_3860 <= {{arrayidx3_0_0_0_load22_fu_456[75:74]}};
        r_38_reg_3865 <= {{arrayidx3_0_0_0_load22_fu_456[77:76]}};
        r_39_reg_3870 <= {{arrayidx3_0_0_0_load22_fu_456[79:78]}};
        r_3_reg_3690 <= {{arrayidx3_0_0_0_load22_fu_456[7:6]}};
        r_40_reg_3875 <= {{arrayidx3_0_0_0_load22_fu_456[81:80]}};
        r_41_reg_3880 <= {{arrayidx3_0_0_0_load22_fu_456[83:82]}};
        r_42_reg_3885 <= {{arrayidx3_0_0_0_load22_fu_456[85:84]}};
        r_43_reg_3890 <= {{arrayidx3_0_0_0_load22_fu_456[87:86]}};
        r_44_reg_3895 <= {{arrayidx3_0_0_0_load22_fu_456[89:88]}};
        r_45_reg_3900 <= {{arrayidx3_0_0_0_load22_fu_456[91:90]}};
        r_46_reg_3905 <= {{arrayidx3_0_0_0_load22_fu_456[93:92]}};
        r_47_reg_3910 <= {{arrayidx3_0_0_0_load22_fu_456[95:94]}};
        r_48_reg_3915 <= {{arrayidx3_0_0_0_load22_fu_456[97:96]}};
        r_49_reg_3920 <= {{arrayidx3_0_0_0_load22_fu_456[99:98]}};
        r_4_reg_3695 <= {{arrayidx3_0_0_0_load22_fu_456[9:8]}};
        r_50_reg_3925 <= {{arrayidx3_0_0_0_load22_fu_456[101:100]}};
        r_51_reg_3930 <= {{arrayidx3_0_0_0_load22_fu_456[103:102]}};
        r_52_reg_3935 <= {{arrayidx3_0_0_0_load22_fu_456[105:104]}};
        r_53_reg_3940 <= {{arrayidx3_0_0_0_load22_fu_456[107:106]}};
        r_54_reg_3945 <= {{arrayidx3_0_0_0_load22_fu_456[109:108]}};
        r_55_reg_3950 <= {{arrayidx3_0_0_0_load22_fu_456[111:110]}};
        r_56_reg_3955 <= {{arrayidx3_0_0_0_load22_fu_456[113:112]}};
        r_57_reg_3960 <= {{arrayidx3_0_0_0_load22_fu_456[115:114]}};
        r_58_reg_3965 <= {{arrayidx3_0_0_0_load22_fu_456[117:116]}};
        r_59_reg_3970 <= {{arrayidx3_0_0_0_load22_fu_456[119:118]}};
        r_5_reg_3700 <= {{arrayidx3_0_0_0_load22_fu_456[11:10]}};
        r_60_reg_3975 <= {{arrayidx3_0_0_0_load22_fu_456[121:120]}};
        r_61_reg_3980 <= {{arrayidx3_0_0_0_load22_fu_456[123:122]}};
        r_62_reg_3985 <= {{arrayidx3_0_0_0_load22_fu_456[125:124]}};
        r_63_reg_3990 <= {{arrayidx3_0_0_0_load22_fu_456[127:126]}};
        r_6_reg_3705 <= {{arrayidx3_0_0_0_load22_fu_456[13:12]}};
        r_7_reg_3710 <= {{arrayidx3_0_0_0_load22_fu_456[15:14]}};
        r_8_reg_3715 <= {{arrayidx3_0_0_0_load22_fu_456[17:16]}};
        r_9_reg_3720 <= {{arrayidx3_0_0_0_load22_fu_456[19:18]}};
        r_reg_3675 <= r_fu_610_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln126_fu_558_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln123_fu_546_p2 == 1'd0))) begin
        arrayidx3_0_0_0_load22_fu_456 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln123_fu_546_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_452;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_3 = nf_1_fu_448;
    end
end

always @ (*) begin
    if (((ap_predicate_op29_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln123_reg_3658_pp0_iter4_reg == 1'd0))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln123_reg_3658_pp0_iter4_reg == 1'd0))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        weights_39_ce0 = 1'b1;
    end else begin
        weights_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else if (((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln123_reg_3658_pp0_iter4_reg == 1'd1)))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

assign add_ln169_10_fu_3026_p2 = ($signed(sext_ln216_52_fu_2799_p1) + $signed(sext_ln216_51_fu_2782_p1));

assign add_ln169_11_fu_3032_p2 = ($signed(sext_ln216_54_fu_2833_p1) + $signed(sext_ln216_53_fu_2816_p1));

assign add_ln169_12_fu_3246_p2 = ($signed(sext_ln169_12_fu_3243_p1) + $signed(sext_ln169_11_fu_3240_p1));

assign add_ln169_13_fu_3256_p2 = ($signed(sext_ln169_13_fu_3252_p1) + $signed(sext_ln169_10_fu_3236_p1));

assign add_ln169_14_fu_3266_p2 = ($signed(sext_ln169_14_fu_3262_p1) + $signed(sext_ln169_7_fu_3220_p1));

assign add_ln169_15_fu_3038_p2 = ($signed(sext_ln216_32_fu_2459_p1) + $signed(sext_ln216_31_fu_2442_p1));

assign add_ln169_16_fu_3044_p2 = ($signed(sext_ln216_34_fu_2493_p1) + $signed(sext_ln216_33_fu_2476_p1));

assign add_ln169_17_fu_3278_p2 = ($signed(sext_ln169_16_fu_3275_p1) + $signed(sext_ln169_15_fu_3272_p1));

assign add_ln169_18_fu_3050_p2 = ($signed(sext_ln216_36_fu_2527_p1) + $signed(sext_ln216_35_fu_2510_p1));

assign add_ln169_19_fu_3056_p2 = ($signed(sext_ln216_38_fu_2561_p1) + $signed(sext_ln216_37_fu_2544_p1));

assign add_ln169_1_fu_2996_p2 = ($signed(sext_ln216_60_fu_2935_p1) + $signed(sext_ln216_59_fu_2918_p1));

assign add_ln169_20_fu_3294_p2 = ($signed(sext_ln169_19_fu_3291_p1) + $signed(sext_ln169_18_fu_3288_p1));

assign add_ln169_21_fu_3304_p2 = ($signed(sext_ln169_20_fu_3300_p1) + $signed(sext_ln169_17_fu_3284_p1));

assign add_ln169_22_fu_3062_p2 = ($signed(sext_ln216_40_fu_2595_p1) + $signed(sext_ln216_39_fu_2578_p1));

assign add_ln169_23_fu_3068_p2 = ($signed(sext_ln216_42_fu_2629_p1) + $signed(sext_ln216_41_fu_2612_p1));

assign add_ln169_24_fu_3320_p2 = ($signed(sext_ln169_23_fu_3317_p1) + $signed(sext_ln169_22_fu_3314_p1));

assign add_ln169_25_fu_3074_p2 = ($signed(sext_ln216_44_fu_2663_p1) + $signed(sext_ln216_43_fu_2646_p1));

assign add_ln169_26_fu_3080_p2 = ($signed(sext_ln216_46_fu_2697_p1) + $signed(sext_ln216_45_fu_2680_p1));

assign add_ln169_27_fu_3336_p2 = ($signed(sext_ln169_26_fu_3333_p1) + $signed(sext_ln169_25_fu_3330_p1));

assign add_ln169_28_fu_3346_p2 = ($signed(sext_ln169_27_fu_3342_p1) + $signed(sext_ln169_24_fu_3326_p1));

assign add_ln169_29_fu_3356_p2 = ($signed(sext_ln169_28_fu_3352_p1) + $signed(sext_ln169_21_fu_3310_p1));

assign add_ln169_2_fu_3188_p2 = ($signed(sext_ln169_2_fu_3185_p1) + $signed(sext_ln169_1_fu_3182_p1));

assign add_ln169_30_fu_3528_p2 = (add_ln169_29_reg_4190 + add_ln169_14_reg_4185);

assign add_ln169_31_fu_3086_p2 = ($signed(sext_ln216_1_fu_1932_p1) + $signed(sext_ln216_2_fu_1949_p1));

assign add_ln169_32_fu_3092_p2 = ($signed(sext_ln216_fu_1915_p1) + $signed(sext_ln216_4_fu_1983_p1));

assign add_ln169_33_fu_3368_p2 = ($signed(sext_ln169_30_fu_3365_p1) + $signed(sext_ln169_29_fu_3362_p1));

assign add_ln169_34_fu_3098_p2 = ($signed(sext_ln216_3_fu_1966_p1) + $signed(sext_ln216_6_fu_2017_p1));

assign add_ln169_35_fu_3104_p2 = ($signed(sext_ln216_5_fu_2000_p1) + $signed(sext_ln216_8_fu_2051_p1));

assign add_ln169_36_fu_3384_p2 = ($signed(sext_ln169_33_fu_3381_p1) + $signed(sext_ln169_32_fu_3378_p1));

assign add_ln169_37_fu_3394_p2 = ($signed(sext_ln169_34_fu_3390_p1) + $signed(sext_ln169_31_fu_3374_p1));

assign add_ln169_38_fu_3110_p2 = ($signed(sext_ln216_7_fu_2034_p1) + $signed(sext_ln216_10_fu_2085_p1));

assign add_ln169_39_fu_3116_p2 = ($signed(sext_ln216_9_fu_2068_p1) + $signed(sext_ln216_12_fu_2119_p1));

assign add_ln169_3_fu_3002_p2 = ($signed(sext_ln216_56_fu_2867_p1) + $signed(sext_ln216_55_fu_2850_p1));

assign add_ln169_40_fu_3406_p2 = ($signed(sext_ln169_37_fu_3403_p1) + $signed(sext_ln169_36_fu_3400_p1));

assign add_ln169_41_fu_3122_p2 = ($signed(sext_ln216_11_fu_2102_p1) + $signed(sext_ln216_14_fu_2153_p1));

assign add_ln169_42_fu_3128_p2 = ($signed(sext_ln216_13_fu_2136_p1) + $signed(sext_ln216_16_fu_2187_p1));

assign add_ln169_43_fu_3422_p2 = ($signed(sext_ln169_40_fu_3419_p1) + $signed(sext_ln169_39_fu_3416_p1));

assign add_ln169_44_fu_3432_p2 = ($signed(sext_ln169_41_fu_3428_p1) + $signed(sext_ln169_38_fu_3412_p1));

assign add_ln169_45_fu_3538_p2 = ($signed(sext_ln169_42_fu_3535_p1) + $signed(sext_ln169_35_fu_3532_p1));

assign add_ln169_46_fu_3134_p2 = ($signed(sext_ln216_15_fu_2170_p1) + $signed(sext_ln216_18_fu_2221_p1));

assign add_ln169_47_fu_3140_p2 = ($signed(sext_ln216_17_fu_2204_p1) + $signed(sext_ln216_20_fu_2255_p1));

assign add_ln169_48_fu_3444_p2 = ($signed(sext_ln169_44_fu_3441_p1) + $signed(sext_ln169_43_fu_3438_p1));

assign add_ln169_49_fu_3146_p2 = ($signed(sext_ln216_19_fu_2238_p1) + $signed(sext_ln216_22_fu_2289_p1));

assign add_ln169_4_fu_3008_p2 = ($signed(sext_ln216_58_fu_2901_p1) + $signed(sext_ln216_57_fu_2884_p1));

assign add_ln169_50_fu_3152_p2 = ($signed(sext_ln216_21_fu_2272_p1) + $signed(sext_ln216_24_fu_2323_p1));

assign add_ln169_51_fu_3460_p2 = ($signed(sext_ln169_47_fu_3457_p1) + $signed(sext_ln169_46_fu_3454_p1));

assign add_ln169_52_fu_3470_p2 = ($signed(sext_ln169_48_fu_3466_p1) + $signed(sext_ln169_45_fu_3450_p1));

assign add_ln169_53_fu_3158_p2 = ($signed(sext_ln216_23_fu_2306_p1) + $signed(sext_ln216_26_fu_2357_p1));

assign add_ln169_54_fu_3164_p2 = ($signed(sext_ln216_25_fu_2340_p1) + $signed(sext_ln216_28_fu_2391_p1));

assign add_ln169_55_fu_3486_p2 = ($signed(sext_ln169_51_fu_3483_p1) + $signed(sext_ln169_50_fu_3480_p1));

assign add_ln169_56_fu_3170_p2 = ($signed(sext_ln216_27_fu_2374_p1) + $signed(sext_ln216_30_fu_2425_p1));

assign add_ln169_57_fu_3176_p2 = ($signed(sext_ln216_29_fu_2408_p1) + $signed(sext_ln169_fu_2986_p1));

assign add_ln169_58_fu_3502_p2 = ($signed(sext_ln169_54_fu_3499_p1) + $signed(sext_ln169_53_fu_3496_p1));

assign add_ln169_59_fu_3512_p2 = ($signed(sext_ln169_55_fu_3508_p1) + $signed(sext_ln169_52_fu_3492_p1));

assign add_ln169_5_fu_3204_p2 = ($signed(sext_ln169_5_fu_3201_p1) + $signed(sext_ln169_4_fu_3198_p1));

assign add_ln169_60_fu_3522_p2 = ($signed(sext_ln169_56_fu_3518_p1) + $signed(sext_ln169_49_fu_3476_p1));

assign add_ln169_61_fu_3544_p2 = (add_ln169_60_reg_4205 + add_ln169_45_fu_3538_p2);

assign add_ln169_62_fu_3549_p2 = (add_ln169_61_fu_3544_p2 + add_ln169_30_fu_3528_p2);

assign add_ln169_6_fu_3214_p2 = ($signed(sext_ln169_6_fu_3210_p1) + $signed(sext_ln169_3_fu_3194_p1));

assign add_ln169_7_fu_3014_p2 = ($signed(sext_ln216_48_fu_2731_p1) + $signed(sext_ln216_47_fu_2714_p1));

assign add_ln169_8_fu_3020_p2 = ($signed(sext_ln216_50_fu_2765_p1) + $signed(sext_ln216_49_fu_2748_p1));

assign add_ln169_9_fu_3230_p2 = ($signed(sext_ln169_9_fu_3227_p1) + $signed(sext_ln169_8_fu_3224_p1));

assign add_ln169_fu_2990_p2 = ($signed(sext_ln216_61_fu_2952_p1) + $signed(sext_ln216_62_fu_2969_p1));

assign add_ln218_fu_3609_p2 = (zext_ln218_2_fu_3569_p1 + zext_ln218_1_fu_3605_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((ap_predicate_op29_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state6_io = ((out_V_TREADY == 1'b0) & (icmp_ln123_reg_3658_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((out_V_TREADY == 1'b0) & (icmp_ln123_reg_3658_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_condition_120 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op29_read_state1 = ((icmp_ln126_fu_558_p2 == 1'd1) & (icmp_ln123_fu_546_p2 == 1'd0));
end

assign i_2_fu_552_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln108_1_fu_3576_p2 = (($signed(add_ln169_62_reg_4210) < $signed(zext_ln108_1_fu_3573_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_2_fu_3594_p2 = (($signed(add_ln169_62_reg_4210) < $signed(zext_ln108_2_fu_3591_p1)) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_3558_p2 = (($signed(add_ln169_62_reg_4210) < $signed(zext_ln108_fu_3555_p1)) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_546_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln123_reg_3658_pp0_iter0_reg = icmp_ln123_reg_3658;

assign icmp_ln126_fu_558_p2 = ((ap_sig_allocacmp_nf_3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_575_p2 = ((nf_fu_569_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i26_fu_605_p1 = tile_fu_444;

assign idxprom2_i_fu_1250_p1 = nf_3_reg_3653;

assign local_temp_10_fu_1362_p4 = {{weights_39_q0[21:20]}};

assign local_temp_11_fu_1372_p4 = {{weights_39_q0[23:22]}};

assign local_temp_12_fu_1382_p4 = {{weights_39_q0[25:24]}};

assign local_temp_13_fu_1392_p4 = {{weights_39_q0[27:26]}};

assign local_temp_14_fu_1402_p4 = {{weights_39_q0[29:28]}};

assign local_temp_15_fu_1412_p4 = {{weights_39_q0[31:30]}};

assign local_temp_16_fu_1422_p4 = {{weights_39_q0[33:32]}};

assign local_temp_17_fu_1432_p4 = {{weights_39_q0[35:34]}};

assign local_temp_18_fu_1442_p4 = {{weights_39_q0[37:36]}};

assign local_temp_19_fu_1452_p4 = {{weights_39_q0[39:38]}};

assign local_temp_1_fu_1272_p4 = {{weights_39_q0[3:2]}};

assign local_temp_20_fu_1462_p4 = {{weights_39_q0[41:40]}};

assign local_temp_21_fu_1472_p4 = {{weights_39_q0[43:42]}};

assign local_temp_22_fu_1482_p4 = {{weights_39_q0[45:44]}};

assign local_temp_23_fu_1492_p4 = {{weights_39_q0[47:46]}};

assign local_temp_24_fu_1502_p4 = {{weights_39_q0[49:48]}};

assign local_temp_25_fu_1512_p4 = {{weights_39_q0[51:50]}};

assign local_temp_26_fu_1522_p4 = {{weights_39_q0[53:52]}};

assign local_temp_27_fu_1532_p4 = {{weights_39_q0[55:54]}};

assign local_temp_28_fu_1542_p4 = {{weights_39_q0[57:56]}};

assign local_temp_29_fu_1552_p4 = {{weights_39_q0[59:58]}};

assign local_temp_2_fu_1282_p4 = {{weights_39_q0[5:4]}};

assign local_temp_30_fu_1562_p4 = {{weights_39_q0[61:60]}};

assign local_temp_31_fu_1572_p4 = {{weights_39_q0[63:62]}};

assign local_temp_32_fu_1582_p4 = {{weights_39_q0[65:64]}};

assign local_temp_33_fu_1592_p4 = {{weights_39_q0[67:66]}};

assign local_temp_34_fu_1602_p4 = {{weights_39_q0[69:68]}};

assign local_temp_35_fu_1612_p4 = {{weights_39_q0[71:70]}};

assign local_temp_36_fu_1622_p4 = {{weights_39_q0[73:72]}};

assign local_temp_37_fu_1632_p4 = {{weights_39_q0[75:74]}};

assign local_temp_38_fu_1642_p4 = {{weights_39_q0[77:76]}};

assign local_temp_39_fu_1652_p4 = {{weights_39_q0[79:78]}};

assign local_temp_3_fu_1292_p4 = {{weights_39_q0[7:6]}};

assign local_temp_40_fu_1662_p4 = {{weights_39_q0[81:80]}};

assign local_temp_41_fu_1672_p4 = {{weights_39_q0[83:82]}};

assign local_temp_42_fu_1682_p4 = {{weights_39_q0[85:84]}};

assign local_temp_43_fu_1692_p4 = {{weights_39_q0[87:86]}};

assign local_temp_44_fu_1702_p4 = {{weights_39_q0[89:88]}};

assign local_temp_45_fu_1712_p4 = {{weights_39_q0[91:90]}};

assign local_temp_46_fu_1722_p4 = {{weights_39_q0[93:92]}};

assign local_temp_47_fu_1732_p4 = {{weights_39_q0[95:94]}};

assign local_temp_48_fu_1742_p4 = {{weights_39_q0[97:96]}};

assign local_temp_49_fu_1752_p4 = {{weights_39_q0[99:98]}};

assign local_temp_4_fu_1302_p4 = {{weights_39_q0[9:8]}};

assign local_temp_50_fu_1762_p4 = {{weights_39_q0[101:100]}};

assign local_temp_51_fu_1772_p4 = {{weights_39_q0[103:102]}};

assign local_temp_52_fu_1782_p4 = {{weights_39_q0[105:104]}};

assign local_temp_53_fu_1792_p4 = {{weights_39_q0[107:106]}};

assign local_temp_54_fu_1802_p4 = {{weights_39_q0[109:108]}};

assign local_temp_55_fu_1812_p4 = {{weights_39_q0[111:110]}};

assign local_temp_56_fu_1822_p4 = {{weights_39_q0[113:112]}};

assign local_temp_57_fu_1832_p4 = {{weights_39_q0[115:114]}};

assign local_temp_58_fu_1842_p4 = {{weights_39_q0[117:116]}};

assign local_temp_59_fu_1852_p4 = {{weights_39_q0[119:118]}};

assign local_temp_5_fu_1312_p4 = {{weights_39_q0[11:10]}};

assign local_temp_60_fu_1862_p4 = {{weights_39_q0[121:120]}};

assign local_temp_61_fu_1872_p4 = {{weights_39_q0[123:122]}};

assign local_temp_62_fu_1882_p4 = {{weights_39_q0[125:124]}};

assign local_temp_63_fu_1892_p4 = {{weights_39_q0[127:126]}};

assign local_temp_6_fu_1322_p4 = {{weights_39_q0[13:12]}};

assign local_temp_7_fu_1332_p4 = {{weights_39_q0[15:14]}};

assign local_temp_8_fu_1342_p4 = {{weights_39_q0[17:16]}};

assign local_temp_9_fu_1352_p4 = {{weights_39_q0[19:18]}};

assign local_temp_fu_1268_p1 = weights_39_q0[1:0];

assign mul_ln115_10_fu_2079_p0 = mul_ln115_10_fu_2079_p00;

assign mul_ln115_10_fu_2079_p00 = r_10_reg_3725;

assign mul_ln115_11_fu_2096_p0 = mul_ln115_11_fu_2096_p00;

assign mul_ln115_11_fu_2096_p00 = r_11_reg_3730;

assign mul_ln115_12_fu_2113_p0 = mul_ln115_12_fu_2113_p00;

assign mul_ln115_12_fu_2113_p00 = r_12_reg_3735;

assign mul_ln115_13_fu_2130_p0 = mul_ln115_13_fu_2130_p00;

assign mul_ln115_13_fu_2130_p00 = r_13_reg_3740;

assign mul_ln115_14_fu_2147_p0 = mul_ln115_14_fu_2147_p00;

assign mul_ln115_14_fu_2147_p00 = r_14_reg_3745;

assign mul_ln115_15_fu_2164_p0 = mul_ln115_15_fu_2164_p00;

assign mul_ln115_15_fu_2164_p00 = r_15_reg_3750;

assign mul_ln115_16_fu_2181_p0 = mul_ln115_16_fu_2181_p00;

assign mul_ln115_16_fu_2181_p00 = r_16_reg_3755;

assign mul_ln115_17_fu_2198_p0 = mul_ln115_17_fu_2198_p00;

assign mul_ln115_17_fu_2198_p00 = r_17_reg_3760;

assign mul_ln115_18_fu_2215_p0 = mul_ln115_18_fu_2215_p00;

assign mul_ln115_18_fu_2215_p00 = r_18_reg_3765;

assign mul_ln115_19_fu_2232_p0 = mul_ln115_19_fu_2232_p00;

assign mul_ln115_19_fu_2232_p00 = r_19_reg_3770;

assign mul_ln115_1_fu_1926_p0 = mul_ln115_1_fu_1926_p00;

assign mul_ln115_1_fu_1926_p00 = r_1_reg_3680;

assign mul_ln115_20_fu_2249_p0 = mul_ln115_20_fu_2249_p00;

assign mul_ln115_20_fu_2249_p00 = r_20_reg_3775;

assign mul_ln115_21_fu_2266_p0 = mul_ln115_21_fu_2266_p00;

assign mul_ln115_21_fu_2266_p00 = r_21_reg_3780;

assign mul_ln115_22_fu_2283_p0 = mul_ln115_22_fu_2283_p00;

assign mul_ln115_22_fu_2283_p00 = r_22_reg_3785;

assign mul_ln115_23_fu_2300_p0 = mul_ln115_23_fu_2300_p00;

assign mul_ln115_23_fu_2300_p00 = r_23_reg_3790;

assign mul_ln115_24_fu_2317_p0 = mul_ln115_24_fu_2317_p00;

assign mul_ln115_24_fu_2317_p00 = r_24_reg_3795;

assign mul_ln115_25_fu_2334_p0 = mul_ln115_25_fu_2334_p00;

assign mul_ln115_25_fu_2334_p00 = r_25_reg_3800;

assign mul_ln115_26_fu_2351_p0 = mul_ln115_26_fu_2351_p00;

assign mul_ln115_26_fu_2351_p00 = r_26_reg_3805;

assign mul_ln115_27_fu_2368_p0 = mul_ln115_27_fu_2368_p00;

assign mul_ln115_27_fu_2368_p00 = r_27_reg_3810;

assign mul_ln115_28_fu_2385_p0 = mul_ln115_28_fu_2385_p00;

assign mul_ln115_28_fu_2385_p00 = r_28_reg_3815;

assign mul_ln115_29_fu_2402_p0 = mul_ln115_29_fu_2402_p00;

assign mul_ln115_29_fu_2402_p00 = r_29_reg_3820;

assign mul_ln115_2_fu_1943_p0 = mul_ln115_2_fu_1943_p00;

assign mul_ln115_2_fu_1943_p00 = r_2_reg_3685;

assign mul_ln115_30_fu_2419_p0 = mul_ln115_30_fu_2419_p00;

assign mul_ln115_30_fu_2419_p00 = r_30_reg_3825;

assign mul_ln115_31_fu_2436_p0 = mul_ln115_31_fu_2436_p00;

assign mul_ln115_31_fu_2436_p00 = r_31_reg_3830;

assign mul_ln115_32_fu_2453_p0 = mul_ln115_32_fu_2453_p00;

assign mul_ln115_32_fu_2453_p00 = r_32_reg_3835;

assign mul_ln115_33_fu_2470_p0 = mul_ln115_33_fu_2470_p00;

assign mul_ln115_33_fu_2470_p00 = r_33_reg_3840;

assign mul_ln115_34_fu_2487_p0 = mul_ln115_34_fu_2487_p00;

assign mul_ln115_34_fu_2487_p00 = r_34_reg_3845;

assign mul_ln115_35_fu_2504_p0 = mul_ln115_35_fu_2504_p00;

assign mul_ln115_35_fu_2504_p00 = r_35_reg_3850;

assign mul_ln115_36_fu_2521_p0 = mul_ln115_36_fu_2521_p00;

assign mul_ln115_36_fu_2521_p00 = r_36_reg_3855;

assign mul_ln115_37_fu_2538_p0 = mul_ln115_37_fu_2538_p00;

assign mul_ln115_37_fu_2538_p00 = r_37_reg_3860;

assign mul_ln115_38_fu_2555_p0 = mul_ln115_38_fu_2555_p00;

assign mul_ln115_38_fu_2555_p00 = r_38_reg_3865;

assign mul_ln115_39_fu_2572_p0 = mul_ln115_39_fu_2572_p00;

assign mul_ln115_39_fu_2572_p00 = r_39_reg_3870;

assign mul_ln115_3_fu_1960_p0 = mul_ln115_3_fu_1960_p00;

assign mul_ln115_3_fu_1960_p00 = r_3_reg_3690;

assign mul_ln115_40_fu_2589_p0 = mul_ln115_40_fu_2589_p00;

assign mul_ln115_40_fu_2589_p00 = r_40_reg_3875;

assign mul_ln115_41_fu_2606_p0 = mul_ln115_41_fu_2606_p00;

assign mul_ln115_41_fu_2606_p00 = r_41_reg_3880;

assign mul_ln115_42_fu_2623_p0 = mul_ln115_42_fu_2623_p00;

assign mul_ln115_42_fu_2623_p00 = r_42_reg_3885;

assign mul_ln115_43_fu_2640_p0 = mul_ln115_43_fu_2640_p00;

assign mul_ln115_43_fu_2640_p00 = r_43_reg_3890;

assign mul_ln115_44_fu_2657_p0 = mul_ln115_44_fu_2657_p00;

assign mul_ln115_44_fu_2657_p00 = r_44_reg_3895;

assign mul_ln115_45_fu_2674_p0 = mul_ln115_45_fu_2674_p00;

assign mul_ln115_45_fu_2674_p00 = r_45_reg_3900;

assign mul_ln115_46_fu_2691_p0 = mul_ln115_46_fu_2691_p00;

assign mul_ln115_46_fu_2691_p00 = r_46_reg_3905;

assign mul_ln115_47_fu_2708_p0 = mul_ln115_47_fu_2708_p00;

assign mul_ln115_47_fu_2708_p00 = r_47_reg_3910;

assign mul_ln115_48_fu_2725_p0 = mul_ln115_48_fu_2725_p00;

assign mul_ln115_48_fu_2725_p00 = r_48_reg_3915;

assign mul_ln115_49_fu_2742_p0 = mul_ln115_49_fu_2742_p00;

assign mul_ln115_49_fu_2742_p00 = r_49_reg_3920;

assign mul_ln115_4_fu_1977_p0 = mul_ln115_4_fu_1977_p00;

assign mul_ln115_4_fu_1977_p00 = r_4_reg_3695;

assign mul_ln115_50_fu_2759_p0 = mul_ln115_50_fu_2759_p00;

assign mul_ln115_50_fu_2759_p00 = r_50_reg_3925;

assign mul_ln115_51_fu_2776_p0 = mul_ln115_51_fu_2776_p00;

assign mul_ln115_51_fu_2776_p00 = r_51_reg_3930;

assign mul_ln115_52_fu_2793_p0 = mul_ln115_52_fu_2793_p00;

assign mul_ln115_52_fu_2793_p00 = r_52_reg_3935;

assign mul_ln115_53_fu_2810_p0 = mul_ln115_53_fu_2810_p00;

assign mul_ln115_53_fu_2810_p00 = r_53_reg_3940;

assign mul_ln115_54_fu_2827_p0 = mul_ln115_54_fu_2827_p00;

assign mul_ln115_54_fu_2827_p00 = r_54_reg_3945;

assign mul_ln115_55_fu_2844_p0 = mul_ln115_55_fu_2844_p00;

assign mul_ln115_55_fu_2844_p00 = r_55_reg_3950;

assign mul_ln115_56_fu_2861_p0 = mul_ln115_56_fu_2861_p00;

assign mul_ln115_56_fu_2861_p00 = r_56_reg_3955;

assign mul_ln115_57_fu_2878_p0 = mul_ln115_57_fu_2878_p00;

assign mul_ln115_57_fu_2878_p00 = r_57_reg_3960;

assign mul_ln115_58_fu_2895_p0 = mul_ln115_58_fu_2895_p00;

assign mul_ln115_58_fu_2895_p00 = r_58_reg_3965;

assign mul_ln115_59_fu_2912_p0 = mul_ln115_59_fu_2912_p00;

assign mul_ln115_59_fu_2912_p00 = r_59_reg_3970;

assign mul_ln115_5_fu_1994_p0 = mul_ln115_5_fu_1994_p00;

assign mul_ln115_5_fu_1994_p00 = r_5_reg_3700;

assign mul_ln115_60_fu_2929_p0 = mul_ln115_60_fu_2929_p00;

assign mul_ln115_60_fu_2929_p00 = r_60_reg_3975;

assign mul_ln115_61_fu_2946_p0 = mul_ln115_61_fu_2946_p00;

assign mul_ln115_61_fu_2946_p00 = r_61_reg_3980;

assign mul_ln115_62_fu_2963_p0 = mul_ln115_62_fu_2963_p00;

assign mul_ln115_62_fu_2963_p00 = r_62_reg_3985;

assign mul_ln115_63_fu_2980_p0 = mul_ln115_63_fu_2980_p00;

assign mul_ln115_63_fu_2980_p00 = r_63_reg_3990;

assign mul_ln115_6_fu_2011_p0 = mul_ln115_6_fu_2011_p00;

assign mul_ln115_6_fu_2011_p00 = r_6_reg_3705;

assign mul_ln115_7_fu_2028_p0 = mul_ln115_7_fu_2028_p00;

assign mul_ln115_7_fu_2028_p00 = r_7_reg_3710;

assign mul_ln115_8_fu_2045_p0 = mul_ln115_8_fu_2045_p00;

assign mul_ln115_8_fu_2045_p00 = r_8_reg_3715;

assign mul_ln115_9_fu_2062_p0 = mul_ln115_9_fu_2062_p00;

assign mul_ln115_9_fu_2062_p00 = r_9_reg_3720;

assign mul_ln115_fu_1909_p0 = mul_ln115_fu_1909_p00;

assign mul_ln115_fu_1909_p00 = r_reg_3675;

assign nf_4_fu_581_p3 = ((icmp_ln174_fu_575_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_569_p2);

assign nf_fu_569_p2 = (ap_sig_allocacmp_nf_3 + 32'd1);

assign out_V_TDATA = result_2_fu_3615_p2;

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_1250_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_1250_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_1250_p1;

assign r_fu_610_p1 = arrayidx3_0_0_0_load22_fu_456[1:0];

assign result_2_fu_3615_p2 = (add_ln218_fu_3609_p2 + zext_ln218_fu_3587_p1);

assign result_fu_3563_p2 = (icmp_ln108_fu_3558_p2 ^ 1'd1);

assign sext_ln169_10_fu_3236_p1 = $signed(add_ln169_9_fu_3230_p2);

assign sext_ln169_11_fu_3240_p1 = $signed(add_ln169_10_reg_4040);

assign sext_ln169_12_fu_3243_p1 = $signed(add_ln169_11_reg_4045);

assign sext_ln169_13_fu_3252_p1 = $signed(add_ln169_12_fu_3246_p2);

assign sext_ln169_14_fu_3262_p1 = $signed(add_ln169_13_fu_3256_p2);

assign sext_ln169_15_fu_3272_p1 = $signed(add_ln169_15_reg_4050);

assign sext_ln169_16_fu_3275_p1 = $signed(add_ln169_16_reg_4055);

assign sext_ln169_17_fu_3284_p1 = $signed(add_ln169_17_fu_3278_p2);

assign sext_ln169_18_fu_3288_p1 = $signed(add_ln169_18_reg_4060);

assign sext_ln169_19_fu_3291_p1 = $signed(add_ln169_19_reg_4065);

assign sext_ln169_1_fu_3182_p1 = $signed(add_ln169_reg_4010);

assign sext_ln169_20_fu_3300_p1 = $signed(add_ln169_20_fu_3294_p2);

assign sext_ln169_21_fu_3310_p1 = $signed(add_ln169_21_fu_3304_p2);

assign sext_ln169_22_fu_3314_p1 = $signed(add_ln169_22_reg_4070);

assign sext_ln169_23_fu_3317_p1 = $signed(add_ln169_23_reg_4075);

assign sext_ln169_24_fu_3326_p1 = $signed(add_ln169_24_fu_3320_p2);

assign sext_ln169_25_fu_3330_p1 = $signed(add_ln169_25_reg_4080);

assign sext_ln169_26_fu_3333_p1 = $signed(add_ln169_26_reg_4085);

assign sext_ln169_27_fu_3342_p1 = $signed(add_ln169_27_fu_3336_p2);

assign sext_ln169_28_fu_3352_p1 = $signed(add_ln169_28_fu_3346_p2);

assign sext_ln169_29_fu_3362_p1 = $signed(add_ln169_31_reg_4090);

assign sext_ln169_2_fu_3185_p1 = $signed(add_ln169_1_reg_4015);

assign sext_ln169_30_fu_3365_p1 = $signed(add_ln169_32_reg_4095);

assign sext_ln169_31_fu_3374_p1 = $signed(add_ln169_33_fu_3368_p2);

assign sext_ln169_32_fu_3378_p1 = $signed(add_ln169_34_reg_4100);

assign sext_ln169_33_fu_3381_p1 = $signed(add_ln169_35_reg_4105);

assign sext_ln169_34_fu_3390_p1 = $signed(add_ln169_36_fu_3384_p2);

assign sext_ln169_35_fu_3532_p1 = $signed(add_ln169_37_reg_4195);

assign sext_ln169_36_fu_3400_p1 = $signed(add_ln169_38_reg_4110);

assign sext_ln169_37_fu_3403_p1 = $signed(add_ln169_39_reg_4115);

assign sext_ln169_38_fu_3412_p1 = $signed(add_ln169_40_fu_3406_p2);

assign sext_ln169_39_fu_3416_p1 = $signed(add_ln169_41_reg_4120);

assign sext_ln169_3_fu_3194_p1 = $signed(add_ln169_2_fu_3188_p2);

assign sext_ln169_40_fu_3419_p1 = $signed(add_ln169_42_reg_4125);

assign sext_ln169_41_fu_3428_p1 = $signed(add_ln169_43_fu_3422_p2);

assign sext_ln169_42_fu_3535_p1 = $signed(add_ln169_44_reg_4200);

assign sext_ln169_43_fu_3438_p1 = $signed(add_ln169_46_reg_4130);

assign sext_ln169_44_fu_3441_p1 = $signed(add_ln169_47_reg_4135);

assign sext_ln169_45_fu_3450_p1 = $signed(add_ln169_48_fu_3444_p2);

assign sext_ln169_46_fu_3454_p1 = $signed(add_ln169_49_reg_4140);

assign sext_ln169_47_fu_3457_p1 = $signed(add_ln169_50_reg_4145);

assign sext_ln169_48_fu_3466_p1 = $signed(add_ln169_51_fu_3460_p2);

assign sext_ln169_49_fu_3476_p1 = $signed(add_ln169_52_fu_3470_p2);

assign sext_ln169_4_fu_3198_p1 = $signed(add_ln169_3_reg_4020);

assign sext_ln169_50_fu_3480_p1 = $signed(add_ln169_53_reg_4150);

assign sext_ln169_51_fu_3483_p1 = $signed(add_ln169_54_reg_4155);

assign sext_ln169_52_fu_3492_p1 = $signed(add_ln169_55_fu_3486_p2);

assign sext_ln169_53_fu_3496_p1 = $signed(add_ln169_56_reg_4160);

assign sext_ln169_54_fu_3499_p1 = $signed(add_ln169_57_reg_4165);

assign sext_ln169_55_fu_3508_p1 = $signed(add_ln169_58_fu_3502_p2);

assign sext_ln169_56_fu_3518_p1 = $signed(add_ln169_59_fu_3512_p2);

assign sext_ln169_5_fu_3201_p1 = $signed(add_ln169_4_reg_4025);

assign sext_ln169_6_fu_3210_p1 = $signed(add_ln169_5_fu_3204_p2);

assign sext_ln169_7_fu_3220_p1 = $signed(add_ln169_6_fu_3214_p2);

assign sext_ln169_8_fu_3224_p1 = $signed(add_ln169_7_reg_4030);

assign sext_ln169_9_fu_3227_p1 = $signed(add_ln169_8_reg_4035);

assign sext_ln169_fu_2986_p1 = mul_ln115_63_fu_2980_p2;

assign sext_ln216_10_fu_2085_p1 = mul_ln115_10_fu_2079_p2;

assign sext_ln216_11_fu_2102_p1 = mul_ln115_11_fu_2096_p2;

assign sext_ln216_12_fu_2119_p1 = mul_ln115_12_fu_2113_p2;

assign sext_ln216_13_fu_2136_p1 = mul_ln115_13_fu_2130_p2;

assign sext_ln216_14_fu_2153_p1 = mul_ln115_14_fu_2147_p2;

assign sext_ln216_15_fu_2170_p1 = mul_ln115_15_fu_2164_p2;

assign sext_ln216_16_fu_2187_p1 = mul_ln115_16_fu_2181_p2;

assign sext_ln216_17_fu_2204_p1 = mul_ln115_17_fu_2198_p2;

assign sext_ln216_18_fu_2221_p1 = mul_ln115_18_fu_2215_p2;

assign sext_ln216_19_fu_2238_p1 = mul_ln115_19_fu_2232_p2;

assign sext_ln216_1_fu_1932_p1 = mul_ln115_1_fu_1926_p2;

assign sext_ln216_20_fu_2255_p1 = mul_ln115_20_fu_2249_p2;

assign sext_ln216_21_fu_2272_p1 = mul_ln115_21_fu_2266_p2;

assign sext_ln216_22_fu_2289_p1 = mul_ln115_22_fu_2283_p2;

assign sext_ln216_23_fu_2306_p1 = mul_ln115_23_fu_2300_p2;

assign sext_ln216_24_fu_2323_p1 = mul_ln115_24_fu_2317_p2;

assign sext_ln216_25_fu_2340_p1 = mul_ln115_25_fu_2334_p2;

assign sext_ln216_26_fu_2357_p1 = mul_ln115_26_fu_2351_p2;

assign sext_ln216_27_fu_2374_p1 = mul_ln115_27_fu_2368_p2;

assign sext_ln216_28_fu_2391_p1 = mul_ln115_28_fu_2385_p2;

assign sext_ln216_29_fu_2408_p1 = mul_ln115_29_fu_2402_p2;

assign sext_ln216_2_fu_1949_p1 = mul_ln115_2_fu_1943_p2;

assign sext_ln216_30_fu_2425_p1 = mul_ln115_30_fu_2419_p2;

assign sext_ln216_31_fu_2442_p1 = mul_ln115_31_fu_2436_p2;

assign sext_ln216_32_fu_2459_p1 = mul_ln115_32_fu_2453_p2;

assign sext_ln216_33_fu_2476_p1 = mul_ln115_33_fu_2470_p2;

assign sext_ln216_34_fu_2493_p1 = mul_ln115_34_fu_2487_p2;

assign sext_ln216_35_fu_2510_p1 = mul_ln115_35_fu_2504_p2;

assign sext_ln216_36_fu_2527_p1 = mul_ln115_36_fu_2521_p2;

assign sext_ln216_37_fu_2544_p1 = mul_ln115_37_fu_2538_p2;

assign sext_ln216_38_fu_2561_p1 = mul_ln115_38_fu_2555_p2;

assign sext_ln216_39_fu_2578_p1 = mul_ln115_39_fu_2572_p2;

assign sext_ln216_3_fu_1966_p1 = mul_ln115_3_fu_1960_p2;

assign sext_ln216_40_fu_2595_p1 = mul_ln115_40_fu_2589_p2;

assign sext_ln216_41_fu_2612_p1 = mul_ln115_41_fu_2606_p2;

assign sext_ln216_42_fu_2629_p1 = mul_ln115_42_fu_2623_p2;

assign sext_ln216_43_fu_2646_p1 = mul_ln115_43_fu_2640_p2;

assign sext_ln216_44_fu_2663_p1 = mul_ln115_44_fu_2657_p2;

assign sext_ln216_45_fu_2680_p1 = mul_ln115_45_fu_2674_p2;

assign sext_ln216_46_fu_2697_p1 = mul_ln115_46_fu_2691_p2;

assign sext_ln216_47_fu_2714_p1 = mul_ln115_47_fu_2708_p2;

assign sext_ln216_48_fu_2731_p1 = mul_ln115_48_fu_2725_p2;

assign sext_ln216_49_fu_2748_p1 = mul_ln115_49_fu_2742_p2;

assign sext_ln216_4_fu_1983_p1 = mul_ln115_4_fu_1977_p2;

assign sext_ln216_50_fu_2765_p1 = mul_ln115_50_fu_2759_p2;

assign sext_ln216_51_fu_2782_p1 = mul_ln115_51_fu_2776_p2;

assign sext_ln216_52_fu_2799_p1 = mul_ln115_52_fu_2793_p2;

assign sext_ln216_53_fu_2816_p1 = mul_ln115_53_fu_2810_p2;

assign sext_ln216_54_fu_2833_p1 = mul_ln115_54_fu_2827_p2;

assign sext_ln216_55_fu_2850_p1 = mul_ln115_55_fu_2844_p2;

assign sext_ln216_56_fu_2867_p1 = mul_ln115_56_fu_2861_p2;

assign sext_ln216_57_fu_2884_p1 = mul_ln115_57_fu_2878_p2;

assign sext_ln216_58_fu_2901_p1 = mul_ln115_58_fu_2895_p2;

assign sext_ln216_59_fu_2918_p1 = mul_ln115_59_fu_2912_p2;

assign sext_ln216_5_fu_2000_p1 = mul_ln115_5_fu_1994_p2;

assign sext_ln216_60_fu_2935_p1 = mul_ln115_60_fu_2929_p2;

assign sext_ln216_61_fu_2952_p1 = mul_ln115_61_fu_2946_p2;

assign sext_ln216_62_fu_2969_p1 = mul_ln115_62_fu_2963_p2;

assign sext_ln216_6_fu_2017_p1 = mul_ln115_6_fu_2011_p2;

assign sext_ln216_7_fu_2034_p1 = mul_ln115_7_fu_2028_p2;

assign sext_ln216_8_fu_2051_p1 = mul_ln115_8_fu_2045_p2;

assign sext_ln216_9_fu_2068_p1 = mul_ln115_9_fu_2062_p2;

assign sext_ln216_fu_1915_p1 = mul_ln115_fu_1909_p2;

assign tile_1_fu_1244_p2 = (tile_fu_444 + 32'd1);

assign tile_2_fu_1256_p3 = ((icmp_ln174_reg_3665[0:0] == 1'b1) ? 32'd0 : tile_1_fu_1244_p2);

assign weights_39_address0 = idxprom2_i26_fu_605_p1;

assign xor_ln108_1_fu_3599_p2 = (icmp_ln108_2_fu_3594_p2 ^ 1'd1);

assign xor_ln108_fu_3581_p2 = (icmp_ln108_1_fu_3576_p2 ^ 1'd1);

assign zext_ln108_1_fu_3573_p1 = p_ZL7threshs_1_load_reg_4175_pp0_iter4_reg;

assign zext_ln108_2_fu_3591_p1 = p_ZL7threshs_2_load_reg_4180_pp0_iter4_reg;

assign zext_ln108_fu_3555_p1 = p_ZL7threshs_0_load_reg_4170_pp0_iter4_reg;

assign zext_ln218_1_fu_3605_p1 = xor_ln108_1_fu_3599_p2;

assign zext_ln218_2_fu_3569_p1 = result_fu_3563_p2;

assign zext_ln218_fu_3587_p1 = xor_ln108_fu_3581_p2;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Batch
