# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/artti/Desktop/finn/notebooks/sat6_cnn/T1-8bit/build_t1w8/stitched_ip/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_MatrixVectorActivation_1_0/finn_design_MatrixVectorActivation_1_0.xci
# IP: The module: 'finn_design_MatrixVectorActivation_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/artti/Desktop/finn/notebooks/sat6_cnn/T1-8bit/build_t1w8/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_MatrixVectorActivation_1_0/constraints/MatrixVectorActivation_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_MatrixVectorActivation_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/artti/Desktop/finn/notebooks/sat6_cnn/T1-8bit/build_t1w8/stitched_ip/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_MatrixVectorActivation_1_0/finn_design_MatrixVectorActivation_1_0.xci
# IP: The module: 'finn_design_MatrixVectorActivation_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/artti/Desktop/finn/notebooks/sat6_cnn/T1-8bit/build_t1w8/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_MatrixVectorActivation_1_0/constraints/MatrixVectorActivation_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_MatrixVectorActivation_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
