// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FMPadding_Batch_0_FMPadding_Batch_0,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.393000,HLS_SYN_LAT=4627,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=53,HLS_SYN_LUT=368,HLS_VERSION=2023_2}" *)

module FMPadding_Batch_0 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln277_fu_150_p2;
wire   [0:0] brmerge5_i_i_fu_264_p2;
reg    ap_predicate_op47_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
reg   [0:0] icmp_ln277_reg_364;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln277_reg_364_pp0_iter1_reg;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg   [0:0] brmerge5_i_i_reg_368;
wire   [0:0] brmerge5_i_i_reg_368_pp0_iter0_reg;
reg   [7:0] outData_reg_372;
reg   [7:0] ap_phi_mux_outData_1_phi_fu_107_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_outData_1_reg_103;
reg   [2:0] sf_fu_70;
wire   [2:0] sf_3_fu_282_p3;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_sf_2;
reg   [5:0] x_fu_74;
wire   [5:0] select_ln278_fu_220_p3;
reg   [5:0] ap_sig_allocacmp_x_load;
reg   [8:0] indvar_flatten_fu_78;
wire   [8:0] select_ln278_1_fu_296_p3;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [5:0] y_fu_82;
wire   [5:0] select_ln277_1_fu_206_p3;
reg   [5:0] ap_sig_allocacmp_y_load;
reg   [12:0] indvar_flatten12_fu_86;
wire   [12:0] add_ln277_fu_156_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten12_load;
wire   [0:0] icmp_ln278_fu_168_p2;
wire   [0:0] icmp_ln279_fu_188_p2;
wire   [0:0] xor_ln277_fu_182_p2;
wire   [5:0] add_ln277_1_fu_200_p2;
wire   [5:0] select_ln277_fu_174_p3;
wire   [0:0] and_ln277_fu_194_p2;
wire   [5:0] x_2_fu_214_p2;
wire   [0:0] cmp9_not_i_i_fu_228_p2;
wire   [0:0] cmp10_not_i_i_fu_234_p2;
wire   [0:0] cmp12_not_i_i_fu_246_p2;
wire   [0:0] cmp14_not_i_i_fu_252_p2;
wire   [0:0] tmp1_fu_258_p2;
wire   [0:0] tmp_fu_240_p2;
wire   [0:0] or_ln279_fu_276_p2;
wire   [2:0] add_ln279_fu_270_p2;
wire   [8:0] add_ln278_1_fu_290_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_90;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 sf_fu_70 = 3'd0;
#0 x_fu_74 = 6'd0;
#0 indvar_flatten_fu_78 = 9'd0;
#0 y_fu_82 = 6'd0;
#0 indvar_flatten12_fu_86 = 13'd0;
end

FMPadding_Batch_0_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

FMPadding_Batch_0_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

FMPadding_Batch_0_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(ap_phi_mux_outData_1_phi_fu_107_p4),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((icmp_ln277_fu_150_p2 == 1'd0)) begin
            indvar_flatten12_fu_86 <= add_ln277_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_86 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((icmp_ln277_fu_150_p2 == 1'd0)) begin
            indvar_flatten_fu_78 <= select_ln278_1_fu_296_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_78 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((icmp_ln277_fu_150_p2 == 1'd0)) begin
            sf_fu_70 <= sf_3_fu_282_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_70 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((icmp_ln277_fu_150_p2 == 1'd0)) begin
            x_fu_74 <= select_ln278_fu_220_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_74 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_90)) begin
        if ((icmp_ln277_fu_150_p2 == 1'd0)) begin
            y_fu_82 <= select_ln277_1_fu_206_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_82 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        brmerge5_i_i_reg_368 <= brmerge5_i_i_fu_264_p2;
        icmp_ln277_reg_364 <= icmp_ln277_fu_150_p2;
        outData_reg_372 <= in0_V_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln277_reg_364_pp0_iter1_reg <= icmp_ln277_reg_364;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln277_fu_150_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln277_reg_364 == 1'd0)) begin
        if ((brmerge5_i_i_reg_368_pp0_iter0_reg == 1'd1)) begin
            ap_phi_mux_outData_1_phi_fu_107_p4 = 8'd0;
        end else if ((brmerge5_i_i_reg_368_pp0_iter0_reg == 1'd0)) begin
            ap_phi_mux_outData_1_phi_fu_107_p4 = outData_reg_372;
        end else begin
            ap_phi_mux_outData_1_phi_fu_107_p4 = ap_phi_reg_pp0_iter1_outData_1_reg_103;
        end
    end else begin
        ap_phi_mux_outData_1_phi_fu_107_p4 = ap_phi_reg_pp0_iter1_outData_1_reg_103;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_86;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_78;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_sf_2 = sf_fu_70;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 6'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_74;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 6'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_82;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op47_read_state1 == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op47_read_state1 == 1'b1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln277_reg_364_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((icmp_ln277_reg_364 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (icmp_ln277_reg_364 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (icmp_ln277_reg_364_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter2_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln277_1_fu_200_p2 = (ap_sig_allocacmp_y_load + 6'd1);

assign add_ln277_fu_156_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 13'd1);

assign add_ln278_1_fu_290_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln279_fu_270_p2 = (ap_sig_allocacmp_sf_2 + 3'd1);

assign and_ln277_fu_194_p2 = (xor_ln277_fu_182_p2 & icmp_ln279_fu_188_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op47_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln277_reg_364 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln277_reg_364 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln277_reg_364_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((icmp_ln277_reg_364_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_90 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter1_outData_1_reg_103 = 'bx;

always @ (*) begin
    ap_predicate_op47_read_state1 = ((brmerge5_i_i_fu_264_p2 == 1'd0) & (icmp_ln277_fu_150_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge5_i_i_fu_264_p2 = (tmp_fu_240_p2 | tmp1_fu_258_p2);

assign brmerge5_i_i_reg_368_pp0_iter0_reg = brmerge5_i_i_reg_368;

assign cmp10_not_i_i_fu_234_p2 = ((select_ln277_1_fu_206_p3 > 6'd32) ? 1'b1 : 1'b0);

assign cmp12_not_i_i_fu_246_p2 = ((select_ln278_fu_220_p3 == 6'd0) ? 1'b1 : 1'b0);

assign cmp14_not_i_i_fu_252_p2 = ((select_ln278_fu_220_p3 > 6'd32) ? 1'b1 : 1'b0);

assign cmp9_not_i_i_fu_228_p2 = ((select_ln277_1_fu_206_p3 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln277_fu_150_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 13'd4624) ? 1'b1 : 1'b0);

assign icmp_ln278_fu_168_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd136) ? 1'b1 : 1'b0);

assign icmp_ln279_fu_188_p2 = ((ap_sig_allocacmp_sf_2 == 3'd4) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign or_ln279_fu_276_p2 = (icmp_ln278_fu_168_p2 | and_ln277_fu_194_p2);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign select_ln277_1_fu_206_p3 = ((icmp_ln278_fu_168_p2[0:0] == 1'b1) ? add_ln277_1_fu_200_p2 : ap_sig_allocacmp_y_load);

assign select_ln277_fu_174_p3 = ((icmp_ln278_fu_168_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_x_load);

assign select_ln278_1_fu_296_p3 = ((icmp_ln278_fu_168_p2[0:0] == 1'b1) ? 9'd1 : add_ln278_1_fu_290_p2);

assign select_ln278_fu_220_p3 = ((and_ln277_fu_194_p2[0:0] == 1'b1) ? x_2_fu_214_p2 : select_ln277_fu_174_p3);

assign sf_3_fu_282_p3 = ((or_ln279_fu_276_p2[0:0] == 1'b1) ? 3'd1 : add_ln279_fu_270_p2);

assign tmp1_fu_258_p2 = (cmp14_not_i_i_fu_252_p2 | cmp12_not_i_i_fu_246_p2);

assign tmp_fu_240_p2 = (cmp9_not_i_i_fu_228_p2 | cmp10_not_i_i_fu_234_p2);

assign x_2_fu_214_p2 = (select_ln277_fu_174_p3 + 6'd1);

assign xor_ln277_fu_182_p2 = (icmp_ln278_fu_168_p2 ^ 1'd1);

endmodule //FMPadding_Batch_0
